STATES=("QUEUED","ATTEMPT_CREATED","SETUP_READY","WAITING_FOR_SLOT","SLOT_ACQUIRED","HOST_START_INTENT","HOST_STARTED","SOLVER_ENTRY_INTENT","SCIENTIFIC_SOLVER_ENTERED","SCIENTIFIC_SOLVER_RUNNING","SOLVER_RETURNED","NATIVE_TRUTH_PERSISTING","NATIVE_TRUTH_DURABLE","POSTPROCESSING","POST_FSP_VALID","RAW_VALID","SCIENTIFIC_VALID","HF_ARCHIVED","RELEASE_PENDING","RELEASED","FAILED_PREENTRY","FAILED_AFTER_ENTRY","AMBIGUOUS_QUARANTINED","CONTROL_PLANE_DEGRADED","PENDING_RECONCILE")
TERMINAL={"RELEASED","FAILED_PREENTRY","FAILED_AFTER_ENTRY","AMBIGUOUS_QUARANTINED"}

def replay_allowed(events):
    kinds={e.get("event_type") for e in events}
    return "SCIENTIFIC_SOLVER_ENTERED" not in kinds and "SCIENTIFIC_VALID" not in kinds

def release_allowed(events):
    kinds={e.get("event_type") for e in events}
    return "HF_ARCHIVED" in kinds and "SCIENTIFIC_VALID" in kinds
