"""APCD branch-neutral FDTD production framework."""

GLOBAL_CONTROL_PLANE_API_VERSION = "3.0"
GLOBAL_DB_SCHEMA_VERSION = 3
BRANCH_ENGINE_CONTRACT_VERSION = "1.0"
REFERENCE_ENGINE_VERSION = "1.0"
SHARED_ENGINE_RUNTIME_PATCH_VERSION = "3.0.1-entered-exception-isolation"
