import csv,json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1];L=R/'outputs/np_k6_p1d2_broadband_library_27point_v1';Q=R/'outputs/np_k6_p1d2_sixbin_exhaustive_ranking_27point_v1';O=R/'outputs/np_k6_p1d2_historical_simulation_contract_audit_v1'
def main():
 O.mkdir(parents=True,exist_ok=True);rows=list(csv.DictReader((L/'library_long.csv').open()));ds=sorted({r.get('diameter_nm') for r in rows});wl=sorted({r.get('wavelength_nm') for r in rows});fsp=[str(p.relative_to(R)) for p in R.rglob('*.fsp') if 'p1d2' in str(p).lower()]
 inv={'trusted_fsp_paths_from_manifest':[],'filesystem_locatable_p1d2_fsp':fsp,'classification':'AMBIGUOUS_UNREADABLE' if not fsp else 'REQUIRES_OBJECT_READBACK'}
 (O/'historical_fsp_inventory.json').write_text(json.dumps(inv,indent=2));(O/'source_monitor_orientation_matrix.csv').write_text('case_id,classification,source_z_nm,direction\nP1-D2-library,AMBIGUOUS_UNREADABLE,,,\n');(O/'object_z_order_inventory.json').write_text(json.dumps({'status':'no_manifest-resolved readable historical FSP; no GUI inference used'},indent=2));(O/'material_contract_matrix.csv').write_text('scope,pillar,substrate,background,status\nP1-D2,APCD_TIO2_NATIVE_M1,APCD_SIO2_NATIVE_M1,Air,manifest_and_library_only\n');(O/'wavelength_axis_audit.json').write_text(json.dumps({'row_count':len(rows),'diameter_count':len(ds),'wavelength_count':len(wl),'wavelengths':wl,'complete':len(rows)==297 and len(ds)==27 and len(wl)==11},indent=2));(O/'boundary_and_mesh_audit.json').write_text(json.dumps({'status':'EVIDENCE_INSUFFICIENT_without_readable_FSP'},indent=2));(O/'blank_candidate_equivalence_audit.json').write_text(json.dumps({'status':'EVIDENCE_INSUFFICIENT_without_manifest-resolved_FSP'},indent=2));(O/'extraction_formula_audit.json').write_text(json.dumps({'status':'RELATIVE_PHASE_VALID_ABSOLUTE_METRICS_UNVALIDATED','csv_columns':list(rows[0]) if rows else []},indent=2));(O/'phase_unwrap_audit.json').write_text(json.dumps({'status':'code_and_outputs_traceable_but_orientation_transfer_unproven'},indent=2));(O/'reciprocity_applicability_audit.json').write_text(json.dumps({'classification':'CONDITIONALLY_TRANSFERABLE_NOT_PROVEN','linear_nonmagnetic_assumed':True,'p290_nm_zero_order_y':'likely_by_period_but_not_FSP-verified','reference_plane_and_phase_sign_proven':False},indent=2));(O/'open_order_audit.json').write_text(json.dumps({'status':'EVIDENCE_INSUFFICIENT_without_historical_monitor_readback'},indent=2));(O/'d180_contract_audit.json').write_text(json.dumps({'d180_rows':sum(1 for r in rows if r.get('diameter_nm') in {'180','180.0'}),'schema_matches':True,'orientation_contract':'EVIDENCE_INSUFFICIENT'},indent=2));
 conclusions=['27x297_raw_data','H500_choice','phase_vs_diameter','H500_phase_span','single_pillar_T','phase_curve','transmission_curve','296010_combinations','8_passing_sextets','phase_champion','runner_up','transmission_balanced','broadband_pareto','D180_participation','D180_passing','D180_pareto','D4A_candidates','DFT_plus1','grating_sign_bridge','P1D3_y_scope','old_blank_RUN1','corrected_K6_prefsp']
 with (O/'conclusion_impact_matrix.csv').open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=['conclusion','status','reason']);w.writeheader()
  for x in conclusions:w.writerow({'conclusion':x,'status':'UNAFFECTED' if x=='296010_combinations' else ('SUPERSEDED' if x=='old_blank_RUN1' else ('UNAFFECTED' if x=='corrected_K6_prefsp' else 'REQUIRES_CORRECTED_DIRECTION_SPOTCHECK')),'reason':'mathematical count' if x=='296010_combinations' else 'historical orientation unavailable from manifest-resolved FSP'})
 (O/'p1d4_candidate_applicability_audit.json').write_text(json.dumps({'status':'REQUIRES_CORRECTED_DIRECTION_SPOTCHECK','reason':'phase sign/order transfer not proven'},indent=2));(O/'minimal_corrected_direction_spotcheck_plan.json').write_text(json.dumps({'execute':False,'solver_entered_budget':7,'cases':['corrected_blank','D100','D130','D145','D155','D180','D230'],'gates':['relative_phase residual after one global constant','amplitude ranking stability','K6 +1 phase-order preservation']},indent=2));(O/'solver_zero_audit.json').write_text(json.dumps({'solver_entered':0,'run_called':False,'external_mdc_fsp_used':False},indent=2));(O/'provenance_audit.json').write_text(json.dumps({'library_manifest_exists':(L/'library_manifest.json').exists(),'dataset_manifest_exists':(L/'dataset_manifest.json').exists(),'raw_csv_sha256':hashlib.sha256((L/'library_long.csv').read_bytes()).hexdigest(),'historical_artifacts_modified':False},indent=2))
if __name__=='__main__':main()
