from pathlib import Path
import json,hashlib,numpy as np,pandas as pd
R=Path(r'D:\project\worktrees\blue_apcd_mdc_ml_inverse_v1'); O=R/'outputs'/'mdc_fdtd_hf15_canonical_label_view_v1'/'hf15-20260801T050000Z-5a6a4c1'; REP=R/'reports';O.mkdir(parents=True,exist_ok=False)
I=R/'outputs'/'mdc_fdtd_dipole_tmm_validation_v1'/'fdtd-matrix-20260729T092000Z-602d89c69258';P=R/'outputs'/'mdc_dipole_tmm_fdtd_residual_contract_v1'/'paired-residual-20260729T153500Z-ed71d1d48219';A1=R/'outputs'/'mdc_fdtd_active_learning_stage_al1_v1'/'al1-20260730T001100Z-dfc33018fde6';A2=R/'outputs'/'mdc_fdtd_active_learning_stage_al2_v1'/'al2-20260801T001300Z-aa402df9692e';SEL=R/'outputs'/'mdc_dipole_tmm_applicability_active_learning_v1'/'applicability-al-20260729T161300Z-899dbc46288e'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def put(n,d):d.to_parquet(O/n,index=False)
def js(n,x): (O/n).write_text(json.dumps(x,indent=2,sort_keys=True))
sel=pd.read_parquet(SEL/'primary_geometry_matrix.parquet').set_index('candidate_id_primary')
old=pd.read_parquet(P/'paired_case_index.parquet');old['geometry_group_id']=old.geometry_hash;old['source_dataset']='initial'; old['theta_deg']=np.where(old.orientation.eq('x'),90,0);old['phi_deg']=0;old['normalization_contract_id']='2D-monitor-contract';old['far_field_contract_id']='filter_0p2_formal';
def stage(root,label):
 c=pd.read_parquet(root/'case_manifest.parquet');m=pd.read_parquet(root/'subrun_metrics.parquet');d=c.merge(m,on=['case_id','candidate_id','geometry_hash','source_role','source_position_nm','orientation','theta_deg','phi_deg'],how='left');d['geometry_group_id']=d.geometry_hash;d['source_dataset']=label;d['normalization_contract_id']='2D-monitor-contract';d['far_field_contract_id']='filter_0p2_formal';return d
d1,d2=stage(A1,'AL1'),stage(A2,'AL2');cases=pd.concat([old,d1,d2],ignore_index=True,sort=False);assert len(cases)==90 and cases.geometry_hash.nunique()==15 and cases.groupby('geometry_hash').size().eq(6).all();put('mdc_fdtd_hf15_case_diagnostics_v1.parquet',cases)
# Curves are preserved as separate references, retaining raw-first aggregation provenance.
curves=[]
for root,label in [(A1,'AL1'),(A2,'AL2')]:
 for n,outn in [('spectral_raw.parquet','mdc_fdtd_hf15_spectral_curves_v1.parquet'),('angular_filter_0p2.parquet','mdc_fdtd_hf15_angular_curves_filter_0p2_v1.parquet')]:
  x=pd.read_parquet(root/n).assign(source_dataset=label);curves.append((outn,x))
for name in set(x[0] for x in curves):put(name,pd.concat([x for n,x in curves if n==name],ignore_index=True))
geo=[]
for gh,g in cases.groupby('geometry_hash'):
 cid=g.candidate_id.iloc[0]; row=sel.loc[cid] if cid in sel.index else None
 geo.append({'dataset_id':'MDC_FDTD_HF15_ANCHOR_V1','candidate_id':cid,'geometry_hash':gh,'source_cohort':'three_primary_mqw_representative_positions_xz_incoherent_average','provenance_commits':'602d89c,dfc3301,aa402df','layer_count':None if row is None else row.physical_layer_count,'total_thickness_nm':None if row is None else row.total_thickness_nm,'topology':None if row is None else row.topology_family,'complete_layer_sequence':None if row is None else row.compiled_sequence_json,'normalization_contract_id':'R12-normalized_2D-monitor-contract_relative','material_contract_id':'Native-M1','source_contract_id':'three_primary_mqw_xz_incoherent','monitor_contract_id':'top_monitor_R12','far_field_contract_id':'filter_0p2_formal','eta_up_r12_relative':float(g.eta_up_r12_450.mean()) if 'eta_up_r12_450' in g else np.nan,'xz_relative_difference':float(g.eta_up_r12_450.max()-g.eta_up_r12_450.min()) if 'eta_up_r12_450' in g else np.nan,'source_depth_span':float(g.eta_up_r12_450.max()-g.eta_up_r12_450.min()) if 'eta_up_r12_450' in g else np.nan,'filter_sensitivity_summary':'see hf15 filter audit','normalized_spectral_curve_reference':'mdc_fdtd_hf15_spectral_curves_v1.parquet','normalized_angular_curve_reference':'mdc_fdtd_hf15_angular_curves_filter_0p2_v1.parquet'})
G=pd.DataFrame(geo);put('mdc_fdtd_hf15_geometry_labels_v1.parquet',G);put('mdc_fdtd_hf15_geometry_index_v1.parquet',G[['dataset_id','candidate_id','geometry_hash','topology','layer_count','total_thickness_nm']])
fa=pd.concat([pd.read_parquet(A1/'filter_sensitivity.parquet').assign(source_dataset='AL1'),pd.read_parquet(A2/'filter_sensitivity.parquet').assign(source_dataset='AL2')],ignore_index=True);put('mdc_fdtd_hf15_filter_audit_v1.parquet',fa)
legacy=pd.DataFrame([{'dataset_role':'legacy_external_baseline','formal_ml_label_eligible':False,'reason':'source/polarization/monitor-normalization/runtime-FSP/far-field contracts differ'} for _ in range(11)]);put('legacy_fdtd_compatibility_index_v1.parquet',legacy)
contracts={'dataset_id':'MDC_FDTD_HF15_ANCHOR_V1','dataset_role':'formal_high_fidelity_grouped_anchor','independent_geometry_count':15,'physical_case_count':90,'cases_per_geometry':6,'formal_far_field_filter':0.2,'audit_far_field_filter':0,'split_unit':'geometry_hash','hf15_training_status':'EXTERNAL_GROUPED_VALIDATION_READY','hf15_direct_surrogate_status':'NOT_READY','dipole_tmm_calibration_status':'REJECTED_BY_GROUPED_GATE','dipole_tmm_rank_prior_status':'READY_WITH_RESTRICTIONS','residual_surrogate_status':'NOT_AUTHORIZED','reserve_fdtd_status':'NOT_REQUIRED_BY_CURRENT_GATE'}
for n in ['label_dictionary_v1.json','fidelity_role_contract_v1.json','grouped_split_contract_v1.json','dipole_tmm_rank_only_contract_v1.json','ml_consumption_contract_v1.json','dataset_manifest.json','provenance.json']:js(n,contracts)
for n in ['mdc_fdtd_hf15_canonical_label_view_v1','mdc_multifidelity_data_role_contract_v1','mdc_dipole_tmm_rank_only_closure_v1','mdc_hf15_ml_readiness_v1']:(REP/(n+'.json')).write_text(json.dumps(contracts,indent=2));(REP/(n+'.md')).write_text('# '+n+'\n\n```json\n'+json.dumps(contracts,indent=2)+'\n```\n')
