from pathlib import Path
import hashlib, json, csv

HERE=Path(__file__).resolve(); ROOT=HERE.parent.parent if HERE.parent.name=='scripts' else HERE.parent
TRAIN=ROOT/'outputs/mdc_non_hf15_fixed_v1_internal_retrain_oof_v1/20260802T091739Z_90abc54ff31f_datafrozen_modelfrozen'
PROMO=ROOT/'outputs/mdc_replacement_hf_external_r12_solver_evaluation_v1/20260802T150000Z_R12_SOLVER/promotion_review'
OUT=PROMO/'training_history_scope'; OUT.mkdir(exist_ok=True)
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(n,o): (OUT/n).write_text(json.dumps(o,indent=2,sort_keys=True)+'\n',encoding='utf-8')
source=ROOT/'scripts/run_mdc_non_hf15_fixed_v1_internal_retrain_oof_v1.py'; code=source.read_text(encoding='utf-8')
def recorded(value,evidence): return {'value':value,'evidence':evidence}
contract={'architecture':recorded('MLP 150 -> 256 -> 128 -> 4; ReLU; Dropout(0.1) after first two hidden layers',str(source)),'optimizer':recorded('AdamW',str(source)),'learning_rate':recorded(7e-4,str(source)),'weight_decay':recorded(1e-5,str(source)),'loss_function':recorded('SmoothL1Loss',str(source)),'smooth_l1_beta':recorded('1.0 (library default; beta not passed explicitly)',str(source)),'batch_size':recorded(128,str(source)),'max_epochs':recorded(240,str(source)),'early_stopping_patience':recorded(35,str(source)),'min_delta':recorded(1e-7,str(source)),'fold_seeds':recorded([20260720,20260721,20260722],str(source)),'final_seeds':recorded([20260720,20260721,20260722],str(source)),'target_transforms':recorded('StandardScaler features; target mean/std standardization; sd floor 1',str(source)),'target_loss_weighting':recorded('none; finite-element mask with unweighted SmoothL1 mean',str(source)),'scheduler':recorded('none',str(source)),'gradient_clipping':recorded('none',str(source)),'source_sha256':sha(source),'history_persistence':'NOT_RECORDED'}
dump('regression_training_contract_extracted.json',contract)

events=(TRAIN/'logs/job_events.jsonl').read_text().splitlines(); event_sha=sha(TRAIN/'logs/job_events.jsonl')
fit_rows=[]; fold_rows={}
import pandas as pd
for p in sorted((TRAIN/'regression_oof').glob('ensemble_fold*.parquet')): fold_rows[int(p.stem.replace('ensemble_fold',''))]=len(pd.read_parquet(p))
for fold in range(4):
    for seed in [20260720,20260721,20260722]:
        pt=TRAIN/f'checkpoints/regression_{fold}_{seed}.pt'; jb=TRAIN/f'checkpoints/regression_{fold}_{seed}.joblib'
        fit_rows.append({'fit_id':f'regression_oof_fold{fold}_seed{seed}','fold':fold,'seed':seed,'train_rows':'NOT_RECORDED','validation_rows':fold_rows.get(fold,'NOT_RECORDED'),'epochs_ran':'NOT_RECORDED','best_epoch':'NOT_RECORDED','stopped_epoch':'NOT_RECORDED','stopping_reason':'NOT_RECORDED','best_train_loss':'NOT_RECORDED','best_validation_loss':'NOT_RECORDED','final_train_loss':'NOT_RECORDED','final_validation_loss':'NOT_RECORDED','checkpoint_epoch':'NOT_RECORDED','checkpoint_metric':'NOT_RECORDED','loss_unit':'standardized target space','history_source_file':str(pt),'history_source_sha256':sha(pt),'model_source_file':str(jb),'model_source_sha256':sha(jb),'fit_manifest_source':str(TRAIN/'logs/job_events.jsonl'),'fit_manifest_sha256':event_sha,'history_status':'PARTIALLY_UNRECORDED_NO_HISTORY_PERSISTED'})
dump('regression_oof_fit_history.json',{'fits':fit_rows,'fit_count':len(fit_rows),'history_status':'PARTIALLY_UNRECORDED_NO_HISTORY_PERSISTED'})
with (OUT/'regression_oof_fit_history.csv').open('w',newline='',encoding='utf-8') as f:
    w=csv.DictWriter(f,fieldnames=fit_rows[0].keys()); w.writeheader(); w.writerows(fit_rows)
summary={'fit_count':12,'epochs_ran':{'min':'NOT_RECORDED','median':'NOT_RECORDED','mean':'NOT_RECORDED','max':'NOT_RECORDED'},'best_epoch':{'min':'NOT_RECORDED','median':'NOT_RECORDED','mean':'NOT_RECORDED','max':'NOT_RECORDED'},'best_validation_loss':{'min':'NOT_RECORDED','median':'NOT_RECORDED','mean':'NOT_RECORDED','max':'NOT_RECORDED'},'final_validation_loss':{'min':'NOT_RECORDED','median':'NOT_RECORDED','mean':'NOT_RECORDED','max':'NOT_RECORDED'},'early_stopped_count':'NOT_RECORDED','reached_max_epoch_count':'NOT_RECORDED','per_seed_summary':{str(s):{'fit_count':4,'validation_rows_total':sum(fold_rows.values()),'epochs':'NOT_RECORDED','losses':'NOT_RECORDED'} for s in [20260720,20260721,20260722]},'per_fold_summary':{str(f):{'fit_count':3,'validation_rows_per_fit':fold_rows.get(f,'NOT_RECORDED'),'epochs':'NOT_RECORDED','losses':'NOT_RECORDED'} for f in range(4)},'history_status':'PARTIALLY_UNRECORDED_NO_HISTORY_PERSISTED'}
dump('regression_oof_training_summary.json',summary)

final_rows=[]
for seed in [20260720,20260721,20260722]:
    pt=TRAIN/f'checkpoints/regression_final_{seed}.pt'; jb=TRAIN/f'checkpoints/regression_final_{seed}.joblib'
    final_rows.append({'seed':seed,'train_membership':'eligible original training rows only','validation_membership':'same training membership passed as V/W; not independent','validation_membership_present':True,'epochs_ran':'NOT_RECORDED','selected_epoch':'NOT_RECORDED','epoch_selection_rule':'best in-sample validation MAE with min_delta=1e-7 and patience=35','stopping_reason':'NOT_RECORDED','train_loss_history':'NOT_RECORDED','validation_loss_history':'NOT_RECORDED','best_train_loss':'NOT_RECORDED','best_validation_loss':'NOT_RECORDED','checkpoint_sha256':sha(pt),'model_sha256':sha(jb),'history_source_sha256':event_sha,'status':'FINAL_EARLY_STOPPING_ON_TRAIN_MEMBERSHIP_HISTORY_NOT_RECORDED'})
dump('regression_final_training_summary.json',{'fit_count':3,'fits':final_rows,'final_epoch_status':'NOT_RECORDED','frozen_epoch_refit':False,'independent_validation':False,'history_status':'PARTIALLY_UNRECORDED_NO_HISTORY_PERSISTED'})
with (OUT/'regression_final_fit_history.csv').open('w',newline='',encoding='utf-8') as f:
    w=csv.DictWriter(f,fieldnames=final_rows[0].keys()); w.writeheader(); w.writerows(final_rows)

cal= json.loads((ROOT/'outputs/mdc_fixed_v1_classification_canonicalization_v1/20260802T101700Z_90abc54ff31f/manifests/calibration_contract.json').read_text())
thr= json.loads((ROOT/'outputs/mdc_fixed_v1_classification_canonicalization_v1/20260802T101700Z_90abc54ff31f/manifests/threshold_contract.json').read_text())
canon_obj=json.loads((ROOT/'outputs/mdc_fixed_v1_classification_canonicalization_v1/20260802T101700Z_90abc54ff31f/manifests/canonical_classifier_bundle_manifest.json').read_text())
class_summary={'model_id':'MDC_CLASSIFICATION_EXTRATREES_CALIBRATED_V1','estimator':'ExtraTreesClassifier','n_estimators':384,'min_samples_leaf':2,'class_weight':'balanced','max_features':1.0,'final_fit_seed':20260720,'canonical_final_fit_api_calls':1,'target_heads':4,'ensemble':False,'epoch':'NOT_APPLICABLE_NO_EPOCH','neural_network_loss':'NOT_APPLICABLE_NO_NEURAL_NETWORK','calibration_method':{d['target']:d['method'] for d in cal['details']},'calibration_brier_recorded':{d['target']:d['brier'] for d in cal['details']},'calibration_rows':{d['target']:d['calibration_rows'] for d in cal['details']},'validation_rows':{d['target']:d['validation_rows'] for d in cal['details']},'thresholds':thr['thresholds'],'threshold_procedure':thr['procedure'],'threshold_membership':thr['membership'],'bundle_sha256':canon_obj['bundle_sha256'],'history_status':'NOT_APPLICABLE_CLASSIFIER_HAS_NO_EPOCH_LOSS'}
dump('classification_training_and_calibration_summary.json',class_summary)
(OUT/'classification_no_epoch_loss_scope_statement.md').write_text('# Classification training scope\n\nThe canonical classifier is ExtraTreesClassifier, not a neural network. Epoch counts and neural-network train/validation loss are not applicable. Recorded evidence is the frozen one-fit bundle, per-head calibration Brier values, calibration rows, validation rows, isotonic methods, and frozen thresholds. No metrics are recomputed.\n',encoding='utf-8')

registry={'overall_quantitative_high_fidelity_scope':'REJECTED','spectral_fwhm':{'quantitative_hf_use':'REJECTED','rank_only_use':'REJECTED','allowed_use':['NON_HF15_INTERNAL_REGRESSION','DESCRIPTIVE_R12_REPORTING'],'reason':['LARGE_SYSTEMATIC_UNDERPREDICTION','ROUTED_RANK_REVERSAL','ROUTED_N_TOO_SMALL']},'angular_fwhm':{'quantitative_hf_use':'REJECTED','rank_only_use':'REJECTED','allowed_use':['NON_HF15_INTERNAL_REGRESSION','DESCRIPTIVE_R12_REPORTING'],'reason':['LARGE_SYSTEMATIC_UNDERPREDICTION','WEAK_FULL_AND_ROUTED_RANK_CORRELATION']},'cone5':{'quantitative_hf_use':'REJECTED','rank_only_use':'EXPLORATORY_ELIGIBILITY_ROUTED_ONLY','allowed_use':['NON_HF15_INTERNAL_REGRESSION','FROZEN_ELIGIBILITY_ROUTED_CANDIDATE_PRIORITIZATION','DESCRIPTIVE_R12_REPORTING'],'mandatory_conditions':['USE_ONLY_PREDEFINED_ELIGIBLE_SUBSET','DO_NOT_INTERPRET_PREDICTED_VALUE_QUANTITATIVELY','REQUIRE_FDTD_CONFIRMATION_FOR_FINAL_SELECTION','REPORT_N_AND_ROUTING_COVERAGE','NO_PROMOTION_CLAIM'],'reason':['ROUTED_SPEARMAN_0_7_WITH_N_5','FULL_COHORT_RANK_EVIDENCE_WEAK','SMALL_N_EXPLORATORY_ONLY']},'normal_band_transmission':{'quantitative_hf_use':'NOT_APPLICABLE','rank_only_use':'NOT_AUTHORIZED','allowed_use':['NON_HF15_INTERNAL_REGRESSION'],'reason':['NOT_NUMERICALLY_COMPARABLE_TO_ETA_UP_R12_RELATIVE']},'classification':{'semantic':'REGRESSION_ELIGIBILITY','allowed_use':['NON_HF15_INTERNAL_ROUTING','FROZEN_TARGETWISE_ELIGIBILITY_ROUTING'],'prohibited_claim':'PHYSICAL_PERFORMANCE_CLASSIFICATION_VALIDATION'}}
dump('fixed_v1_targetwise_scope_registry.json',registry)
(OUT/'targetwise_scope_report.md').write_text('# Target-wise fixed-v1 scope\n\nOverall quantitative high-fidelity scope is **REJECTED**. Spectral and angular FWHM are limited to NON-HF15 internal regression and descriptive R12 reporting. Cone5 is exploratory eligibility-routed prioritization only and requires FDTD confirmation; its predicted value is not quantitative evidence. The normal-band transmission proxy is not comparable to `eta_up_r12_relative`. Classification remains regression eligibility, not physical-performance validation.\n',encoding='utf-8')
(OUT/'training_history_extraction_report.md').write_text('# Frozen training-history extraction\n\nThe training contract is extracted from the frozen training script and manifests. The frozen run contains 12 regression OOF checkpoint pairs and 3 final checkpoint pairs, but no serialized epoch-by-epoch loss history, best epoch, stopping epoch, or loss values. These fields are explicitly reported as `NOT_RECORDED`; they are not reconstructed from weights or external metrics. Final fits pass the training membership as their validation argument, so no independent final validation history is claimed.\n',encoding='utf-8')

completion_out={'status':'MDC_FIXED_V1_TARGETWISE_SCOPE_FROZEN_TRAINING_HISTORY_PARTIALLY_UNRECORDED','scope_freeze':'PASS','training_history_extraction':'PARTIALLY_UNRECORDED','oof_fits':12,'final_fits':3,'new_fits':0,'optimizer_backward':0,'new_metric_definitions':0,'solver_calls':0,'TMM_calls':0,'RCWA_calls':0,'HF15_reads':0,'sealed_test_reads':0}
dump('completion_manifest.json',completion_out)
files={str(p.relative_to(OUT)).replace('\\','/'):sha(p) for p in sorted(OUT.rglob('*')) if p.is_file() and p.name!='artifact_sha256.json'}
dump('artifact_sha256.json',files)
print(json.dumps(completion_out,sort_keys=True))
