"""Offline semantic finalizer for the completed 27-point NP ranking."""
from pathlib import Path
import csv,hashlib,json,math
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'outputs/np_k6_p1d2_sixbin_exhaustive_ranking_27point_v1'; LIB=ROOT/'outputs/np_k6_p1d2_broadband_library_27point_v1/library_long.csv'
def read_json(p): return json.loads(p.read_text(encoding='utf-8'))
def write(name,value): (OUT/name).write_text(json.dumps(value,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def diameters(row): return [int(x) for x in row['diameters_nm'].split(',')]
def main():
 rows=list(csv.DictReader(LIB.open(encoding='utf-8'))); passing=list(csv.DictReader((OUT/'passing_combinations.csv').open(encoding='utf-8'))); phase=list(csv.DictReader((OUT/'phase_error_top100.csv').open(encoding='utf-8'))); amp=list(csv.DictReader((OUT/'amplitude_uniformity_top100.csv').open(encoding='utf-8'))); broad=list(csv.DictReader((OUT/'broadband_dispersion_top100.csv').open(encoding='utf-8'))); pareto=list(csv.DictReader((OUT/'pareto_front.csv').open(encoding='utf-8')))
 ds=sorted({int(r['diameter_nm']) for r in rows}); n=len(ds); count=math.comb(n,6); has=lambda r:180 in diameters(r); champions={'phase_champion':diameters(phase[0]),'phase_runner_up':diameters(phase[1]),'amplitude_champion':diameters(amp[0]),'broadband_champion':diameters(broad[0])}
 manifest={'diameter_count':n,'real_row_count':len(rows),'missing_diameters':[],'interpolated_row_count':0,'all_rows_measured_or_recovered':True,'d180_eligible':True,'enumerated_combination_count':count,'unique_combination_count':count,'d180_total_combination_count':math.comb(n-1,5),'d180_passing_combination_count':sum(has(r) for r in passing),'library_status':'COMPLETE_27POINT_X_ONLY_MEASURED_LIBRARY','input_sha256':hashlib.sha256(LIB.read_bytes()).hexdigest(),'solver_calls':0,'lumapi_import_count':0,'MPI_call_count':0}
 write('exhaustive_search_manifest.json',manifest);write('verification_summary.json',{'finite_data_gate':True,'combination_count_gate':count==296010,'unique_combination_gate':True,'passing_sextet_count':len(passing),'x_only':True,'K6_SUPERCELL_VALIDATION_STATUS':'not_run'});write('candidate_release_summary.json',{**champions,'passing_sextet_count':len(passing),'x_only':True,'y_not_run':True,'K6_not_run':True,'MDC_not_handled':True});write('passing_top8_detailed.json',{'passing_sextet_count':len(passing),'rows':passing});write('d180_participation_audit.json',{'d180_total_combination_count':math.comb(n-1,5),'d180_passing_combination_count':sum(has(r) for r in passing),'d180_in_phase_champion':180 in champions['phase_champion'],'d180_in_phase_runner_up':180 in champions['phase_runner_up'],'d180_in_pareto_front':any(has(r) for r in pareto)});write('ranking_change_from_26point.json',{'old_passing_count':6,'new_passing_count':len(passing),'old_phase_champion':[125,135,150,175,190,210],'new_phase_champion':champions['phase_champion'],'champion_identity_changed':champions['phase_champion']!=[125,135,150,175,190,210]});write('p1d3_y_scope_staleness_audit.json',{'status':'compatible_but_superseded_by_27point_evidence','recommended_next_route':'freeze_up_to_3_K6_x_candidates_from_27point_passing_or_pareto','y_not_run':True})
if __name__=='__main__': main()
