from __future__ import annotations
import csv,hashlib,json,math,os,shutil,uuid
from pathlib import Path
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4');O=R/'outputs';ML=O/'lp_ml_dataset_v1';C20=ML/'canonical_v1_20';C21=ML/'canonical_v1_21';ST=ML/'staging/b120_j2lm06_stage_d5_perturbation_data_finalized_lp_ml_schema_v1_21';A=ML/'analysis';P=ML/'plans'
PROT={R/'reports/lp_ml1a3_git_history_geometry_reconstruction.md':'21c6884f71bad6bd6779d7ccc90cec55ab1a94e239f849ea74a942bdd50edd6a',R/'reports/stage11_4a20_legacy_fsp_object_inventory.md':'ae3b13341547e13ca85ca763ed8265591c100ac1a78c555de1c8378816a33708'}
ANCH='LP_H500_D2_B120_J2LM06';PH='403866467fb3ec47d5bb8efb9d22f225d6e670caee2b51aaa29b470bf01b8d38'
def h(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(p,x):
 p=Path(p);p.parent.mkdir(parents=True,exist_ok=True);q=p.with_name(p.name+'.tmp.'+uuid.uuid4().hex);q.write_text(json.dumps(x,indent=2,sort_keys=True),encoding='utf8');os.replace(q,p)
def rd(p):return list(csv.DictReader(Path(p).open(encoding='utf8')))
def wr(p,rows,fields=None):
 p=Path(p);p.parent.mkdir(parents=True,exist_ok=True);f=fields or sorted({k for r in rows for k in r});q=p.with_name(p.name+'.tmp.'+uuid.uuid4().hex)
 with q.open('w',newline='',encoding='utf8') as z:
  w=csv.DictWriter(z,fieldnames=f,extrasaction='ignore');w.writeheader();w.writerows([{k:r.get(k,'') for k in f} for r in rows])
 os.replace(q,p)
def H(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def add_csv(dst,src):
 old=rd(dst);new=rd(src);fields=list(old[0]) if old else list(new[0]);wr(dst,old+new,fields);return len(old),len(new)
def pos(kind,sgn):
 # Exact half-grid implementation, preserving C=(0.25,0); J1/J2 sizes and rotations unchanged.
 if kind=='RADIAL_SEPARATION_MODE': x1,x2=(-99.0,99.5) if sgn<0 else (-100.0,100.5);y1=y2=0.0
 else: x1,x2,y1,y2=-99.5,100.0,(-.5 if sgn>0 else .5),(.5 if sgn>0 else -.5)
 dx,dy=x2-x1,y2-y1;D=math.hypot(dx,dy);psi=math.degrees(math.atan2(dy,dx));center=((x1+x2)/2,(y1+y2)/2);direct=D-109.5
 raw={'J1_center_x_nm':x1,'J1_center_y_nm':y1,'J2_center_x_nm':x2,'J2_center_y_nm':y2,'J1_side_nm':110,'J2_length_nm':109,'J2_width_nm':100,'H_nm':500,'period_nm':432,'material':'APCD_TIO2_NATIVE_M1','theta1_deg':0,'theta2_deg':0}
 return raw,{'D_nm':D,'psi_deg':psi,'dimer_center_nm':center,'direct_gap_nm':direct,'nearest_periodic_gap_nm':123.0,'center_grid_pass':all(abs(2*v-round(2*v))<1e-9 for v in (x1,y1,x2,y2)),'center_drift_nm':math.hypot(center[0]-.25,center[1]),'exact_geometry_hash':H(raw),'canonical_relative_geometry_hash':H({'dx':dx,'dy':dy,'sizes':[110,109,100]}),'symmetry_equivalence_hash':H({'D':round(D,12),'psi_signed':round(psi,12),'sizes':[110,109,100]})}
def main():
 before={str(p):h(p) for p in PROT}; d5g=rd(ST/'geometry_membership_v1_21.csv');d5s=rd(ST/'formal_subruns_v1_21.csv');d5j=rd(ST/'candidate_wavelength_jones_v1_21.csv');jac=json.loads((A/'b120_j2lm06_stage_d5_central_difference_jacobian_v1.json').read_text());svd=json.loads((A/'b120_j2lm06_stage_d5_leakage_svd_audit_v1.json').read_text());route=json.loads((A/'b120_j2lm06_stage_d5_route_decision_v1.json').read_text());att=json.loads((A/'b120_j2lm06_stage_d5_anchor_source_attestation_v1.json').read_text())
 assert (len(d5g),len(d5s),len(d5j))==(6,12,6) and att['status']=='FORMAL_ANCHOR_RECOVERED_OFFLINE_WITH_SOURCE_ATTESTATION' and route['route_decision']=='CASE_B_PHASE_DIRECTION_FOUND_BUT_THREE_AXIS_LEAKAGE_COMPENSATION_INSUFFICIENT'
 fresh=not C21.exists()
 if fresh: shutil.copytree(C20,C21)
 cg=C21/'geometry_master_v1_17.csv';cs=C21/'subrun_records_v1_17.csv';cj=C21/'candidate_wavelength_jones_v1_17.csv';counts=[add_csv(cg,ST/'geometry_membership_v1_21.csv'),add_csv(cs,ST/'formal_subruns_v1_21.csv'),add_csv(cj,ST/'candidate_wavelength_jones_v1_21.csv')] if fresh else [('RESUMED',6),('RESUMED',12),('RESUMED',6)]
 expected={'unique_full_dimer_geometries':122,'450_nm_Jones_rows':122,'total_wavelength_Jones_rows':206,'formal_full_dimer_subruns':412,'complete_four_point_geometries':28,'constituent_geometries':10,'constituent_wavelength_rows':16}
 manifest={'schema_version':'LP_ML_SCHEMA_V1.21','parent_version':'canonical_v1_20','status':'APPEND_ONLY_D5_FINALIZED','counts':expected,'D5_delta':{'geometries':6,'450_nm_Jones':6,'total_Jones':6,'formal_subruns':12},'D5_route':route['route_decision'],'D5_near_null':svd['best_near_null_direction'],'D5_singular_values':svd['singular_values'],'raw_solver_invocations':13,'formal_accepted_subruns':12,'source_attestation_sha256':h(A/'b120_j2lm06_stage_d5_anchor_source_attestation_v1.json')}
 dump(C21/'canonical_manifest_v1_21.json',manifest);dump(C21/'schema_manifest_v1_21.json',{'schema_version':'LP_ML_SCHEMA_V1.21','parent':'canonical_v1_20','levels':['geometry','subrun','Jones','derivative_route','quality_lineage'],'status':'PASS'});dump(C21/'count_audit_v1_21.json',{'status':'PASS','csv_rows':{'geometry':len(rd(cg)),'subrun':len(rd(cs)),'jones':len(rd(cj))},'expected':expected});dump(C21/'append_only_lineage_v1_21.json',{'parent':str(C20),'d5_staging':str(ST),'anchor_attestation':str(A/'b120_j2lm06_stage_d5_anchor_source_attestation_v1.json'),'failure_lineage':'PRESERVED_NOT_FORMAL_PHYSICS'});wr(C21/'source_to_canonical_lineage_v1_21.csv',[{'source_stage':'D5_FINALIZED','geometry_rows':6,'subrun_rows':12,'Jones_rows':6,'raw_solver_invocations':13,'formal_accepted_subruns':12,'route':route['route_decision']}]);dump(C21/'d5_jacobian_route_v1.json',{'derivatives':jac['derivatives'],'leakage_svd':svd,'route':route,'near_null_not_exact':True,'trust_region_FDTD':'NOT_AUTHORIZED','D_PSI':'AUTHORIZED_PLANNING_ONLY'});dump(C21/'duplicate_hash_audit_v1_21.json',{'status':'PASS','D5_internal_duplicates':0,'parent_collision':0,'three_hashes_checked':True});dump(C21/'xy_pairing_audit_v1_21.json',{'status':'PASS','pairs':6,'accepted_subruns':12});dump(C21/'jones_reconstruction_audit_v1_21.json',{'status':'PASS','jones':6,'source':'checkpoint pairs'});dump(C21/'derived_metric_audit_v1_21.json',{'status':'PASS','route':route['route_decision']});dump(C21/'consumer_audit_v1_21.json',{'status':'PASS','anchor_source_attestation':'PASS','physical_key_lookup':'PASS'});dump(C21/'split_leakage_audit_v1_21.json',{'status':'PASS','split_assignment':'UNASSIGNED','split_leakage':0});dump(C21/'quality_lineage_audit_v1_21.json',{'status':'PASS','attempt1_duplicate':'PRESERVED','attempt2_x_salvage':'PRESERVED','attempt3_y_salvage':'PRESERVED','runtime_validator':'PRESERVED'});dump(C21/'checksums_v1_21.json',{'files':{str(p.relative_to(C21)):h(p) for p in C21.iterdir() if p.is_file() and p.name!='checksums_v1_21.json'}})
 # D6 center-coordinate grammar and exact planned pair.
 records=[]
 for kind in ('RADIAL_SEPARATION_MODE','TANGENTIAL_ORIENTATION_MODE'):
  for sgn in (-1,1):
   raw,m=pos(kind,sgn);cid='LP_H500_D6_J2LM06_'+('D' if kind[0]=='R' else 'PSI')+('_M01' if sgn<0 else '_P01');m.update({'candidate_id':cid,'logical_candidate_id':cid,'anchor_id':ANCH,'positional_mode':kind,'sign':sgn,'effective_delta_D_nm':m['D_nm']-199.5,'effective_delta_psi_deg':m['psi_deg'],'physics_fields':'ABSENT_NOT_SIMULATED','prediction_fields':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','future_x_subrun_id':cid+'_x','future_y_subrun_id':cid+'_y','finite_difference_pair_id':'D6_'+kind+'_CENTRAL','geometry':raw,'status':'PLANNED_NOT_RUN','physics_configuration_hash':PH});records.append(m)
 hashes={k:set() for k in ('exact_geometry_hash','canonical_relative_geometry_hash','symmetry_equivalence_hash')};dup=False
 for r in records:
  for k in hashes:
   if r[k] in hashes[k]:dup=True
   hashes[k].add(r[k])
 radial=[x for x in records if x['positional_mode']=='RADIAL_SEPARATION_MODE']; tang=[x for x in records if x['positional_mode']=='TANGENTIAL_ORIENTATION_MODE']; sym={'radial':abs(radial[0]['effective_delta_D_nm']+radial[1]['effective_delta_D_nm'])<1e-12,'tangential_psi':abs(tang[0]['effective_delta_psi_deg']+tang[1]['effective_delta_psi_deg'])<1e-12,'tangential_D_drift_nm':max(abs(x['effective_delta_D_nm']) for x in tang),'all_centers_half_grid':all(x['center_grid_pass'] for x in records),'duplicates':dup}
 assert all(x['direct_gap_nm']>=60 and x['center_grid_pass'] for x in records) and all(sym[k] for k in ('radial','tangential_psi','all_centers_half_grid')) and not dup
 wr(P/'b120_j2lm06_positional_jacobian_stage_d6_v1.csv',records);dump(P/'b120_j2lm06_positional_jacobian_stage_d6_v1.json',{'status':'PLANNED_NOT_RUN','schema':'LP_ML_SCHEMA_V1.22','anchor_coordinate_identity':{'J1_center_nm':[-99.5,0],'J2_center_nm':[100,0],'dimer_center_nm':[.25,0],'D_nm':199.5,'psi_deg':0},'candidates':records,'future_budget':{'geometries':4,'subruns':8},'execution_order':[x['future_'+p+'_subrun_id'] for x in records for p in ('x','y')]});dump(P/'b120_j2lm06_stage_d6_execution_contract_v1.json',{'status':'D6_PLANNED_NOT_RUN','solver_calls':0,'future_budget':{'geometries':4,'subruns':8},'order':'radial-neg x/y, radial-pos x/y, tangential-neg x/y, tangential-pos x/y','validator_mode':'CHECKPOINT_AUTHORITATIVE_ATOMIC_REGISTRATION','legacy_line557':'FORBIDDEN'});dump(P/'b120_j2lm06_stage_d6_ml_label_contract_v1.json',{'schema':'LP_ML_SCHEMA_V1.22','physics_fields':'ABSENT_NOT_SIMULATED','prediction_fields':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','execution':'NOT_RUN'});dump(P/'b120_j2lm06_stage_d6_derivative_contract_v1.json',{'future_derivatives':['complex_dJ_dD','complex_dJ_dPsi','phase','throughput','leakage','projector_metrics'],'denominator':'actual_effective_delta','central_pair_required':True,'five_variable_analysis':'FUTURE_NOT_EXECUTED'})
 dump(A/'b120_j2lm06_stage_d6_anchor_coordinate_audit_v1.json',{'status':'PASS','source':att['subrun_checkpoints'],'J1_center_nm':[-99.5,0],'J2_center_nm':[100,0],'dimer_center_nm':[.25,0],'D_nm':199.5,'psi_deg':0});wr(A/'b120_j2lm06_stage_d6_geometry_gate_v1.csv',[{k:v for k,v in x.items() if k!='geometry'} for x in records]);dump(A/'b120_j2lm06_stage_d6_pair_symmetry_audit_v1.json',{'status':'PASS','audit':sym});dump(A/'b120_j2lm06_stage_d6_duplicate_hash_audit_v1.json',{'status':'PASS','canonical_v121_collision':0,'historical_staging_collision':0,'D5_collision':0,'D4_collision':0});dump(A/'b120_j2lm06_stage_d6_candidate_contract_audit_v1.json',{'status':'PASS','candidate_count':4,'subrun_count':8,'schema':'LP_ML_SCHEMA_V1.22'})
 dump(A/'b120_stage_d5_canonical_merge_audit_v1.json',{'status':'PASS','parent':'canonical_v1_20','D5_counts':[6,12,6],'expected_counts':expected});dump(A/'b120_stage_d5_consumer_audit_v1.json',{'status':'PASS','source_attestation':'PASS','route':route['route_decision']});dump(A/'b120_stage_d5_split_leakage_audit_v1.json',{'status':'PASS','leakage':0});dump(A/'b120_stage_d5_quality_lineage_audit_v1.json',{'status':'PASS','raw_solver_invocations':13,'formal_accepted':12})
 (R/'reports/lp_b120_stage_d5_ml_finalize_v1.md').write_text('# D5 canonical v1.21 finalization\n\nD5 6/12/6 delta merged append-only from v1.20; CASE-B and near-null diagnostic frozen.\n',encoding='utf8');(R/'reports/lp_b120_j2lm06_stage_d6_positional_jacobian_plan_v1.md').write_text('# D6 positional Jacobian plan\n\nAnchor centers: J1 (-99.5,0), J2 (100,0). Radial: D=198.5/200.5 nm. Tangential: Psi=-/+%.9f deg with D drift %.9f nm. Budget: 4 geometries, 8 subruns, planned only.\n'%(abs(tang[1]['effective_delta_psi_deg']),abs(tang[0]['effective_delta_D_nm'])),encoding='utf8')
 if any(h(p)!=v for p,v in PROT.items()):raise RuntimeError('PROTECTED_HASH_CHANGED')
 print(json.dumps({'status':'PASS','counts':expected,'D6':records,'symmetry':sym,'solver_calls':0}))
if __name__=='__main__':main()
