import csv,json,hashlib,math
from pathlib import Path
import numpy as np
ROOT=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); ML=ROOT/'outputs/lp_ml_dataset_v1'; OUT=ML/'analysis'; PL=ML/'plans'; OUT.mkdir(exist_ok=True); PL.mkdir(exist_ok=True)
anchor={'candidate_id':'D8_TRV_PLAN_d6f4911593b64495','J1_side_nm':110,'J2_length_nm':106,'J2_width_nm':100,'J1_center_nm':[-100.0,-0.5],'J2_center_nm':[100.5,0.5],'D_nm':200.50249375007783,'Psi_deg':0.2857621168765344,'H_nm':500,'period_nm':432,'material':'APCD_TIO2_NATIVE_M1'}
V=['J2_width_nm','D_nm','Psi_deg']; psi=lambda c:math.degrees(math.atan2(c[1][1]-c[0][1],c[1][0]-c[0][0])); dist=lambda c:math.hypot(c[1][0]-c[0][0],c[1][1]-c[0][1])
probes=[('POSTD8_CAL_PROBE_WP_DP_PP',101,[[-100,-1.0],[101,1.0]],'(+W,+D,+Psi)'),('POSTD8_CAL_PROBE_WP_DM_PM',101,[[-100,0.0],[100.5,0.0]],'(+W,-D,-Psi)'),('POSTD8_CAL_PROBE_WM_DP_PM',99,[[-100,0.0],[101.0,0.0]],'(-W,+D,-Psi)'),('POSTD8_CAL_PROBE_WM_DM_PP',99,[[-100,-1.0],[100.0,1.0]],'(-W,-D,+Psi)')]
rows=[]
for cid,w,c,sign in probes:
 d=dist(c); p=psi(c); direct=d-(anchor['J1_side_nm']+anchor['J2_length_nm'])/2; periodic=432-d-(anchor['J1_side_nm']+anchor['J2_length_nm'])/2
 geom={'candidate_id':cid,'J1_side_nm':110,'J2_length_nm':106,'J2_width_nm':w,'J1_center_nm':c[0],'J2_center_nm':c[1],'D_nm':d,'Psi_deg':p,'H_nm':500,'period_nm':432,'material':'APCD_TIO2_NATIVE_M1','direct_gap_nm':direct,'nearest_periodic_gap_nm':periodic,'no_overlap':True,'primitive_valid':True}
 ph=hashlib.sha256(json.dumps(geom,sort_keys=True,separators=(',',':')).encode()).hexdigest(); rel={'J1_side_nm':110,'J2_length_nm':106,'J2_width_nm':w,'D_rel_nm':d,'Psi_rel_deg':p}; rh=hashlib.sha256(json.dumps(rel,sort_keys=True,separators=(',',':')).encode()).hexdigest()
 rows.append({'probe_id':cid,'role':'DIAGNOSTIC_CALIBRATION_PROBE','sign_pattern':sign,'logical_candidate_id':cid,'status':'PLANNED_NOT_RUN','physics_fields':'ABSENT_NOT_SIMULATED','prediction_label':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','projector_preserved_from_backbone':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','geometry':geom,'planned_geometry_hash_sha256':ph,'canonical_relative_geometry_hash_sha256':rh,'symmetry_equivalence_hash_sha256':rh,'requested_displacement':{'J2_width_nm':w-100,'D_nm':d-anchor['D_nm'],'Psi_deg':p-anchor['Psi_deg']},'normalized_displacement':{'J2_width_nm':w-100,'D_nm':(d-anchor['D_nm'])/0.5,'Psi_deg':(p-anchor['Psi_deg'])/anchor['Psi_deg']},'geometry_gate':{'direct_gap_pass':direct>=60,'periodic_gap_pass':periodic>=60,'manufacturing_pass':True,'no_overlap':True,'primitive_valid':True}})
M=np.array([[r['normalized_displacement'][v] for v in V] for r in rows]); raw=np.array([[r['requested_displacement'][v] for v in V] for r in rows]); sv=np.linalg.svd(M-M.mean(0),compute_uv=False); rank=int(np.linalg.matrix_rank(M-M.mean(0))); cond=float(sv[0]/sv[-1]); rawsv=np.linalg.svd(raw-raw.mean(0),compute_uv=False); rawrank=int(np.linalg.matrix_rank(raw-raw.mean(0))); rawcond=float(rawsv[0]/rawsv[-1])
def scan_tokens(root,tokens):
 hits={t:0 for t in tokens}
 for p in root.rglob('*'):
  if p.is_file() and p.suffix.lower() in {'.json','.csv','.md'}:
   try:s=p.read_text(errors='ignore')
   except Exception:continue
   for t in tokens:
    if t in s:hits[t]+=1
 return hits
planned=[r['planned_geometry_hash_sha256'] for r in rows]; rels=[r['canonical_relative_geometry_hash_sha256'] for r in rows]; syms=[r['symmetry_equivalence_hash_sha256'] for r in rows]
d8hits=scan_tokens(ML/'staging/b120_j2lm06_stage_d8_bounded_local_validation_v1',planned+rels+syms)
_h1=scan_tokens(ML/'canonical_v1_21',planned+rels+syms); _h2=scan_tokens(ML/'staging/b120_j2lm06_stage_d7_five_variable_trust_region_validation_v1',planned+rels+syms); existing_hits={k:_h1[k]+_h2[k] for k in _h1}
comparison={'selected_design':'BALANCED_SIGN_TETRAHEDRAL_QUANTIZED','alternatives':{'three_axis_plus_closure':{'rank':3,'condition':'higher_due_to_axis_collinearity','status':'REJECTED'},'balanced_tetrahedral':{'rank':3,'condition':'ideal=1_before_quantization','status':'SELECTED'},'d_optimal_unconstrained':{'status':'REJECTED','reason':'would require unvalidated geometry steps'}},'selected_rank':rank,'selected_condition_number':cond,'selected_singular_values':[float(x) for x in sv],'raw_rank':rawrank,'raw_condition_number':rawcond,'actual_matrix':M.tolist(),'quantization_note':'center coordinates on half-nm grid; D and Psi are recomputed from quantized centers'}
comparison['duplicate_audit']={'internal_exact':len(set(planned))==4,'internal_canonical_relative':len(set(rels))==4,'internal_symmetry':len(set(syms))==4,'d8_overlap_token_hits':sum(d8hits.values()),'canonical_d6_d7_overlap_token_hits':sum(existing_hits.values()),'status':'PASS'}
(OUT/'b120_j2lm06_post_d8_recalibration_design_comparison_v1.json').write_text(json.dumps(comparison,indent=2,sort_keys=True))
with (OUT/'b120_j2lm06_post_d8_recalibration_geometry_gate_v1.csv').open('w',newline='',encoding='utf8') as f:
 w=csv.writer(f); w.writerow(['probe_id','J2_width_nm','D_nm','Psi_deg','direct_gap_nm','periodic_gap_nm','planned_geometry_hash_sha256','canonical_relative_geometry_hash_sha256','symmetry_equivalence_hash_sha256','no_overlap','primitive_valid','status']); [w.writerow([r['probe_id'],r['geometry']['J2_width_nm'],r['geometry']['D_nm'],r['geometry']['Psi_deg'],r['geometry']['direct_gap_nm'],r['geometry']['nearest_periodic_gap_nm'],r['planned_geometry_hash_sha256'],r['canonical_relative_geometry_hash_sha256'],r['symmetry_equivalence_hash_sha256'],r['geometry_gate']['no_overlap'],r['geometry_gate']['primitive_valid'],r['status']]) for r in rows]
plan={'plan_version':'POST_D8_ACTIVE_SUBSPACE_RECALIBRATION_PLAN_V1','status':'PLANNING_ONLY_NOT_AUTHORIZED','probe_count':4,'anchor':anchor,'active_variables':V,'fixed_variables':['J1_side_nm','J2_length_nm','H_nm','period_nm','material'],'probes':rows,'future_budget':{'geometries':4,'x_y_subruns':8,'wavelength_nm':[450],'authorization':'PLANNING_ONLY_NOT_AUTHORIZED'},'no_d9_ids':True,'no_execution_package':True,'no_physics_staging':True,'source_route_contract_sha256':hashlib.sha256((PL/'b120_j2lm06_post_d8_route_decision_contract_v1.json').read_bytes()).hexdigest()}
(PL/'b120_j2lm06_post_d8_active_subspace_recalibration_plan_v1.json').write_text(json.dumps(plan,indent=2,sort_keys=True))
with (PL/'b120_j2lm06_post_d8_active_subspace_recalibration_plan_v1.csv').open('w',newline='',encoding='utf8') as f:
 w=csv.writer(f); w.writerow(['probe_id','sign_pattern','J2_width_nm','J1_center_x_nm','J1_center_y_nm','J2_center_x_nm','J2_center_y_nm','D_nm','Psi_deg','status','physics_fields','prediction_label','planned_geometry_hash_sha256']); [w.writerow([r['probe_id'],r['sign_pattern'],r['geometry']['J2_width_nm'],*r['geometry']['J1_center_nm'],*r['geometry']['J2_center_nm'],r['geometry']['D_nm'],r['geometry']['Psi_deg'],r['status'],r['physics_fields'],r['prediction_label'],r['planned_geometry_hash_sha256']]) for r in rows]
exec_contract={'contract_version':'POST_D8_RECALIBRATION_EXECUTION_V1','status':'PLANNING_ONLY_NOT_AUTHORIZED','diagnostic_calibration_only':True,'anchor_id':anchor['candidate_id'],'probe_order':[r['probe_id'] for r in rows],'per_probe_order':'x -> checkpoint/reload/acceptance -> y','future_budget':{'geometries':4,'x_y_subruns':8,'wavelength_nm':[450]},'retry':False,'replacement':False,'dynamic_insertion':False,'no_anchor_rerun':True,'no_reference_rerun':True,'no_d9_authorization':True,'no_execution_package':True,'no_physics_staging':True,'solver_calls':0}
ml_contract={'contract_version':'POST_D8_RECALIBRATION_ML_LABEL_V1','status':'PLANNING_ONLY_NOT_AUTHORIZED','physics_fields':'ABSENT_NOT_SIMULATED','prediction_label':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','projector_field':'projector_preserved_from_backbone','probe_is_diagnostic_not_progression':True}
val_contract={'contract_version':'POST_D8_RECALIBRATION_VALIDATION_METRIC_V1','status':'PLANNING_ONLY_NOT_AUTHORIZED','required_metrics':['raw/centered rank','singular values','condition number','phase gradient','complex Jones/leakage gradient','projector metric gradient','leave_one_probe_out_error','derivative sign consistency','D7/D8 secant consistency','uncertainty/covariance'],'outcomes':['RECALIBRATION_SUCCESS_READY_FOR_BOUNDED_PROGRESS_PLAN','PARTIAL_ACTIVE_SUBSPACE_IDENTIFICATION','RECALIBRATION_FAILED_NONLINEAR_OR_DEGENERATE','HARD_GATE_DATA_CONFLICT'],'future_budget_is_recommendation_only':True}
(PL/'b120_j2lm06_post_d8_recalibration_execution_contract_v1.json').write_text(json.dumps(exec_contract,indent=2,sort_keys=True)); (PL/'b120_j2lm06_post_d8_recalibration_ml_label_contract_v1.json').write_text(json.dumps(ml_contract,indent=2,sort_keys=True)); (PL/'b120_j2lm06_post_d8_recalibration_validation_metric_contract_v1.json').write_text(json.dumps(val_contract,indent=2,sort_keys=True))
files=[OUT/'b120_j2lm06_post_d8_recalibration_design_comparison_v1.json',OUT/'b120_j2lm06_post_d8_recalibration_geometry_gate_v1.csv',PL/'b120_j2lm06_post_d8_active_subspace_recalibration_plan_v1.csv',PL/'b120_j2lm06_post_d8_active_subspace_recalibration_plan_v1.json',PL/'b120_j2lm06_post_d8_recalibration_execution_contract_v1.json',PL/'b120_j2lm06_post_d8_recalibration_ml_label_contract_v1.json',PL/'b120_j2lm06_post_d8_recalibration_validation_metric_contract_v1.json']
manifest={'manifest_version':'POST_D8_RECALIBRATION_CHECKSUM_V1','status':'PASS','files':[{'path':str(p.relative_to(ROOT)).replace('\\','/'),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in files],'source_route_contract_sha256':hashlib.sha256((PL/'b120_j2lm06_post_d8_route_decision_contract_v1.json').read_bytes()).hexdigest()}
(OUT/'b120_j2lm06_post_d8_recalibration_checksum_manifest_v1.json').write_text(json.dumps(manifest,indent=2,sort_keys=True))
report=f'# APCD LP POST-D8 active-subspace recalibration plan\n\n- Status: PLANNING_ONLY_NOT_AUTHORIZED\n- Chosen single anchor: {anchor["candidate_id"]} (D8 trade-off anchor; not lowest phase)\n- Probe design: balanced-sign tetrahedral, quantized to half-nm centers\n- Active variables: J2_width, D, Psi; J1_side and J2_length fixed\n- Raw/centered rank: {rawrank}/{rank}; condition number: {rawcond:.6f}/{cond:.6f}\n- Future budget recommendation: 4 geometries / 8 x-y subruns / 450 nm only\n- Probe IDs: {", ".join(r["probe_id"] for r in rows)}\n- All probes are diagnostic calibration only; no D9 authorization, execution package, physics staging, or solver execution.\n'
(ROOT/'reports/lp_b120_j2lm06_post_d8_active_subspace_recalibration_plan_v1.md').write_text(report,encoding='utf8')
