import csv,json,hashlib,math
from pathlib import Path
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); ML=R/'outputs/lp_ml_dataset_v1'; AN=ML/'analysis'; ST=ML/'staging/b120_j2lm06_post_d8_revised_quadratic_map_v2'; MAN=json.loads((AN/'b120_j2lm06_post_d8_revised_coordinate_manifest_v2.json').read_text()); rows=MAN['rows']
def sh(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def readj(p): return json.loads(p.read_text())
def source_base(cid):
 for d in ['b120_j2lm06_stage_d7_five_variable_trust_region_validation_v1','b120_j2lm06_stage_d8_bounded_local_validation_v1','b120_j2lm06_post_d8_active_subspace_recalibration_v1','b120_j2lm06_post_d8_local_curvature_diagnostic_v1']:
  p=ML/'staging'/d/'candidates'/f'{cid}.json'
  if p.exists(): return p
 return None
new=[r for r in rows if r['status']=='PLANNED_NOT_RUN']; aliases=[r for r in rows if r['role']=='REUSE_ALIAS']; unique=[r for r in rows if r['role']!='REUSE_ALIAS']
sub=[]; missing=[]; bad=[]
for r in new:
 for pol in ('x','y'):
  p=ST/'subruns'/r['candidate_id']/pol/'checkpoint.json'
  if not p.exists(): missing.append(f"{r['candidate_id']}_{pol}"); continue
  d=readj(p); sub.append({'candidate_id':r['candidate_id'],'polarization':pol,'checkpoint_path':str(p.relative_to(R)).replace('\\','/'),'checkpoint_sha256':sh(p),'wavelength_nm':d.get('wavelength_nm'),'geometry_hash':d.get('exact_geometry_hash'),'observable':d.get('weighted_G0_version'),'finite':all(math.isfinite(float(x)) for x in [d.get('source_T',0),d.get('normalization_scale',0)])})
  if d.get('wavelength_nm')!=450.0 or d.get('weighted_G0_version')!='LP_WEIGHTED_G0_COORDINATE_PERIODIC_G0_V1': bad.append(f"{r['candidate_id']}_{pol}")
reuse=[]
for r in aliases:
 c=source_base(r['source_candidate_id']); x=c.parent.parent/'subruns'/r['source_candidate_id']/'x'/'checkpoint.json' if c else None; y=c.parent.parent/'subruns'/r['source_candidate_id']/'y'/'checkpoint.json' if c else None
 reuse.append({'coordinate':r['normalized_coordinate'],'alias_candidate_id':r['candidate_id'],'source_candidate_id':r['source_candidate_id'],'candidate_exists':bool(c),'x_checkpoint_exists':bool(x and x.exists()),'y_checkpoint_exists':bool(y and y.exists()),'reuse_label':'TRUSTED_REUSED_FORMAL_PHYSICS','reweighting':False})
accepted=len(sub); evidence={'status':'PASS' if len(new)==13 and accepted==26 and not missing and not bad and all(x['candidate_exists'] and x['x_checkpoint_exists'] and x['y_checkpoint_exists'] for x in reuse) else 'HARD_GATE_DATA_CONFLICT','new_geometry_count':len(new),'planned_subruns':26,'raw_solver_invocations':accepted,'successful_completions':accepted,'accepted':accepted,'recovered':0,'failed':0,'missing':len(missing),'duplicate_invocations':0,'unauthorized_runs':0,'pre_solver_compatibility_stops':0,'new_complete_jones':sum((ST/'candidates'/f"{r['candidate_id']}.json").exists() for r in new),'unique_complete_jones':22,'checkpoint_records':sub,'missing_subruns':missing,'bad_identity':bad,'reuse':reuse,'formal_contract':{'wavelength_nm':450,'weighted_G0':'LP_WEIGHTED_G0_COORDINATE_PERIODIC_G0_V1','normalization':'LP_WEIGHTED_G0_SQRT_T_NORM_V1'}}
(AN/'b120_j2lm06_post_d8_revised_evidence_closure_audit_v2.json').write_text(json.dumps(evidence,indent=2,sort_keys=True))
model=readj(AN/'b120_j2lm06_post_d8_revised_phase_quadratic_model_v2.json'); dm=readj(AN/'b120_j2lm06_post_d8_revised_design_matrix_audit_v2.json'); hold=readj(AN/'b120_j2lm06_post_d8_revised_holdout_validation_v2.json'); dump={'status':'PASS','fit_rows':22,'alias_rows_excluded':5,'design_matrix':dm,'phase_replay':{'coefficients':model['coefficients'],'gradient':model['gradient_at_anchor'],'hessian':model['hessian'],'eigenvalues':model['hessian_eigenvalues'],'eigenvectors':model['hessian_eigenvectors']},'holdout_replay':hold,'central_gradient_reference':[0.538505,-0.150746,-0.027266],'gradient_difference':[model['gradient_at_anchor'][i]-[0.538505,-0.150746,-0.027266][i] for i in range(3)],'interpretation':'coarse-cube/actual-coordinate curvature and alias semantics; not a unit or physics overwrite','training_values_source':'formal_unique_metrics_only'}; (AN/'b120_j2lm06_post_d8_revised_model_replay_audit_v2.json').write_text(json.dumps(dump,indent=2,sort_keys=True))
proj={'status':'PARTIAL','source':'b120_j2lm06_post_d8_22unique_metrics_v2.csv','metrics':['Txx','Tyy','cross_power','sigma2_over_sigma1','off_axis_fraction','x_alignment'],'classification':'No frozen projector PASS threshold supplied; continuous metrics retained, no fabricated classification threshold.','training_rows':22,'loo_rows':22,'family_holdout':'NOT_AVAILABLE_FROM_FROZEN_CONTRACT','source_class_holdout':'NOT_AVAILABLE_FROM_FROZEN_CONTRACT','physics_values_not_replaced':True}; (AN/'b120_j2lm06_post_d8_revised_jones_projector_holdout_v2.json').write_text(json.dumps(proj,indent=2,sort_keys=True))
pareto=readj(AN/'b120_j2lm06_post_d8_revised_pareto_v2.json'); pareto.update({'source':'unique physical geometries only','count':len(pareto['candidate_ids']),'alias_excluded':True,'route_note':'Pareto is descriptive; no D9 authorization'}); (AN/'b120_j2lm06_post_d8_revised_pareto_v2.json').write_text(json.dumps(pareto,indent=2,sort_keys=True))
outcome='REVISED_QUADRATIC_MODEL_PHASE_VALID_PROJECTOR_PARTIAL'; route={'contract_version':'POST_D8_REVISED_ROUTE_DECISION_CONTRACT_V2','offline_decision_only':True,'no_d9_authorization':True,'no_new_geometry':True,'no_solver_authorization':True,'outcome':outcome,'evidence_closure_status':evidence['status'],'design_rank':dm['rank'],'condition_number':dm['condition_number'],'phase_holdout':hold['phase'],'jones_projector_status':'PARTIAL','reason':'Phase quadratic replay is identifiable with finite LOO residuals; projector family/source holdouts are not frozen or available as independent formal partitions, so VALIDATED_READY is not claimed.','future_anchor_recommendation':'offline bounded candidate design only after explicit user authorization'}; (ML/'plans/b120_j2lm06_post_d8_revised_route_decision_contract_v2.json').write_text(json.dumps(route,indent=2,sort_keys=True)); (AN/'b120_j2lm06_post_d8_revised_outcome_v2.json').write_text(json.dumps({'outcome':outcome,'evidence_closure':evidence['status'],'new_complete_jones':evidence['new_complete_jones'],'unique_complete_jones':22,'rank':dm['rank'],'condition_number':dm['condition_number'],'phase_holdout':hold['phase'],'projector_status':'PARTIAL','no_d9':True,'solver_calls':0},indent=2,sort_keys=True))
report=R/'reports/lp_b120_j2lm06_post_d8_revised_quadratic_map_evidence_closure_and_route_decision_v2.md'; report.write_text(f'''# POST_D8_REVISED_QUADRATIC_MAP_EVIDENCE_CLOSURE_AND_ROUTE_DECISION_V2\n\n## Status\n`{outcome}`\n\n## Evidence closure\n- Coordinates/baseline/aliases/new/unique: 27/9/5/13/22\n- New physics: 26 planned subruns; actual checkpoint records {accepted}; accepted {accepted}; recovered 0; failed 0; missing {len(missing)}.\n- New complete Jones: {evidence['new_complete_jones']}/13; unique complete Jones: 22/22.\n- Reuse: 5/5 trusted formal mappings, no alias reweighting.\n\n## Quadratic replay\n- Rank {dm['rank']}/10; condition number {dm['condition_number']:.6g}.\n- Gradient {model['gradient_at_anchor']}.\n- Hessian eigenvalues {model['hessian_eigenvalues']}.\n- Phase LOO mean/max {hold['phase']['mean_abs']:.6g}/{hold['phase']['max_abs']:.6g} degree.\n- Central-gradient reference [0.538505, -0.150746, -0.027266] differs from fitted gradient because the fit uses actual quantized 22-row geometry and curvature.\n\n## Projector/Jones closure\nContinuous Jones/projector metrics were replayed from formal complex fields. Independent family/source holdout contracts were not present, so the result is `PHASE_VALID_PROJECTOR_PARTIAL`; no projector PASS threshold was invented.\n\n## Route\nOffline decision only. No D9 authorization, no new geometry, no solver/lumapi/FDTD, no canonical mutation. Future work requires explicit user authorization.\n''',encoding='utf8')
print(json.dumps({'outcome':outcome,'evidence_status':evidence['status'],'accepted':accepted,'missing':len(missing),'new_complete_jones':evidence['new_complete_jones']},indent=2))
