import csv,json,hashlib,math
from pathlib import Path
import numpy as np
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); M=R/'outputs/lp_ml_dataset_v1'; A=M/'analysis'; P=M/'plans'
U=[(0,2,-1),(0,1,-2),(2,0,1),(2,0,0),(0,2,0),(2,1,1)]
ROLES=['PHASE_ROBUST_DESCENT','PHASE_NEGATIVE_CURVATURE_PROBE','PROJECTOR_SAFE_PROGRESS','TRADEOFF_ROBUST_PROGRESS','MODEL_DISAGREEMENT_DIAGNOSTIC','PHASE_PROJECTOR_DECOUPLING_DIAGNOSTIC']
PARENTS=['POSTD8_QMAP_W0_DP_PM','POSTD8_QMAP_W0_DP_PM','POSTD8_QMAP_WP_D0_PP','POSTD8_QMAP_WP_D0_PP','POSTD8_QMAP_W0_DP_PM','POSTD8_QMAP_WP_D0_PP']
def hh(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def cid(i): return 'POSTD8_BOUNDED_'+('PHASE' if i<2 else 'PROJECTOR' if i<4 else 'DIAG')+f'_{i+1:02d}'
def geom(u):
 w,d,p=u; j1=[-100.,-.5]; j2=[100.5+.5*d,.5+p]; dx=j2[0]-j1[0]; dy=j2[1]-j1[1]; D=math.hypot(dx,dy); psi=math.degrees(math.atan2(dy,dx)); g={'J1_side_nm':110.,'J2_length_nm':106.,'J2_width_nm':100.+w,'J1_center_nm':j1,'J2_center_nm':j2,'D_nm':D,'Psi_deg':psi,'H_nm':500.,'period_nm':432.,'material':'APCD_TIO2_NATIVE_M1','direct_gap_nm':D-108.,'nearest_periodic_gap_nm':432.-D-108.,'center_grid':'INTEGER_OR_EXACT_HALF_NM','no_overlap':D>=108.,'primitive_valid':True}; g['exact_geometry_hash_sha256']=hh(g); rel={'J1_side_nm':110.,'J2_length_nm':106.,'J2_width_nm':100.+w,'D_rel_nm':D,'Psi_rel_deg':psi}; g['canonical_relative_geometry_hash_sha256']=hh(rel); g['symmetry_equivalence_hash_sha256']=g['canonical_relative_geometry_hash_sha256']; return g
metrics=list(csv.DictReader((A/'b120_j2lm06_post_d8_22unique_metrics_v2.csv').open())); coords={r['candidate_id']:r for r in json.loads((A/'b120_j2lm06_post_d8_revised_coordinate_manifest_v2.json').read_text())['rows']}
for r in metrics:
 r.update({k:coords[r['candidate_id']][k] for k in ['uW','uD','uPsi']})
phase=json.loads((A/'b120_j2lm06_post_d8_revised_phase_quadratic_model_v2.json').read_text()); pc=np.array(phase['coefficients']); grad=np.array([.538505,-.150746,-.027266]); target=71.445607
def B(u): return np.array([1,u[0],u[1],u[2],u[0]**2,u[1]**2,u[2]**2,u[0]*u[1],u[0]*u[2],u[1]*u[2]],float)
def nearest(u): return min(metrics,key=lambda r:sum((float(r[k])-u[i])**2 for i,k in enumerate(['uW','uD','uPsi'])))
def pq(u): return float(B(u)@pc)
def pcen(u,parent):
 r=next((x for x in metrics if x['candidate_id']==parent),nearest(u)); base=np.array([float(r['uW']),float(r['uD']),float(r['uPsi'])]); return float(r['phase_deg'])+float(np.dot(grad,np.array(u)-base))
items=[]
for i,(u,role,parent) in enumerate(zip(U,ROLES,PARENTS)):
 g=geom(u); n=nearest(u); q=pq(u); c=pcen(u,parent); s=float(n['phase_deg']); spread=max(q,c,s)-min(q,c,s); pm={k:float(n[k]) for k in ['Txx','Tyy','cross_power','sigma2_over_sigma1','off_axis_fraction','x_alignment']}; guard='PROJECTOR_GUARD_STRONG' if pm['x_alignment']>=.999 and pm['off_axis_fraction']<1e-5 else 'PROJECTOR_GUARD_MODERATE' if pm['x_alignment']>=.999 else 'PROJECTOR_DIAGNOSTIC_ONLY'; pred={'phase_quadratic_deg':q,'phase_central_gradient_deg':c,'phase_secant_deg':s,'phase_ensemble_median_deg':float(np.median([q,c,s])),'phase_prediction_spread_deg':spread,'distance_to_B120_target_deg':abs(float(np.median([q,c,s]))-target),'nearest_observed_candidate':n['candidate_id'],'model_agreement_sign':(q-s)*(c-s)>=0,'distance_from_training_hull_L1':max(0,abs(u[0])-1)+max(0,abs(u[1])-1)+max(0,abs(u[2])-1),'extrapolation_score':max(abs(x) for x in u)-1,'negative_curvature_contribution_deg':float(pc[4]*u[0]**2+pc[5]*u[1]**2+pc[6]*u[2]**2+pc[7]*u[0]*u[1]+pc[8]*u[0]*u[2]+pc[9]*u[1]*u[2]),'predicted_linear_term_deg':float(pc[1]*u[0]+pc[2]*u[1]+pc[3]*u[2]),'predicted_quadratic_term_deg':q-float(pc[0]+pc[1]*u[0]+pc[2]*u[1]+pc[3]*u[2])}; pred.update(pm); items.append({'execution_order':i+1,'candidate_id':cid(i),'role':role,'parent_anchor_id':parent,'normalized_coordinate':list(u),'geometry':g,'source_model_identities':{'phase_model':'b120_j2lm06_post_d8_revised_phase_quadratic_model_v2','secant_source_candidate':n['candidate_id']},'predicted_metrics':pred,'empirical_projector_guard':guard,'physics_label':'ABSENT_NOT_SIMULATED','prediction_label':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','status':'PLANNED_NOT_RUN','manufacturing_margin_nm':min(g['direct_gap_nm'],g['nearest_periodic_gap_nm'])-60,'duplicate_check':'PASS'})
assert len(items)==6 and len({x['geometry']['exact_geometry_hash_sha256'] for x in items})==6 and all(x['predicted_metrics']['model_agreement_sign'] for x in items)
def dump(path,obj): path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(obj,indent=2,sort_keys=True,default=float))
fs=['execution_order','candidate_id','role','parent_anchor_id','normalized_coordinate','phase_quadratic_deg','phase_central_gradient_deg','phase_secant_deg','phase_prediction_spread_deg','distance_to_B120_target_deg','Txx','Tyy','cross_power','sigma2_over_sigma1','off_axis_fraction','x_alignment','empirical_projector_guard','physics_label','prediction_label','status'];
with (A/'b120_j2lm06_post_d8_bounded_outer_shell_candidate_pool_v1.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=fs); w.writeheader(); [w.writerow({k:(x['predicted_metrics'].get(k) if k in x['predicted_metrics'] else x.get(k)) for k in fs}) for x in items]
with (A/'b120_j2lm06_post_d8_bounded_candidate_geometry_gate_v1.csv').open('w',newline='') as f:
 fs2=['candidate_id','exact_hash','canonical_hash','symmetry_hash','direct_gap_nm','periodic_gap_nm','no_overlap','primitive_valid','duplicate_free','manufacturing_pass']; w=csv.DictWriter(f,fieldnames=fs2); w.writeheader(); [w.writerow({'candidate_id':x['candidate_id'],'exact_hash':x['geometry']['exact_geometry_hash_sha256'],'canonical_hash':x['geometry']['canonical_relative_geometry_hash_sha256'],'symmetry_hash':x['geometry']['symmetry_equivalence_hash_sha256'],'direct_gap_nm':x['geometry']['direct_gap_nm'],'periodic_gap_nm':x['geometry']['nearest_periodic_gap_nm'],'no_overlap':x['geometry']['no_overlap'],'primitive_valid':x['geometry']['primitive_valid'],'duplicate_free':True,'manufacturing_pass':x['manufacturing_margin_nm']>=0}) for x in items]
dump(A/'b120_j2lm06_post_d8_bounded_predicted_pareto_v1.json',{'status':'PASS','candidate_count':6,'candidate_ids':[x['candidate_id'] for x in items],'items':items,'physics_not_claimed':True})
dump(A/'b120_j2lm06_post_d8_bounded_model_ensemble_audit_v1.json',{'status':'PASS','models':['revised_quadratic','central_gradient','nearest_secant'],'candidate_count':6,'phase_model_agreement_all':True,'negative_eigenvalues':phase['hessian_eigenvalues'],'no_new_physics':True})
dump(A/'b120_j2lm06_post_d8_bounded_projector_empirical_guard_v1.json',{'status':'PASS','method':'nearest formal unique geometry empirical guard','candidate_guards':{x['candidate_id']:x['empirical_projector_guard'] for x in items},'threshold_invented':False,'model_partial_acknowledged':True})
plan={'plan_version':'POST_D8_DUAL_ANCHOR_BOUNDED_CANDIDATE_PLAN_V1','status':'PLANNING_ONLY_NOT_AUTHORIZED','outcome':'BOUNDED_DUAL_ANCHOR_PLAN_READY','future_budget':{'geometries':6,'x_y_subruns':12,'wavelength_nm':[450]},'branch_counts':{'phase':2,'projector':2,'diagnostic':2},'candidates':items,'no_execution_package':True,'no_physics_staging':True,'no_d9':True,'solver_calls':0}; dump(P/'b120_j2lm06_post_d8_dual_anchor_bounded_candidate_plan_v1.json',plan)
dump(P/'b120_j2lm06_post_d8_bounded_execution_contract_v1.json',{'contract_version':'POST_D8_BOUNDED_EXECUTION_CONTRACT_V1','status':'PLANNING_ONLY_NOT_AUTHORIZED','future_budget':{'geometries':6,'subruns':12,'wavelength_nm':[450]},'physics_label':'ABSENT_NOT_SIMULATED','no_solver_authorization':True,'no_execution_package':True,'no_staging':True,'no_d9':True})
dump(P/'b120_j2lm06_post_d8_bounded_validation_metric_contract_v1.json',{'contract_version':'POST_D8_BOUNDED_VALIDATION_METRIC_CONTRACT_V1','metrics':['phase','Jones','Txx','Tyy','leakage','sigma2_over_sigma1','projection_error'],'status':'PLANNING_ONLY_NOT_AUTHORIZED'})
dump(P/'b120_j2lm06_post_d8_bounded_ml_label_contract_v1.json',{'contract_version':'POST_D8_BOUNDED_ML_LABEL_CONTRACT_V1','prediction_physics_separation':True,'physics_fields':'ABSENT_NOT_SIMULATED','prediction_fields':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','split_group':'canonical_relative_geometry_hash_sha256','status':'PLANNING_ONLY_NOT_AUTHORIZED'})
files=list(A.glob('b120_j2lm06_post_d8_bounded_*'))+list(P.glob('b120_j2lm06_post_d8_bounded_*'))+[P/'b120_j2lm06_post_d8_dual_anchor_bounded_candidate_plan_v1.json']; dump(A/'b120_j2lm06_post_d8_bounded_checksum_manifest_v1.json',{'status':'PASS','files':{str(p.relative_to(R)).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}})
(R/'reports/lp_b120_j2lm06_post_d8_dual_anchor_bounded_candidate_plan_v1.md').write_text('# POST-D8 dual-anchor bounded candidate plan v1\n\nStatus: `BOUNDED_DUAL_ANCHOR_PLAN_READY` / `PLANNING_ONLY_NOT_AUTHORIZED`.\n\nSix one-step outer-shell candidates are frozen: 2 phase, 2 projector, 2 diagnostic. Future budget: 6 geometries / 12 x-y subruns / 450 nm. All future physics fields remain absent until explicit authorization. No execution package, physics staging, D9, or solver was created.\n\nComplete candidate table: `outputs/lp_ml_dataset_v1/analysis/b120_j2lm06_post_d8_bounded_outer_shell_candidate_pool_v1.csv`.\n')
print(json.dumps({'outcome':'BOUNDED_DUAL_ANCHOR_PLAN_READY','candidate_count':6,'solver_calls':0},indent=2))
