import hashlib,json
from pathlib import Path
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); ML=R/'outputs/lp_ml_dataset_v1'; AN=ML/'analysis'; PL=ML/'plans'; PK=ML/'execution_packages/b120_j2lm06_post_d8_revised_quadratic_map_execution_package_v2'; ST=ML/'staging/b120_j2lm06_post_d8_revised_quadratic_map_v2'
def sh(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return str(p.relative_to(R)).replace('\\','/')
paths=[PL/'b120_j2lm06_post_d8_revised_quadratic_map_contract_v2.json',AN/'b120_j2lm06_post_d8_reuse_mapping_audit_v2.json',AN/'b120_j2lm06_post_d8_revised_coordinate_manifest_v2.json',AN/'b120_j2lm06_post_d8_revised_unique_geometry_gate_v2.csv',AN/'b120_j2lm06_post_d8_27coordinate_metrics_v2.csv',AN/'b120_j2lm06_post_d8_22unique_metrics_v2.csv',AN/'b120_j2lm06_post_d8_revised_design_matrix_audit_v2.json',AN/'b120_j2lm06_post_d8_revised_phase_quadratic_model_v2.json',AN/'b120_j2lm06_post_d8_revised_jones_quadratic_model_v2.json',AN/'b120_j2lm06_post_d8_revised_projector_quadratic_model_v2.json',AN/'b120_j2lm06_post_d8_revised_holdout_validation_v2.json',AN/'b120_j2lm06_post_d8_revised_pareto_v2.json',AN/'b120_j2lm06_post_d8_revised_solver_accounting_v2.json',AN/'b120_j2lm06_post_d8_revised_outcome_v2.json',AN/'b120_j2lm06_post_d8_revised_v1_v2_supersession_v1.json']
links={rel(p):sh(p) for p in paths if p.exists()}; (AN/'b120_j2lm06_post_d8_revised_artifact_checksums_v2.json').write_text(json.dumps({'status':'PASS','files':links,'sha256_complete':True},indent=2,sort_keys=True))
contract=json.loads(paths[0].read_text()); contract.update({'artifact_checksums_path':rel(AN/'b120_j2lm06_post_d8_revised_artifact_checksums_v2.json'),'artifact_checksums_sha256':sh(AN/'b120_j2lm06_post_d8_revised_artifact_checksums_v2.json'),'source_v1_manifest_sha256':sh(AN/'b120_j2lm06_post_d8_27point_cube_manifest_v1.json'),'source_v1_gate_sha256':sh(AN/'b120_j2lm06_post_d8_3level_grid_geometry_gate_v1.csv'),'protected_v1_preserved':True,'v1_v2_supersession_path':rel(AN/'b120_j2lm06_post_d8_revised_v1_v2_supersession_v1.json'),'v1_v2_supersession_sha256':sh(AN/'b120_j2lm06_post_d8_revised_v1_v2_supersession_v1.json')}); paths[0].write_text(json.dumps(contract,indent=2,sort_keys=True))
(PK/'package_manifest.json').write_text(json.dumps({'status':'READY_FOR_EXECUTION_COMPLETE','package_version':'POST_D8_REVISED_QUADRATIC_MAP_EXECUTION_PACKAGE_V2','new_geometries':13,'new_subruns':26,'phase_a':4,'phase_b':9,'plan_contract_sha256':sh(paths[0]),'manifest_sha256':sh(AN/'b120_j2lm06_post_d8_revised_coordinate_manifest_v2.json'),'solver_calls':26,'no_d9':True},indent=2,sort_keys=True))
(R/'reports/lp_b120_j2lm06_post_d8_revised_quantized_quadratic_response_map_v2.md').write_text((R/'reports/lp_b120_j2lm06_post_d8_revised_quantized_quadratic_response_map_v2.md').read_text()+'\n\nArtifact checksum manifest: `'+rel(AN/'b120_j2lm06_post_d8_revised_artifact_checksums_v2.json')+'`\nAll listed v2 artifacts are SHA256-bound; v1 hard-gate evidence remains preserved and superseded only by explicit revised contract.\n')
print(json.dumps({'status':'PASS','artifact_count':len(links),'checksums':sh(AN/'b120_j2lm06_post_d8_revised_artifact_checksums_v2.json')},indent=2))
