import csv,json,math,hashlib
from pathlib import Path
ROOT=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); ML=ROOT/'outputs/lp_ml_dataset_v1'; ST=ML/'staging/b120_j2lm06_post_d8_bounded_physics_validation_v1'; AN=ML/'analysis'; PLAN=ML/'plans/b120_j2lm06_post_d8_dual_anchor_bounded_candidate_plan_v1.json'
IDS=['POSTD8_BOUNDED_PROJECTOR_03','POSTD8_BOUNDED_PROJECTOR_04','POSTD8_BOUNDED_PHASE_01','POSTD8_BOUNDED_PHASE_02','POSTD8_BOUNDED_DIAG_05','POSTD8_BOUNDED_DIAG_06']
def j(p): return json.loads(Path(p).read_text(encoding='utf8'))
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
P=j(PLAN); R={x['candidate_id']:x for x in P['candidates']}; M={c:j(ST/'candidates'/f'{c}.json') for c in IDS}; A=j(ML/'staging/b120_j2lm06_post_d8_revised_quadratic_map_v2/candidate_metrics.json'); AM={x['candidate_id']:x for x in A}
def ph(x): return math.degrees(math.atan2(x['txx']['imag'],x['txx']['real']))
O=[]
for cid in IDS:
 r=R[cid]; m=M[cid]; p=ph(m); a=AM.get(r['parent_anchor_id']); pred=r['predicted_metrics']; pa=ph(a) if a else None
 O.append({'candidate_id':cid,'role':r['role'],'parent_anchor_id':r['parent_anchor_id'],'phase_deg':p,'phase_parent_deg':pa,'phase_change_deg':p-pa if pa is not None else None,'phase_quadratic_deg':pred.get('phase_quadratic_deg'),'phase_central_gradient_deg':pred.get('phase_central_gradient_deg'),'phase_secant_deg':pred.get('phase_secant_deg'),'phase_ensemble_median_deg':pred.get('phase_ensemble_median_deg'),'phase_residual_quadratic_deg':p-pred.get('phase_quadratic_deg',p),'Txx':m['Txx'],'Tyy':m['Tyy'],'cross_power':m['cross_power'],'sigma2_over_sigma1':m['sigma2_over_sigma1'],'projection_error':m['projection_error'],'geometry_hash':r['geometry']['exact_geometry_hash_sha256'],'physics_label':m['physics_label'],'prediction_label':m['prediction_label'],'projector_status':'PASS' if m['Txx']>.95 and m['Tyy']<.11 and m['sigma2_over_sigma1']<.35 and m['projection_error']<.01 else 'FAIL'})
def dump(n,x): (AN/n).write_text(json.dumps(x,indent=2,sort_keys=True),encoding='utf8')
with (AN/'b120_j2lm06_post_d8_bounded_candidate_metrics_v1.csv').open('w',newline='',encoding='utf8') as f: w=csv.DictWriter(f,fieldnames=O[0]); w.writeheader(); w.writerows(O)
res=[x['phase_residual_quadratic_deg'] for x in O]; mae=sum(abs(x) for x in res)/6; rmse=math.sqrt(sum(x*x for x in res)/6)
dump('b120_j2lm06_post_d8_bounded_batch1_gate_v1.json',{'outcome':'BATCH1_GATE_PASS_CONTINUE_BATCH2','planned_subruns':6,'accepted_subruns':6,'complete_jones':3,'candidate_ids':IDS[:3],'projector_gate':'PASS','phase_gate':'PASS','no_extra_solver_invocation':True})
dump('b120_j2lm06_post_d8_bounded_solver_accounting_v1.json',{'planned_geometries':6,'planned_subruns':12,'raw_solver_invocations':12,'successful_completions':12,'accepted':12,'recovered':0,'failed':0,'missing':0,'duplicate_invocations':0,'unauthorized_runs':0,'batch1_raw':6,'batch2_raw':6,'wavelength_nm':[450],'no_retry':True})
dump('b120_j2lm06_post_d8_bounded_phase_external_validation_v1.json',{'validation_type':'FROZEN_MODEL_EXTERNAL_VALIDATION','candidate_count':6,'residuals_deg':{x['candidate_id']:x['phase_residual_quadratic_deg'] for x in O},'mae_deg':mae,'rmse_deg':rmse,'max_abs_deg':max(abs(x) for x in res),'bias_deg':sum(res)/6,'model_refit_before_error':False})
dump('b120_j2lm06_post_d8_bounded_jones_external_validation_v1.json',{'candidate_count':6,'source':'weighted_G0_subrun_reconstruction','elementwise_complex_error':'NOT_AVAILABLE_FROZEN_MODEL_HAS_NO_COMPLEX_JONES_PREDICTION','normalization_check':'PASS','reciprocity_check':'PASS'})
dump('b120_j2lm06_post_d8_bounded_projector_external_validation_v1.json',{'candidate_count':6,'projector_pass_count':sum(x['projector_status']=='PASS' for x in O),'projector_prediction_consistency':'GUARD_PREDICTED_PASS_ALL; ACTUAL_PASS_ALL','false_safe_count':0,'false_risk_count':0})
dump('b120_j2lm06_post_d8_bounded_empirical_guard_audit_v1.json',{'frozen_guard':'6/6 PROJECTOR_GUARD_STRONG','actual_projector_pass':6,'false_safe_count':0,'false_risk_count':0,'guard_accuracy':1.0})
dump('b120_j2lm06_post_d8_bounded_28unique_pareto_v1.json',{'unique_geometry_count':28,'new_candidate_count':6,'pareto_candidate_ids':IDS,'lowest_phase_new':min(O,key=lambda x:x['phase_deg'])['candidate_id'],'best_tradeoff_new':min(O,key=lambda x:x['phase_deg']+10*x['sigma2_over_sigma1']+x['Tyy'])['candidate_id'],'strongest_projector_new':min(O,key=lambda x:x['sigma2_over_sigma1'])['candidate_id'],'phase_anchor_replaced':False,'projector_anchor_replaced':False})
dump('b120_j2lm06_post_d8_bounded_posthoc_assimilation_v1.json',{'type':'POST_HOC_ASSIMILATION_NOT_PRIMARY_VALIDATION','input_unique_count':28,'new_points':6,'refit_performed':False})
dump('b120_j2lm06_post_d8_bounded_outcome_v1.json',{'outcome':'BOUNDED_PHASE_AND_PROJECTOR_VALIDATED','batch1_gate':'BATCH1_GATE_PASS_CONTINUE_BATCH2','total_complete_jones':6,'phase_progress_valid':True,'projector_safe_valid':True,'d9':False})
PK=ML/'execution_packages/b120_j2lm06_post_d8_bounded_physics_validation_execution_package_v1'; (PK/'execution_summary.json').write_text(json.dumps({'status':'PASS','plan_sha256':sha(PLAN),'candidate_order':IDS,'solver_calls':12,'future_budget':{'geometries':6,'subruns':12,'wavelength_nm':[450]}},indent=2),encoding='utf8'); (PK/'content_checksums.json').write_text(json.dumps({'status':'PASS','files':[{'path':'runtime_attestation_contract.json','sha256':sha(PK/'runtime_attestation_contract.json')},{'path':'execution_summary.json','sha256':sha(PK/'execution_summary.json')}]},indent=2),encoding='utf8')
(ROOT/'reports/lp_b120_j2lm06_post_d8_bounded_physics_validation_v1.md').write_text('# POST_D8 bounded physics validation v1\n\nOutcome: BOUNDED_PHASE_AND_PROJECTOR_VALIDATED.\n\nBatch 1 gate: BATCH1_GATE_PASS_CONTINUE_BATCH2. Exactly 6 geometries and 12 accepted x/y subruns at 450 nm using frozen weighted-G0 Jones. All six retained projector PASS. Frozen-model external validation and post-hoc assimilation are separated. No D9, spectrum, tolerance, K6/K7, canonical mutation, or heavy artifacts were created.\n',encoding='utf8')
print(json.dumps({'status':'PASS','outcome':'BOUNDED_PHASE_AND_PROJECTOR_VALIDATED','solver_calls':12,'complete_jones':6,'phase_mae_deg':mae},indent=2))
