from pathlib import Path
import json, csv, math, hashlib
R=Path(r'D:/project/worktrees/blue_apcd_lp_stage11_4'); A=R/'outputs/lp_ml_dataset_v1/analysis'; P=R/'outputs/lp_ml_dataset_v1/plans'; REP=R/'reports'
def H(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def norm(v): return math.sqrt(sum(x*x for x in v))
def angle(a,b):
 na,nb=norm(a),norm(b)
 return math.degrees(math.acos(max(-1,min(1,sum(x*y for x,y in zip(a,b))/(na*nb))))) if na and nb else 0.0
script=R/'scripts/lp_b120_j2lm06_post_d8_trust_region_shrink_plan_freeze_v1.py'
audit_p=A/'b120_j2lm06_post_d8_trust_region_shrink_factor_audit_v1.json'; audit=json.loads(audit_p.read_text()); scales=[1.0,0.5,audit['anchor']['Psi_deg']]
for r in audit['rows']:
 a=float(r['nominal_alpha']); full=[x/a for x in r['requested']]; actual=r['actual']; aa=angle([x/s for x,s in zip(actual,scales)],[x/s for x,s in zip(full,scales)]); r['ray_angle_error_deg']=aa; r['ray_preservation_cosine']=math.cos(math.radians(aa))
# summaries recompute
summ=[]
for des in ['A_UNIFORM_RADIAL','B_TWO_REDUCED_CENTRAL_PAIRS','C_ANISOTROPIC_WIDTH_FULL_D_PSI_HALF']:
 rr=[r for r in audit['rows'] if r['design']==des]; vals=sorted(r['norm_effective_alpha'] for r in rr); angs=sorted(r['ray_angle_error_deg'] for r in rr); ev=sorted(r['phase_even_over_odd'] for r in rr if r['phase_even_over_odd'] is not None)
 summ.append({'design':des,'geometry_count':len(rr),'unique_from_anchor_count':sum(not r['duplicate_anchor'] for r in rr),'manufacturing_pass_count':sum(r['manufacturing_pass'] for r in rr),'median_norm_effective_alpha':vals[len(vals)//2] if vals else 0,'max_ray_angle_error_deg':max(angs) if angs else 0,'median_ray_angle_error_deg':angs[len(angs)//2] if angs else 0,'median_even_over_odd':ev[len(ev)//2] if ev else None,'duplicate_count':sum(r['duplicate_anchor'] for r in rr),'status':'REJECTED_QUANTIZATION'})
audit['design_summaries']=summ; audit['central_gradient']['normalized_phase_gradient']=audit['central_gradient'].get('normalized_phase_gradient') or audit['central_gradient'].get('normalized_gradient_phase_deg_per_unit')
audit_p.write_text(json.dumps(audit,indent=2,sort_keys=True))
outd=A/'b120_j2lm06_post_d8_trust_region_design_comparison_v1.json'; d=json.loads(outd.read_text()); d['design_summaries']=summ; outd.write_text(json.dumps(d,indent=2,sort_keys=True))
outg=A/'b120_j2lm06_post_d8_trust_region_geometry_gate_v1.csv'
with outg.open('w',newline='') as f:
 w=csv.writer(f); w.writerow(['design','probe_id','nominal_alpha','effective_alpha_W','effective_alpha_D','effective_alpha_Psi','norm_effective_alpha','ray_angle_error_deg','ray_preservation_cosine','duplicate_anchor','manufacturing_pass','direct_gap_nm','periodic_gap_nm','status'])
 for x in audit['rows']: w.writerow([x['design'],x['probe_id'],x['nominal_alpha'],*x['effective_alpha'],x['norm_effective_alpha'],x['ray_angle_error_deg'],x['ray_preservation_cosine'],x['duplicate_anchor'],x['manufacturing_pass'],x['geometry']['direct_gap_nm'],x['geometry']['nearest_periodic_gap_nm'],'REJECTED_QUANTIZATION'])
report=REP/'lp_b120_j2lm06_post_d8_trust_region_shrink_plan_v1.md'; g=audit['central_gradient']; k=audit['curvature']; lines=['# APCD LP D8 Trust-Region Shrink Plan Freeze v1','','Status: HARD_GATE_QUANTIZATION_FLOOR_PREVENTS_MEANINGFUL_SHRINK','','Offline-only; solver/lumapi/FDTD calls = 0. No D9, progression candidate, execution package, or physics staging.','',f"Anchor: `{audit['anchor_id']}`; active variables J2_width_nm, D_nm, Psi_deg; fixed J1_side=110 nm, J2_length=106 nm, H=500 nm, period=432 nm, material=APCD_TIO2_NATIVE_M1.",'',f"Central gradient rank={g['rank']}, singular values={g['singular_values']}, condition={g['condition_number']}; normalized phase gradient={g['normalized_phase_gradient']}.",f"Directional curvature is negative in 4/4 directions; mean={k['mean']:.6f}, max abs={k['max_abs']:.6f}, even/odd magnitude ratio={k['even_over_odd']:.6f}.",'','Quantization rules: centers integer/exact-half-nm, J2 width integer, D/Psi recomputed from quantized centers. Required nominal alpha values: 1/2, 1/3, 1/4, 1/5, 1/8.']
rr=[r for r in audit['rows'] if r['design']=='A_UNIFORM_RADIAL' and abs(r['nominal_alpha']-.5)<1e-9]; lines += ['', 'For Design A at alpha=1/2, normalized-ray angular errors are '+', '.join(f"{r['ray_angle_error_deg']:.2f} deg" for r in rr)+'. Width rounding collapses the width component for all four directions. At alpha=1/3 and 1/4 the ray distortion remains large; at alpha=1/5 and 1/8 all four points collapse exactly to anchor. The first nonzero integer width step requires alpha=1, which is not a shrink.','', 'Design A uniform radial: rejected; no common alpha gives four unique, ray-preserving shrunken geometries.','Design B two reduced central pairs: rejected; same width-grid collapse/angular distortion and incomplete curvature-direction coverage.','Design C anisotropic width-full/D-Psi-half: rejected; effective width alpha remains 1, so it cannot establish a reduced-radius linear region; center quantization remains an angular-risk.','', 'Manufacturing geometry remains legal for enumerated points (direct/periodic gaps above 60 nm, no overlap, primitive valid), but quantization prevents meaningful access to a smaller trust region. Therefore no future solver budget is frozen: 0 geometries / 0 x-y subruns / 450 nm only, planning-only not authorized.','', 'No full Hessian is claimed; this is a sampled directional shrink audit only.','', 'Outputs:']
files=[audit_p,A/'b120_j2lm06_post_d8_trust_region_quantization_floor_v1.json',outd,outg,P/'b120_j2lm06_post_d8_trust_region_shrink_diagnostic_plan_v1.json',P/'b120_j2lm06_post_d8_trust_region_shrink_diagnostic_plan_v1.csv',P/'b120_j2lm06_post_d8_trust_region_shrink_execution_contract_v1.json',P/'b120_j2lm06_post_d8_trust_region_shrink_ml_label_contract_v1.json',P/'b120_j2lm06_post_d8_trust_region_shrink_validation_metric_contract_v1.json']
for p in files: lines.append(f"- `{str(p.relative_to(R)).replace(chr(92),'/')}` SHA256 `{H(p)}`")
lines += ['', 'Protected report SHA256 before/after are unchanged; existing D7/D8/canonical physics evidence remains read-only.']; report.write_text('\n'.join(lines)+'\n',encoding='utf-8')
manifest_p=A/'b120_j2lm06_post_d8_trust_region_shrink_checksum_manifest_v1.json'; man=json.loads(manifest_p.read_text()); files += [report]; man['files']={str(p.relative_to(R)).replace('\\','/'):{'sha256':H(p),'bytes':p.stat().st_size} for p in files}; manifest_p.write_text(json.dumps(man,indent=2,sort_keys=True)); print(json.dumps({'status':audit['selected_design'],'summaries':summ,'script':str(script.relative_to(R)).replace('\\','/')}))
