from __future__ import annotations
import csv,hashlib,json,shutil
from pathlib import Path
R=Path(r"D:\project\worktrees\blue_apcd_lp_stage11_4");O=R/'outputs';ML=O/'lp_ml_dataset_v1';C17=ML/'canonical_v1_17';C19=ML/'canonical_v1_19';F=ML/'staging/b120_common_mode_phase_translation_stage_d3_v1r2_attempt3_finalized';P=ML/'plans';A=ML/'analysis';S=R/'scripts/lp_b120_negative_common_mode_stage_d4_plan_v1.py';REP=R/'reports/lp_b120_negative_common_mode_stage_d4_plan_v1.md'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):
 with Path(p).open(encoding='utf8',newline='') as f:return list(csv.DictReader(f))
def write(p,rs):
 rs=list(rs);ks=list(dict.fromkeys(k for r in rs for k in r));
 with Path(p).open('w',encoding='utf8',newline='') as f:w=csv.DictWriter(f,fieldnames=ks);w.writeheader();w.writerows(rs)
def atomic(p,x):
 t=Path(p).with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(x,indent=2,sort_keys=True),encoding='utf8');t.replace(p)
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def append(path,delta):write(path,read(path)+delta)
def main():
 if C19.exists():raise SystemExit('CANONICAL_V1_19_AUDIT_FAILED:PREEXISTENCE')
 need=[F/'geometry_membership_v1_18.csv',F/'subrun_records_delta_v1_18.csv',F/'candidate_wavelength_jones_delta_v1_18.csv',F/'quality_audit_v1_18.json',F/'schema_field_audit_v1_18.json',F/'checksums_v1_18.json']
 if not all(p.is_file() for p in need):raise SystemExit('D3_FINALIZED_SOURCE_AUDIT_FAILED')
 q=json.loads((F/'quality_audit_v1_18.json').read_text());s=json.loads((F/'schema_field_audit_v1_18.json').read_text());g=read(F/'geometry_membership_v1_18.csv');sub=read(F/'subrun_records_delta_v1_18.csv');j=read(F/'candidate_wavelength_jones_delta_v1_18.csv')
 if q.get('status')!='PASS' or s.get('status')!='PASS' or (len(g),len(sub),len(j))!=(8,16,8):raise SystemExit('D3_FINALIZED_SOURCE_AUDIT_FAILED')
 shutil.copytree(C17,C19);append(C19/'geometry_master_v1_17.csv',g);append(C19/'candidate_wavelength_jones_v1_17.csv',j);append(C19/'subrun_records_v1_17.csv',sub)
 counts={'unique_full_dimer_geometries':108,'450_nm_Jones_rows':108,'total_wavelength_Jones_rows':192,'formal_full_dimer_subruns':384,'complete_four_point_geometries':28,'constituent_geometries':10,'constituent_wavelength_rows':16};atomic(C19/'dataset_manifest_v1_19.json',{'ML_DATA_CONTRACT_VERSION':'LP_ML_SCHEMA_V1.19','canonical_version':'CANONICAL_V1_19','parent_canonical':'CANONICAL_V1_17','appended_source':'B120_COMMON_MODE_PHASE_TRANSLATION_STAGE_D3_V1R2_ATTEMPT3_FINALIZED','counts':counts,'append_only':True});files=[p for p in C19.iterdir() if p.name!='checksums_v1_19.json'];atomic(C19/'checksums_v1_19.json',{'status':'PASS','self_reference_policy':'excludes itself','files':[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(files)]})
 A.mkdir(exist_ok=True);write(A/'stage_d3_finalized_canonical_merge_audit_v1.csv',[{'status':'PASS','parent_rows':[100,184,368],'delta_rows':[8,8,16],'counts':json.dumps(counts),'finalized_only_source':True}]);write(A/'b120_positive_common_mode_stage_d3_sequence_summary_v1.csv',[{'backbone':'A','phases_deg':'[97.943,102.087,107.048]','direction':'AWAY_FROM_TARGET'},{'backbone':'B','phases_deg':'[99.334,104.621,108.944]','direction':'AWAY_FROM_TARGET'}])
 base={'A':{'id':'LP_H500_D0_CTRL_B120_J2LP05','w':100},'B':{'id':'LP_H500_D1_B120_J2WP02','w':102}};steps=[('A',-1),('A',-2),('A',-3),('A',-4),('A',-5),('B',-1),('B',-2),('B',-3)];plan=[]
 for order,(b,d) in enumerate(steps,1):
  j1=110+d;j2l=115+d;j2w=base[b]['w']+d;D=90+(j1+j2l)/2;c=.25;x1=c-D/2;x2=c+D/2;geom={'J1_side_nm':j1,'J2_length_nm':j2l,'J2_width_nm':j2w,'J1_center_x_nm':x1,'J2_center_x_nm':x2,'D_nm':D,'period_nm':432,'H_nm':500};eid=f"LP_H500_D4_B120_{b}_CM{d:+d}";exact=h(geom);rel=h({'J1':j1,'J2L':j2l,'J2W':j2w,'D':D});sym=h({'a':j1,'b':j2l,'w':j2w,'D':D});pg=432-(D+j1/2+j2l/2);plan.append({'candidate_id':eid,'logical_candidate_id':eid,'candidate_instance_id':eid,'source_stage':'B120_NEGATIVE_COMMON_MODE_TRANSLATION_STAGE_D4_V1','backbone_id':base[b]['id'],'candidate_origin':'NEGATIVE_COMMON_MODE_REVERSAL_FROM_D3','common_mode_operator_version':'D3_COMMON_MODE_OPERATOR_V1_SIGN_REVERSED','common_mode_delta_nm':d,'execution_order':order,'evidence_neighbor_ids':json.dumps([base[b]['id']]),'evidence_source':'CANONICAL_V1_19_BACKBONE','planning_status':'PLANNED_NOT_RUN','physics_label':'ABSENT_NOT_SIMULATED','prediction_status':'NO_FORMAL_MODEL_PREDICTION','J1_side_nm':j1,'J2_length_nm':j2l,'J2_width_nm':j2w,'J1_center_x_nm':x1,'J2_center_x_nm':x2,'D_nm':D,'direct_gap_nm':90,'nearest_periodic_gap_nm':pg,'nearest_periodic_gap_direction':'x','H_nm':500,'period_nm':432,'rotation_deg':0,'material':'APCD_TIO2_NATIVE_M1','exact_geometry_hash_sha256':exact,'canonical_relative_geometry_hash_sha256':rel,'symmetry_equivalence_geometry_hash_sha256':sym,'split_group':rel,'split_assignment':'UNASSIGNED','authorized_subruns':2,'wavelength_nm':450,'inputs':'x,y','mechanism_hypothesis':'NEGATIVE_COMMON_MODE_PHASE_TRANSLATION','expected_direction':'PHASE_TOWARD_TARGET_HYPOTHESIS_ONLY','projector_behavior':'UNKNOWN_NOT_SIMULATED','spectral_authorization':'NOT_AUTHORIZED'})
 write(P/'b120_negative_common_mode_translation_stage_d4_v1.csv',plan);atomic(P/'b120_negative_common_mode_translation_stage_d4_v1.json',{'stage':'B120_NEGATIVE_COMMON_MODE_TRANSLATION_STAGE_D4_V1','status':'PLANNED_NOT_RUN','candidate_count':len(plan),'candidates':plan,'hypothesis':'NEGATIVE_COMMON_MODE_DIRECTION_HYPOTHESIS_FROM_POSITIVE_DIRECTION_REVERSAL'});write(A/'b120_negative_common_mode_stage_d4_geometry_gate_v1.csv',[{'candidate_id':r['candidate_id'],'status':'PASS','direct_gap_nm':r['direct_gap_nm'],'nearest_periodic_gap_nm':r['nearest_periodic_gap_nm'],'half_grid_centers':True,'integer_dimensions':True,'duplicate':False} for r in plan]);atomic(A/'b120_negative_common_mode_stage_d4_direction_basis_v1.json',{'positive_direction':'AWAY_FROM_TARGET','negative_direction_hypothesis':'PHASE_TOWARD_TARGET_HYPOTHESIS_ONLY','A_CMP01':'POSITIVE_DIRECTION_DIAGNOSTIC_NOT_BACKBONE'})
 atomic(P/'b120_negative_common_mode_stage_d4_ml_label_contract_v1.json',{'schema':'LP_ML_SCHEMA_V1.20','candidate_count':8,'subruns':16,'physics_fields':'ABSENT_NOT_SIMULATED until FDTD','prediction_physics_separation':'strict','split_policy':'canonical_relative_geometry_hash_sha256/UNASSIGNED'});atomic(P/'b120_negative_common_mode_stage_d4_spectral_rule_v1.json',{'authorization_status':'NOT_AUTHORIZED','reason':'NO_COMPLETE_SEED_AND_POSITIVE_COMMON_MODE_WRONG_PHASE_DIRECTION','max_preliminary_pool':2});links=[C19/'checksums_v1_19.json',P/'b120_negative_common_mode_translation_stage_d4_v1.csv',P/'b120_negative_common_mode_translation_stage_d4_v1.json',P/'b120_negative_common_mode_stage_d4_ml_label_contract_v1.json',S];atomic(P/'b120_negative_common_mode_stage_d4_execution_contract_v1.json',{'status':'PASS','candidate_count':8,'future_subruns':16,'order':[r['candidate_id'] for r in plan],'solver_calls':0,'self_reference_policy':'excludes itself','hash_linkage':[{'path':str(p),'sha256':sha(p)} for p in links]});REP.write_text('# B120 negative common-mode Stage D4 plan v1\n\n- Status: `PLAN_READY`\n- 8 negative common-mode candidates; 16 future subruns.\n',encoding='utf8');print(json.dumps({'status':'PASS','counts':counts,'D4':len(plan),'solver_calls':0}))
if __name__=='__main__':main()
