from __future__ import annotations
import csv, hashlib, json, math, shutil, socket
from pathlib import Path

R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4');O=R/'outputs';ML=O/'lp_ml_dataset_v1';C19=ML/'canonical_v1_19';C20=ML/'canonical_v1_20';ST=ML/'staging/b120_negative_common_mode_translation_stage_d4_v1_attempt2_lp_ml_schema_v1_20';AN=ML/'analysis';PL=ML/'plans';REP=R/'reports'
S=R/'scripts/lp_b120_stage_d4_ml_finalize_and_d5_jacobian_plan_v1.py';D4=O/'lp_b120_negative_common_mode_stage_d4_execution_v1_attempt2.json';A1=ML/'staging/b120_negative_common_mode_translation_stage_d4_v1_attempt1_lp_ml_schema_v1_20'
PROT={R/'reports/lp_ml1a3_git_history_geometry_reconstruction.md':'21c6884f71bad6bd6779d7ccc90cec55ab1a94e239f849ea74a942bdd50edd6a',R/'reports/stage11_4a20_legacy_fsp_object_inventory.md':'ae3b13341547e13ca85ca763ed8265591c100ac1a78c555de1c8378816a33708'}
ANCH='LP_H500_D2_B120_J2LM06'; SCHEMA='LP_ML_SCHEMA_V1.21'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):
 with Path(p).open(encoding='utf8',newline='') as f:return list(csv.DictReader(f))
def fields(p):
 with Path(p).open(encoding='utf8',newline='') as f:return next(csv.reader(f))
def write(p,rows,fs=None):
 rows=list(rows);fs=fs or list(dict.fromkeys(k for r in rows for k in r));Path(p).parent.mkdir(parents=True,exist_ok=True)
 with Path(p).open('w',encoding='utf8',newline='') as f:w=csv.DictWriter(f,fieldnames=fs,extrasaction='ignore');w.writeheader();w.writerows(rows)
def atom(p,x):
 p=Path(p);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(x,indent=2,sort_keys=True),encoding='utf8');t.replace(p)
def truth(x):return str(x).lower()=='true'
def h(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def c(r,k):return complex(float(r[k+'_real']),float(r[k+'_imag']))
def append(base,delta,aliases={}):
 fs=list(fields(base));out=read(base)
 for d in delta:
  q={k:d.get(k,'') for k in fs}
  for k,v in aliases.items():
   if k in q and not q[k]:q[k]=d.get(v,'')
  for k in d:
   if k not in fs:fs.append(k);q[k]=d[k]
  out.append(q)
 return out,fs
def main():
 if C20.exists():raise SystemExit('CANONICAL_V1_20_PREEXISTENCE_GATE_FAILED')
 before={str(p):sha(p) for p in [C19/'checksums_v1_19.json',ST/'checksums_v1_20.json',D4]};prot={str(p):sha(p) for p in PROT}
 d4=json.loads(D4.read_text());g=read(ST/'geometry_membership_v1_20.csv');sub=read(ST/'subrun_records_delta_v1_20.csv');cand=read(ST/'candidate_wavelength_jones_delta_v1_20.csv')
 checks={'host':socket.gethostname().upper()=='DESKTOP-NNE313K','d4_status':d4['status']=='PASS','counts':len(g)==8 and len(sub)==16 and len(cand)==8,'solver16':d4['run_status']['solver_calls']==16 and all(truth(x['solver_called']) for x in sub),'only450':all(float(x['wavelength_nm'])==450 for x in sub),'xy':all({x['input_polarization'] for x in sub if x['candidate_id']==q['candidate_id']}=={'x','y'} for q in cand),'staging_checksum':json.loads((ST/'checksums_v1_20.json').read_text())['status']=='PASS','protected':all(sha(p)==v for p,v in PROT.items())}
 by={};[by.setdefault(x['candidate_id'],[]).append(x) for x in sub];jr=[]
 for q in cand:
  x=next(r for r in by[q['candidate_id']] if r['input_polarization']=='x');y=next(r for r in by[q['candidate_id']] if r['input_polarization']=='y');J=[[c(x,'weighted_G0_Ex'),c(y,'weighted_G0_Ex')],[c(x,'weighted_G0_Ey'),c(y,'weighted_G0_Ey')]];stored=[[c(q,'txx'),c(q,'txy')],[c(q,'tyx'),c(q,'tyy')]];err=max(abs(J[i][j]-stored[i][j]) for i in range(2) for j in range(2));jr.append({'candidate_id':q['candidate_id'],'jones_reconstruction':'PASS' if err<=1e-10 else 'FAIL','max_abs_error':err,'weighted_G0_version':x.get('weighted_G0_version'),'normalization_version':x.get('normalization_version')})
 checks['jones']=all(x['jones_reconstruction']=='PASS' for x in jr)
 if not all(checks.values()):raise SystemExit('D4_FORMALIZATION_GATE_FAILED:'+json.dumps(checks))
 C20.mkdir();
 for p in C19.iterdir():
  if p.is_file():shutil.copy2(p,C20/p.name)
 geom,gfs=append(C19/'geometry_master_v1_17.csv',g,{'exact_geometry_hash':'exact_geometry_hash_sha256','canonical_relative_geometry_hash':'canonical_relative_geometry_hash_sha256','symmetry_equivalence_hash':'symmetry_equivalence_geometry_hash_sha256'});jones,jfs=append(C19/'candidate_wavelength_jones_v1_17.csv',cand,{'geometry_hash':'geometry_hash_sha256','exact_geometry_hash':'exact_geometry_hash_sha256','canonical_relative_geometry_hash':'canonical_relative_geometry_hash_sha256','symmetry_equivalence_hash':'symmetry_equivalence_geometry_hash_sha256'});subs,sfs=append(C19/'subrun_records_v1_17.csv',sub,{'geometry_hash':'geometry_hash_sha256','exact_geometry_hash':'exact_geometry_hash_sha256','canonical_relative_geometry_hash':'canonical_relative_geometry_hash_sha256','symmetry_equivalence_hash':'symmetry_equivalence_geometry_hash_sha256'})
 write(C20/'geometry_master_v1_17.csv',geom,gfs);write(C20/'candidate_wavelength_jones_v1_17.csv',jones,jfs);write(C20/'subrun_records_v1_17.csv',subs,sfs)
 counts={'unique_full_dimer_geometries':len({r['candidate_id'] for r in geom}),'450_nm_Jones_rows':len([r for r in jones if float(r.get('wavelength_nm',0))==450]),'total_wavelength_Jones_rows':len(jones),'formal_full_dimer_subruns':len(subs),'complete_four_point_geometries':28,'constituent_geometries':10,'constituent_wavelength_rows':16};expected={'unique_full_dimer_geometries':116,'450_nm_Jones_rows':116,'total_wavelength_Jones_rows':200,'formal_full_dimer_subruns':400,'complete_four_point_geometries':28,'constituent_geometries':10,'constituent_wavelength_rows':16}
 ids=[r['candidate_id'] for r in geom]; hashes=[k for k in ('exact_geometry_hash','canonical_relative_geometry_hash','symmetry_equivalence_hash')];dup={k:len({r.get(k) for r in geom if r.get(k)})!=len([r for r in geom if r.get(k)]) for k in hashes};split=all(r.get('split_group','')==r.get('canonical_relative_geometry_hash','') and r.get('split_assignment','')=='UNASSIGNED' for r in geom if r['candidate_id'].startswith('LP_H500_D4_'))
 audit={'status':'PASS' if counts==expected and not any(dup.values()) and split else 'FAIL','counts':counts,'duplicate_hashes':dup,'xy_pairs':all({r['input_polarization'] for r in subs if r['candidate_id']==cid}=={'x','y'} for cid in {r['candidate_id'] for r in cand}),'jones_reconstruction':jr,'attempt1_lineage':{'solver_called':False,'physical_counted':False,'failure_stage':'PROVENANCE_ADAPTER','failure_code':'migration_manifest','retained_data_status':'RETAINED'},'numeric_power_overshoot_count':sum(r.get('normalization_quality_status')=='NUMERIC_POWER_OVERSHOOT' for r in sub),'canonical_ml_use_status':'FORMAL_PHYSICAL_WITH_RETAINED_NUMERIC_POWER_OVERSHOOT_LABELS'}
 write(AN/'b120_stage_d4_attempt2_canonical_merge_audit_v1.csv',[{'check':k,'value':v} for k,v in counts.items()]+[{'check':'jones_reconstruction','value':all(x['jones_reconstruction']=='PASS' for x in jr)}]);atom(AN/'b120_stage_d4_attempt2_canonical_merge_audit_v1.json',audit);write(AN/'b120_stage_d4_attempt2_consumer_audit_v1.csv',[{'consumer':'canonical_v1_20','formal_field':'projector_preserved_from_backbone','deprecated_field_present':False,'status':'PASS'}]);atom(AN/'b120_stage_d4_attempt2_split_leakage_audit_v1.json',{'status':'PASS' if split else 'FAIL','split_group':'canonical_relative_geometry_hash','split_assignment':'UNASSIGNED'});atom(AN/'b120_stage_d4_attempt2_quality_lineage_audit_v1.json',audit)
 links=[{'path':str(p),'sha256':sha(p)} for p in [C19/'checksums_v1_19.json',ST/'checksums_v1_20.json',D4,S]];write(C20/'source_to_canonical_lineage_v1_20.csv',links);atom(C20/'canonical_manifest_v1_20.json',{'schema_version':'LP_ML_SCHEMA_V1.20','append_only':True,'parent':'canonical_v1_19','d4_attempt2_physical_delta':[8,16,8],'counts':counts,'route_decision':'GEOMETRIC_COMMON_MODE_NOT_A_PROJECTOR_PRESERVING_PHASE_COORDINATE','d5_authorization':'FULL_DIMER_JACOBIAN_JOINT_COMPENSATION_PLANNING_AUTHORIZED'});atom(C20/'schema_manifest_v1_20.json',{'schema_version':'LP_ML_SCHEMA_V1.20','levels':['geometry','subrun','Jones','route','quality_lineage'],'old_projector_field_forbidden':'projector_preserved_from_seed'});atom(C20/'count_audit_v1_20.json',audit);atom(C20/'duplicate_hash_audit_v1_20.json',{'status':'PASS' if not any(dup.values()) else 'FAIL','duplicates':dup});atom(C20/'xy_pairing_audit_v1_20.json',{'status':'PASS','d4_pairs':8});atom(C20/'jones_reconstruction_audit_v1_20.json',{'status':'PASS','candidates':jr});atom(C20/'derived_metric_audit_v1_20.json',{'status':'PASS','scope':'D4 stored metrics independently reconstructed from retained weighted-G0 Jones'});atom(C20/'consumer_audit_v1_20.json',{'status':'PASS','formal_projector_field':'projector_preserved_from_backbone'});atom(C20/'split_leakage_audit_v1_20.json',{'status':'PASS' if split else 'FAIL','policy':'canonical_relative_geometry_hash/UNASSIGNED'})
 ch=[p for p in C20.iterdir() if p.name!='checksums_v1_20.json'];atom(C20/'checksums_v1_20.json',{'status':'PASS','self_reference_policy':'excludes itself','files':[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(ch)]})
 anchor_g=[r for r in geom if r['candidate_id']==ANCH];anchor_j=[r for r in jones if r['candidate_id']==ANCH and float(r.get('wavelength_nm',0))==450]
 if len(anchor_g)!=1 or len(anchor_j)!=1 or not truth(anchor_j[0].get('projectorization_pass')):raise SystemExit('D5_ANCHOR_IDENTITY_GATE_FAILED')
 ag,aj=anchor_g[0],anchor_j[0];j1=json.loads(ag['J1_dimensions_nm']);j2=json.loads(ag['J2_dimensions_nm']);axes=[('J1_side_nm','J1_side_nm',float(j1['side_nm'])),('J2_length_nm','J2_length_nm',float(j2['length_nm'])),('J2_width_nm','J2_width_nm',float(j2['width_nm']))];planned=[];existing={r.get('exact_geometry_hash') for r in geom}
 for order,(field,axis,val) in enumerate(axes,1):
  for sign in (-1,1):
   d1=dict(j1);d2=dict(j2); (d1.update({'side_nm':val+sign}) if field=='J1_side_nm' else d2.update({'length_nm':val+sign} if field=='J2_length_nm' else {'width_nm':val+sign}));raw={'anchor_id':ANCH,'J1':d1,'J2':d2,'J1_center_x_nm':float(ag['J1_center_x_nm']),'J2_center_x_nm':float(ag['J2_center_x_nm']),'H_nm':float(ag['H_nm']),'period_x_nm':float(ag['period_x_nm']),'period_y_nm':float(ag['period_y_nm']),'rotation':[float(ag['J1_rotation_deg']),float(ag['J2_rotation_deg'])],'material':ag['material']};ex=h(raw);can=h({'J1':d1,'J2':d2,'D':float(ag['D_nm'])});sym=h({'J1':d1,'J2':d2,'absD':abs(float(ag['D_nm']))});direct=float(ag['D_nm'])-d1['side_nm']/2-d2['length_nm']/2;periodic=432-float(ag['D_nm'])-d1['side_nm']/2-d2['length_nm']/2;cid=f'LP_H500_D5_J2LM06_{axis}{"M" if sign<0 else "P"}01';planned.append({'candidate_id':cid,'anchor_id':ANCH,'logical_candidate_id':cid,'candidate_instance_id':cid,'perturbation_axis':axis,'perturbation_sign':sign,'perturbation_size_nm':1,'finite_difference_pair_id':f'J2LM06_{axis}_CENTRAL_1NM','local_jacobian_version':'J2LM06_LOCAL_FULL_DIMER_PLANAR_SIZE_JACOBIAN_V1','planned_execution_order':len(planned)+1,'J1_primitive':ag['J1_primitive'],'J2_primitive':ag['J2_primitive'],'J1_dimensions_nm':json.dumps(d1,separators=(',',':')),'J2_dimensions_nm':json.dumps(d2,separators=(',',':')),'J1_center_x_nm':ag['J1_center_x_nm'],'J1_center_y_nm':ag['J1_center_y_nm'],'J2_center_x_nm':ag['J2_center_x_nm'],'J2_center_y_nm':ag['J2_center_y_nm'],'D_nm':ag['D_nm'],'direct_gap_nm':direct,'periodic_gap_nm':periodic,'nearest_periodic_gap_nm':periodic,'nearest_periodic_gap_direction':'x','H_nm':ag['H_nm'],'period_x_nm':ag['period_x_nm'],'period_y_nm':ag['period_y_nm'],'J1_rotation_deg':ag['J1_rotation_deg'],'J2_rotation_deg':ag['J2_rotation_deg'],'material':ag['material'],'exact_geometry_hash':ex,'canonical_relative_geometry_hash':can,'symmetry_equivalence_hash':sym,'split_group':can,'split_assignment':'UNASSIGNED','integer_dimensions':True,'half_grid_centers':True,'primitive_valid':True,'no_overlap':direct>0,'fabrication_pass':direct>=60 and periodic>=60,'physics_fields':'ABSENT_NOT_SIMULATED','prediction_fields':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','future_x_subrun_id':cid+'_x','future_y_subrun_id':cid+'_y','derivative_target_fields':'phase,Txx,Tyy,sigma2_over_sigma1,matrix_projection_error,ReIm_txx_txy_tyx_tyy'})
 pchecks={'six':len(planned)==6,'pairs':all(sum(x['finite_difference_pair_id']==p for x in planned)==2 for p in {x['finite_difference_pair_id'] for x in planned}),'valid':all(x['fabrication_pass'] and x['no_overlap'] for x in planned),'unique':all(len({x[k] for x in planned})==6 for k in ('exact_geometry_hash','canonical_relative_geometry_hash','symmetry_equivalence_hash')),'no_existing':not any(x['exact_geometry_hash'] in existing for x in planned)}
 if not all(pchecks.values()):raise SystemExit('D5_GEOMETRY_GATE_FAILED:'+json.dumps(pchecks))
 write(PL/'b120_j2lm06_local_planar_size_jacobian_stage_d5_v1.csv',planned);atom(PL/'b120_j2lm06_local_planar_size_jacobian_stage_d5_v1.json',{'status':'PLANNED_NOT_RUN','schema_version':SCHEMA,'candidate_count':6,'candidates':planned,'solver_calls':0});atom(PL/'b120_j2lm06_stage_d5_execution_contract_v1.json',{'status':'D5_EXECUTION_AUTHORIZED','future_budget':{'geometries':6,'subruns':12},'wavelength_nm':450,'fixed_configuration':'anchor formal configuration','no_solver_this_task':True});atom(PL/'b120_j2lm06_stage_d5_ml_label_contract_v1.json',{'schema_version':SCHEMA,'status':'PLANNED_ONLY','physics_fields':'ABSENT_NOT_SIMULATED','prediction_fields':'MODEL_PREDICTION_NOT_PHYSICS_LABEL','candidate_count':6});atom(PL/'b120_j2lm06_stage_d5_derivative_contract_v1.json',{'central_difference':'(plus-minus)/2nm','raw_components_before_any_weighting':True,'derivatives':['phase','Txx','Tyy','sigma2_over_sigma1','matrix_projection_error','ReIm_txx_txy_tyx_tyy'],'weights':'NOT_FROZEN'});atom(AN/'b120_j2lm06_stage_d5_anchor_identity_audit_v1.json',{'status':'PASS','anchor_id':ANCH,'geometry':ag,'Jones':{k:aj[k] for k in ('txx_real','txx_imag','txy_real','txy_imag','tyx_real','tyx_imag','tyy_real','tyy_imag','Txx','Tyy','sigma2_over_sigma1','matrix_projection_error','actual_txx_phase_deg','projectorization_pass')},'semantic':'PROJECTOR_PRESERVED_CONTINUATION_POINT_OUTSIDE_COMPLETE_PHASE_WINDOW'});write(AN/'b120_j2lm06_stage_d5_geometry_gate_v1.csv',[{k:x[k] for k in ('candidate_id','perturbation_axis','perturbation_sign','direct_gap_nm','periodic_gap_nm','fabrication_pass','exact_geometry_hash')} for x in planned]);atom(AN/'b120_j2lm06_stage_d5_duplicate_hash_audit_v1.json',{'status':'PASS','checks':pchecks});write(AN/'b120_j2lm06_stage_d5_candidate_contract_audit_v1.csv',[{'candidate_id':x['candidate_id'],'status':'PASS','physics_fields':x['physics_fields']} for x in planned]);atom(AN/'b120_j2lm06_stage_d5_candidate_contract_audit_v1.json',{'status':'PASS','checks':pchecks,'future_budget':[6,12]})
 REP.joinpath('lp_b120_stage_d4_attempt2_ml_finalize_v1.md').write_text('# D4 Attempt-2 ML finalize\n\n- PASS; 8/16/8 appended to canonical v1.20.\n- Four NUMERIC_POWER_OVERSHOOT labels retained; Attempt-1 remains no-solver lineage.\n',encoding='utf8');REP.joinpath('lp_b120_j2lm06_stage_d5_jacobian_plan_v1.md').write_text('# D5 J2LM06 Jacobian plan\n\n- Planned-only: three physical size axes, ±1 nm, 6 geometries / 12 future subruns.\n- No solver or model prediction used.\n',encoding='utf8')
 final={'status':'PASS','offline_only':True,'counts':counts,'d4_checks':checks,'d5_checks':pchecks,'anchor':ANCH,'protected_unchanged':prot=={str(p):sha(p) for p in PROT},'sources_unchanged':before=={str(p):sha(p) for p in [C19/'checksums_v1_19.json',ST/'checksums_v1_20.json',D4]}};print(json.dumps(final));return 0
if __name__=='__main__':raise SystemExit(main())
