import csv,hashlib,itertools,json,math
from pathlib import Path
ROOT=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); ML=ROOT/'outputs/lp_ml_dataset_v1'; AN=ML/'analysis'; PL=ML/'plans'
PLAN=PL/'b120_j2lm06_post_d8_revised_quadratic_map_contract_v2.json'; MAP=AN/'b120_j2lm06_post_d8_reuse_mapping_audit_v2.json'; MAN=AN/'b120_j2lm06_post_d8_revised_coordinate_manifest_v2.json'; GATE=AN/'b120_j2lm06_post_d8_revised_unique_geometry_gate_v2.csv'; CON=PL/'b120_j2lm06_post_d8_revised_quadratic_map_contract_v2.json'; SUP=AN/'b120_j2lm06_post_d8_revised_v1_v2_supersession_v1.json'; PKG=ML/'execution_packages/b120_j2lm06_post_d8_revised_quadratic_map_execution_package_v2'; ST=ML/'staging/b120_j2lm06_post_d8_revised_quadratic_map_v2'
ANCHOR='D8_TRV_PLAN_d6f4911593b64495'
ALIASES={(-1,0,0):'D8_TRV_PLAN_2709798bc19d7b76',(0,0,-1):'D8_TRV_PLAN_3f9495af463cc07b',(1,0,-1):'POSTD8_CAL_PROBE_WP_DM_PM',(-1,0,1):'POSTD8_CURV_MIRROR_WP_DM_PM',(-1,0,-1):'D8_TRV_PLAN_2c6c4edac3638079'}
BASELINE_IDS=['D7_TRV_PROP_00098aaf5db983b9','D7_TRV_PROP_27a9f273b1daf877','D7_TRV_PROP_56364757e6cc98ca','D7_TRV_PROP_5faf242ac18ec85b','D7_TRV_PROP_693ec7d86d7c23e2','D7_TRV_PROP_89eb19e02e4961be','D7_TRV_PROP_ac2e5d6ca24e9987','D7_TRV_PROP_f5fdd16c144945e5','D8_TRV_PLAN_d6f4911593b64495']
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def h(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def geom(u):
 uW,uD,uP=u; j1=[-100.,-.5]; j2=[100.5+.5*uD,.5+uP]; dx=j2[0]-j1[0]; dy=j2[1]-j1[1]; d=math.hypot(dx,dy); psi=math.degrees(math.atan2(dy,dx)); g={'J1_side_nm':110.,'J2_length_nm':106.,'J2_width_nm':100.+uW,'J1_center_nm':j1,'J2_center_nm':j2,'D_nm':d,'Psi_deg':psi,'H_nm':500.,'period_nm':432.,'material':'APCD_TIO2_NATIVE_M1','direct_gap_nm':d-108.,'nearest_periodic_gap_nm':432.-d-108.,'center_grid':'INTEGER_OR_EXACT_HALF_NM','no_overlap':d>=108.,'primitive_valid':True}; g['exact_geometry_hash_sha256']=h(g); rel={'J1_side_nm':110.,'J2_length_nm':106.,'J2_width_nm':100.+uW,'D_rel_nm':d,'Psi_rel_deg':psi}; g['canonical_relative_geometry_hash_sha256']=h(rel); g['symmetry_equivalence_hash_sha256']=g['canonical_relative_geometry_hash_sha256']; return g
def cid(u):
 c=lambda v:'P' if v==1 else 'M' if v==-1 else '0'; return f'POSTD8_QMAP_W{c(u[0])}_D{c(u[1])}_P{c(u[2])}'
coords=list(itertools.product([-1,0,1],repeat=3)); center=(0,0,0); corners=[u for u in coords if all(abs(x)==1 for x in u)]; axes=[u for u in coords if sum(abs(x) for x in u)==1]; rows=[]
for i,u in enumerate(coords,1):
 g=geom(u); c=cid(u)
 if u==center: role,status,src='BASELINE_ANCHOR','TRUSTED_REUSED_FORMAL_PHYSICS',ANCHOR
 elif u in corners: role,status,src='BASELINE_EXISTING','TRUSTED_REUSED_FORMAL_PHYSICS',BASELINE_IDS[corners.index(u)]
 elif u in ALIASES: role,status,src='REUSE_ALIAS','TRUSTED_REUSED_FORMAL_PHYSICS',ALIASES[u]
 else: role,status,src=('PHASE_A_NEW' if u in axes else 'PHASE_B_NEW'),'PLANNED_NOT_RUN',None
 rows.append({'execution_order':i,'candidate_id':c,'normalized_coordinate':list(u),'uW':u[0],'uD':u[1],'uPsi':u[2],'role':role,'status':status,'source_candidate_id':src,'geometry':g,'input_subruns':[f'{c}_x',f'{c}_y'],'physics_fields':'ABSENT_NOT_SIMULATED' if status=='PLANNED_NOT_RUN' else 'TRUSTED_REUSED_FORMAL_PHYSICS','prediction_label':'MODEL_PREDICTION_NOT_PHYSICS_LABEL' if status=='PLANNED_NOT_RUN' else 'TRUSTED_REUSED_FORMAL_PHYSICS'})
unique_rows=[r for r in rows if r['role']!='REUSE_ALIAS']
basis=lambda u:[1,u[0],u[1],u[2],u[0]**2,u[1]**2,u[2]**2,u[0]*u[1],u[0]*u[2],u[1]*u[2]]
import numpy as np
X=np.array([basis(r['normalized_coordinate']) for r in unique_rows],float); sv=np.linalg.svd(X,compute_uv=False); rank=int(np.linalg.matrix_rank(X)); cond=float(sv[0]/sv[-1]); GATE.parent.mkdir(parents=True,exist_ok=True)
flat=[]
for r in unique_rows:
 g=r['geometry']; flat.append({'execution_order':r['execution_order'],'candidate_id':r['candidate_id'],'role':r['role'],'uW':r['uW'],'uD':r['uD'],'uPsi':r['uPsi'],'J2_width_nm':g['J2_width_nm'],'D_nm':g['D_nm'],'Psi_deg':g['Psi_deg'],'direct_gap_nm':g['direct_gap_nm'],'nearest_periodic_gap_nm':g['nearest_periodic_gap_nm'],'exact_geometry_hash_sha256':g['exact_geometry_hash_sha256'],'canonical_relative_geometry_hash_sha256':g['canonical_relative_geometry_hash_sha256'],'symmetry_equivalence_hash_sha256':g['symmetry_equivalence_hash_sha256'],'manufacturing_pass':bool(g['no_overlap'] and g['primitive_valid'] and g['direct_gap_nm']>=60 and g['nearest_periodic_gap_nm']>=60)})
with GATE.open('w',newline='',encoding='utf8') as f: w=csv.DictWriter(f,fieldnames=list(flat[0])); w.writeheader(); w.writerows(flat)
reuse=[{'normalized_coordinate':list(u),'alias_candidate_id':cid(u),'source_candidate_id':src,'reuse_status':'TRUSTED_REUSED_FORMAL_PHYSICS','reweighting':False} for u,src in ALIASES.items()]; MAP.write_text(json.dumps({'audit_version':'POST_D8_REUSE_MAPPING_AUDIT_V2','reuse_count':5,'reuse':reuse,'alias_rows_not_in_unique_fit':True},indent=2,sort_keys=True),encoding='utf8')
manifest={'manifest_version':'POST_D8_REVISED_27COORDINATE_22UNIQUE_MANIFEST_V2','anchor_id':ANCHOR,'coordinate_count':27,'baseline_coordinate_count':9,'trusted_reused_alias_count':5,'new_coordinate_count':13,'unique_physical_geometry_count':22,'phase_a':{'new_geometries':4,'reused':2,'new_subruns':8},'phase_b':{'new_geometries':9,'reused':3,'new_subruns':18},'rows':rows,'unique_fit_candidate_ids':[r['candidate_id'] for r in unique_rows],'alias_candidate_ids':[r['candidate_id'] for r in rows if r['role']=='REUSE_ALIAS'],'design_matrix':{'basis':['1','uW','uD','uPsi','uW2','uD2','uPsi2','uW_uD','uW_uPsi','uD_uPsi'],'rows':22,'columns':10,'rank':rank,'singular_values':sv.tolist(),'condition_number':cond,'rank_pass':rank==10},'solver_calls':0,'status':'READY_FOR_EXECUTION' if rank==10 else 'HARD_GATE_REVISED_QUADRATIC_IDENTIFIABILITY_FAILURE'}; MAN.write_text(json.dumps(manifest,indent=2,sort_keys=True),encoding='utf8')
source_hashes={}
for p in [ROOT/'outputs/lp_ml_dataset_v1/analysis/b120_j2lm06_post_d8_27point_cube_manifest_v1.json',ROOT/'outputs/lp_ml_dataset_v1/plans/b120_j2lm06_bounded_local_validation_stage_d8_v1.json']:
 if p.exists(): source_hashes[str(p.relative_to(ROOT)).replace('\\','/')]=sha(p)
contract={'contract_version':'POST_D8_REVISED_QUADRATIC_MAP_CONTRACT_V2','status':manifest['status'],'anchor_id':ANCHOR,'expected_head':'5a887d6ce2aee6500b4d3c5ec6922029999e99f1','coordinate_count':27,'baseline_coordinate_count':9,'trusted_reused_alias_count':5,'new_coordinate_count':13,'unique_physical_geometry_count':22,'new_solver_budget':{'geometries':13,'x_y_subruns':26,'wavelength_nm':[450]},'manifest_path':str(MAN.relative_to(ROOT)).replace('\\','/'),'gate_path':str(GATE.relative_to(ROOT)).replace('\\','/'),'source_hashes':source_hashes,'frozen_observable':'LP_WEIGHTED_G0_COORDINATE_PERIODIC_G0_V1','material':'APCD_TIO2_NATIVE_M1','no_d9':True,'no_canonical_mutation':True,'no_alias_reweighting':True,'solver_calls':0,'rank_gate':{'actual_unique_rows':22,'columns':10,'rank':rank,'condition_number':cond,'pass':rank==10}}; CON.write_text(json.dumps(contract,indent=2,sort_keys=True),encoding='utf8'); PLAN.write_text(json.dumps(contract,indent=2,sort_keys=True),encoding='utf8')
SUP.write_text(json.dumps({'supersession_version':'POST_D8_QMAP_V1_TO_V2_SUPERSESSION_V1','v1_manifest':'outputs/lp_ml_dataset_v1/analysis/b120_j2lm06_post_d8_27point_cube_manifest_v1.json','v1_status':'HARD_GATE_DATA_CONFLICT','v2_contract':'outputs/lp_ml_dataset_v1/plans/b120_j2lm06_post_d8_revised_quadratic_map_contract_v2.json','authorization':'explicit revised user contract','v1_preserved':True,'v2_semantics':'five trusted aliases, thirteen new, twenty-two unique fit rows'},indent=2,sort_keys=True),encoding='utf8')
if rank!=10: raise SystemExit('HARD_GATE_REVISED_QUADRATIC_IDENTIFIABILITY_FAILURE')
PKG.mkdir(parents=True,exist_ok=True); ST.mkdir(parents=True,exist_ok=True); pkg={'package_version':'POST_D8_REVISED_QUADRATIC_MAP_EXECUTION_PACKAGE_V2','plan_path':str(PLAN.relative_to(ROOT)).replace('\\','/'),'manifest_path':str(MAN.relative_to(ROOT)).replace('\\','/'),'candidate_order':[r['candidate_id'] for r in rows if r['status']=='PLANNED_NOT_RUN'],'subrun_order':[f"{r['candidate_id']}_{p}" for r in rows if r['status']=='PLANNED_NOT_RUN' for p in ('x','y')],'new_geometries':13,'new_subruns':26,'phase_a_candidate_ids':[r['candidate_id'] for r in rows if r['role']=='PHASE_A_NEW'],'phase_b_candidate_ids':[r['candidate_id'] for r in rows if r['role']=='PHASE_B_NEW'],'solver_calls':0}; (PKG/'package_manifest.json').write_text(json.dumps(pkg,indent=2,sort_keys=True),encoding='utf8'); print(json.dumps({'status':'READY_FOR_EXECUTION','rank':rank,'condition_number':cond,'phase_a':pkg['phase_a_candidate_ids'],'phase_b':pkg['phase_b_candidate_ids'],'new_subruns':26},indent=2))
