import hashlib,json,os
from pathlib import Path
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); P=R/'outputs/lp_ml_dataset_v1/plans'; A=R/'outputs/lp_ml_dataset_v1/analysis'
def h(p): return hashlib.sha256(p.read_bytes()).hexdigest()
old=R/'outputs/lp_ml_dataset_v1/staging/lp_ml_dataset_v1_round1_smoke_v1'; plan=P/'lp_ml_dataset_v1_round1_smoke_16_plan_v1.json'; base=P/'lp_ml_dataset_v1_contract_v1.json'
contract={'execution_contract_version':'LP_ML_BROADBAND_SMOKE_ATTEMPT2_EXECUTION_V1','attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT2_V1','supersedes_attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT1_V1','source_contract_sha256':h(base),'smoke_plan_sha256':h(plan),'new_staging_path':'outputs/lp_ml_dataset_v1/staging/lp_ml_dataset_v1_round1_smoke_attempt2_v1','new_runtime_temp':'%TEMP%\\lp_ml_dataset_v1_round1_smoke_attempt2_runtime','authorization':{'geometries':16,'new_subruns_max':32,'wavelengths_nm':[450.0,450.5,451.0,451.5,452.0,452.5,453.0,453.5,454.0],'automatic_continue_after_first_x_acceptance':True},'sampling_fix':{'root_cause':'monitor local/global settings left at default five-point sampling; source start/stop alone did not freeze monitor grid','global_calls':[{'property':'frequency points','value':9},{'property':'use wavelength spacing','value':True},{'property':'use source limits','value':True}],'local_monitor_calls':[{'property':'override global monitor settings','value':True},{'property':'use wavelength spacing','value':True},{'property':'frequency points','value':9},{'property':'use source limits','value':True}],'target_domain':'wavelength','target_vector_nm':[450.0,450.5,451.0,451.5,452.0,452.5,453.0,453.5,454.0]},'lifecycle':'preflight build/save/reload gate -> entered ledger -> solver -> extraction -> checkpoint reload -> acceptance','no_five_point_fallback':True,'no_interpolation_from_five_points':True,'no_auto_retry_entered_case':True,'forbidden':['D9','Batch B','old Batch2','remaining 240 geometries','model training','inverse design','new candidate selection']}
(P/'lp_ml_dataset_v1_broadband_smoke_attempt2_execution_contract_v1.json').write_text(json.dumps(contract,indent=2,sort_keys=True)+'\n',encoding='utf-8')
sup={'ledger_version':'LP_ML_SMOKE_ATTEMPT_SUPERSESSION_V1','old_attempt':{'attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT1_V1','staging_path':str(old.relative_to(R)).replace('\\','/'),'entered':1,'accepted':0,'complete_jones':0,'returned_frequency_count':5,'admitted_physics_rows':0,'quality_sha256':h(old/'quality_audit_v1.json'),'entered_accounting_sha256':h(old/'entered_accounting_v1.json'),'failure_evidence_sha256':h(old/'failure_evidence_v1.json'),'ingestion_status':'EXCLUDED_NO_FORMAL_PHYSICS'},'new_attempt':{'attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT2_V1','staging_path':'outputs/lp_ml_dataset_v1/staging/lp_ml_dataset_v1_round1_smoke_attempt2_v1','authorization':'EXPLICIT_RERUN_OF_FIRST_X_ONLY_UNDER_NEW_ATTEMPT','candidate_plan_unchanged':True,'smoke_subset_unchanged':True,'new_accounting_separate':True,'no_overwrite':True},'historical_failed_attempt_visible':True}
(A/'lp_ml_dataset_v1_attempt_supersession_ledger_v1.json').write_text(json.dumps(sup,indent=2,sort_keys=True)+'\n',encoding='utf-8')
print(json.dumps({'contract_sha256':h(P/'lp_ml_dataset_v1_broadband_smoke_attempt2_execution_contract_v1.json'),'supersession_sha256':h(A/'lp_ml_dataset_v1_attempt_supersession_ledger_v1.json'),'old_failure_preserved':True},indent=2))
