import json, hashlib
from pathlib import Path
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4');A=R/'outputs/lp_ml_dataset_v1/analysis'
def load(n):return json.loads((A/n).read_text(encoding='utf-8'))
audit=load('lp_ml_dataset_v1_round1_production_failure_audit_v1.json'); base=load('lp_ml_dataset_v1_round1_partial_baseline_metrics_v1.json'); mlp=load('lp_ml_dataset_v1_round1_partial_residual_mlp_metrics_v1.json')
proposal={'proposal_version':'LP_ML_ROUND2_OFFLINE_ACQUISITION_PROPOSAL_V1','status':'NOT_AUTHORIZED_DUE_ROUND1_PRODUCTION_HARD_GATE','runnable_solver_package':False,'candidate_count':0,'solver_authorized':False,'active_learning_fDTD':False,'selection_criteria':['high ensemble uncertainty','low-phase target region','projector-favorable continuous metrics','phase-wrap vicinity','manufacturing boundaries','diversity from existing geometry groups'],'recommended_scale_range':[64,128],'basis_rows':'partial 61-geometry dataset only','reason':audit['failure_code'],'no_d9':True,'no_inverse_design':True}
(A/'lp_ml_dataset_v1_round2_offline_acquisition_proposal_v1.json').write_text(json.dumps(proposal,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def f(x):return f'{x:.6g}'
report=R/'reports/lp_ml_dataset_v1_round1_partial_model_audit_v1.md'
report.write_text(f'''# LP_ML_DATASET_V1 Round-1 partial model audit\n\n## Status\n\n`LP_ML_ROUND1_DATA_OR_MODEL_FIX_REQUIRED`\n\n## Production solver accounting\n\n- Planned: 240 geometries / 480 subruns\n- Entered: {audit['solver_entered']}\n- Accepted: {audit['accepted_subruns']}\n- Failed: {audit['failed_subruns']}\n- Retry: {audit['retry_count']}\n- Failed subrun: `{audit['failure_subrun']}`\n- Failure: `{audit['failure_mechanism']}`\n\n## Dataset and split\n\n- Smoke retained: 16 geometries / 144 rows\n- Production complete: {audit['complete_production_geometries']} geometries / {audit['production_spectral_rows']} rows\n- Combined partial: {audit['partial_round1_geometries']} geometries / {audit['partial_round1_spectral_rows']} rows\n- Split: train 387 rows, validation 81 rows, test 81 rows; geometry and alias groups kept together.\n\n## Baselines\n\n| model | test MAE | relative Frobenius mean | phase MAE (deg) |\n|---|---:|---:|---:|\n'''+''.join(f"| {n} | {f(v['metrics']['mae'])} | {f(v['metrics']['frobenius_relative_mean'])} | {f(v['metrics']['phase_circular_deg_mean'])} |\\n" for n,v in base.items())+f'''\n## Residual MLP ensemble\n\n- 5 seeds: 11, 22, 33, 44, 55\n- Architecture: 7→256, four residual blocks, SiLU, LayerNorm, dropout 0.03\n- AdamW 3e-4, weight decay 1e-4, cosine to 1e-6, max 500 epochs, patience 50, gradient clip 1.0\n- Composite loss: {mlp['composite_loss']}\n- Ensemble test MAE: {f(mlp['ensemble_metrics']['mae'])}\n- Relative Frobenius mean: {f(mlp['ensemble_metrics']['frobenius_relative_mean'])}\n- Phase MAE: {f(mlp['ensemble_metrics']['phase_circular_deg_mean'])} deg\n- Uncertainty/error correlation: {f(mlp['uncertainty_error_correlation'])}\n\nThe ensemble was trained only as a partial-coverage diagnostic. It is not promoted to a Round-1 forward surrogate.\n\n## Round-2 proposal\n\nOffline proposal written with zero runnable candidates because the production hard gate remains unresolved. No active-learning solver was launched.\n\n## Hard gates\n\n- No entered-case retry.\n- No model-filled physics rows.\n- No D9, inverse design, K6, Batch B, old Batch2, or canonical v1.21 change.\n- Protected reports unchanged.\n''',encoding='utf-8')
print(json.dumps({'proposal':str((A/'lp_ml_dataset_v1_round2_offline_acquisition_proposal_v1.json').relative_to(R)).replace('\\','/'),'report':str(report.relative_to(R)).replace('\\','/')},indent=2))
