import json
from pathlib import Path
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4');A=R/'outputs/lp_ml_dataset_v1/analysis';S=R/'outputs/lp_ml_dataset_v1/staging/lp_ml_dataset_v1_round1_recovery_attempt1_v1'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def save(p,x): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,indent=2,sort_keys=True,default=str)+'\n',encoding='utf-8')
failed=load(S/'subruns/LPML_R1_GLOBAL_SOBOL_054/y/run_result.json')
out={'outcome':'LP_ML_ROUND1_RECOVERY_HARD_GATE','recovery_attempt_id':'LP_ML_ROUND1_RECOVERY_ATTEMPT1_V1','planned_new_subruns':389,'solver_entered':1,'accepted_subruns':0,'failed_subruns':1,'remaining_authorized_budget_not_executed':388,'first_gate_candidate':'LPML_R1_GLOBAL_SOBOL_054_y','failure_code':'NORMALIZATION_REVIEW_REQUIRED','failure_message':failed.get('error'),'negative_T_wavelength_nm':450.0,'negative_T_value':-8.41216338271679e-05,'checkpoint_present':False,'old_failed_attempt_retained':True,'old_054_x_rerun':False,'untouched_194_started':False,'continuation_allowed_after_first_gate':False,'solver_calls_this_finalize':0,'no_model_retraining':True,'no_data_rewrite':True,'protected_report_sha256':{'reports/lp_ml1a3_git_history_geometry_reconstruction.md':'d0b9dc84dd5daa0e3144dd0e02b65b1e4228abafa6798c217a7e571e17505161','reports/stage11_4a20_legacy_fsp_object_inventory.md':'ae3b13341547e13ca85ca763ed8265591c100ac1a78c555de1c8378816a33708'}}
save(A/'lp_ml_round1_recovery_attempt1_forensic_v1.json',out)
save(A/'lp_ml_round1_recovery_hard_gate_decision_v1.json',{'decision':'LP_ML_ROUND1_RECOVERY_HARD_GATE','reason':'054_y recovery entered solver and reproduced negative-T normalization failure','negative_T':{'wavelength_nm':450.0,'value':out['negative_T_value']},'no_retry':True,'no_continuation':True,'remaining_untouched_geometries':194,'remaining_unexecuted_subruns':388,'new_solver_calls_after_failure':0})
ledger=load(A/'lp_ml_round1_recovery_supersession_ledger_v1.json'); ledger.update({'recovery_attempt_status':'FAILED_FIRST_GATE','recovery_entered_subruns':1,'recovery_accepted_subruns':0,'recovery_failed_subruns':1,'untouched_continuation_started':False,'old_attempt_unchanged':True}); save(A/'lp_ml_round1_recovery_supersession_ledger_v1.json',ledger)
report=R/'reports/lp_ml_round1_recovery_attempt1_hard_gate_v1.md'
report.write_text(f'''# LP_ML Round-1 recovery attempt 1 hard gate\n\n## Outcome\n\n`LP_ML_ROUND1_RECOVERY_HARD_GATE`\n\n## First gate\n\n`LPML_R1_GLOBAL_SOBOL_054_y` entered the new recovery attempt exactly once and failed during formal normalization. At 450.0 nm the raw directional transmission was `-8.41216338271679e-05`; the runner raised `NORMALIZATION_REVIEW_REQUIRED`. No checkpoint, raw weighted fields, or admitted Jones rows were produced.\n\n## Accounting\n\n- New recovery budget: 389 entered maximum\n- Entered: 1\n- Accepted: 0\n- Failed: 1\n- Untouched continuation: not started\n- Remaining unexecuted budget: 388\n\nThe 194 untouched geometries were not started because the first-gate contract requires 054_y acceptance before continuation. No retry was issued. The historical failed attempt and the new failed attempt remain separate.\n\n## Integrity\n\nNo old accepted case was rerun, no geometry or plan was changed, no physics data was rewritten, and no model retraining was performed. Protected report hashes remained unchanged.\n''',encoding='utf-8')
print(json.dumps(out,indent=2,sort_keys=True))
