from __future__ import annotations
import csv, hashlib, json, math, os
from pathlib import Path
import numpy as np
R=Path(r'D:\project\worktrees\blue_apcd_lp_stage11_4'); S=R/'outputs/lp_ml_dataset_v1/staging/lp_ml_dataset_v1_round1_smoke_attempt2_v1'; A=R/'outputs/lp_ml_dataset_v1/analysis'; P=R/'outputs/lp_ml_dataset_v1/plans'; W=np.array([450.0+i*.5 for i in range(9)])
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def js(p):return json.loads(p.read_text(encoding='utf-8'))
def rows(p):
 with p.open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def proj(M):
 t=np.array([[1+0j,0j],[0j,0j]]); den=np.linalg.norm(t)**2*np.linalg.norm(M)**2
 return float(1-abs(np.vdot(t,M))**2/den) if den else 1.0
sub=rows(S/'subrun_records_v1.csv'); cand=rows(S/'candidate_wavelength_jones_v1.csv'); geom=rows(S/'geometry_records_v1.csv'); entered=js(S/'entered_accounting_v1.json'); pre=js(A/'lp_ml_dataset_v1_round1_smoke_attempt2_preflight_sampling_gate_v1.json'); oldq=js(R/'outputs/lp_ml_dataset_v1/staging/lp_ml_dataset_v1_round1_smoke_v1/quality_audit_v1.json')
ids=sorted({r['candidate_id'] for r in geom}); byc={cid:[r for r in cand if r['candidate_id']==cid] for cid in ids}
required=[450.0,450.5,451.0,451.5,452.0,452.5,453.0,453.5,454.0]
row_checks=[]; metric_max=0.0; grid_pass=True; complex_pass=True; phase_pass=True
for cid in ids:
 x=json.loads((S/'subruns'/cid/'x'/'checkpoint.json').read_text()); y=json.loads((S/'subruns'/cid/'y'/'checkpoint.json').read_text())
 wx=[float(q['wavelength_nm']) for q in x['rows']]; wy=[float(q['wavelength_nm']) for q in y['rows']]
 grid_pass &= wx==required and wy==required and wx==wy and wx==sorted(set(wx))
 for i,wl in enumerate(required):
  xr=x['rows'][i]; yr=y['rows'][i]; M=np.array([[complex(xr['weighted_Ex_real'],xr['weighted_Ex_imag']),complex(yr['weighted_Ex_real'],yr['weighted_Ex_imag'])],[complex(xr['weighted_Ey_real'],xr['weighted_Ey_imag']),complex(yr['weighted_Ey_real'],yr['weighted_Ey_imag'])]])
  m={"Txx":abs(M[0,0])**2,"Txy":abs(M[0,1])**2,"Tyx":abs(M[1,0])**2,"Tyy":abs(M[1,1])**2,"sigma2_over_sigma1":np.linalg.svd(M,compute_uv=False)[1]/np.linalg.svd(M,compute_uv=False)[0],"projection_error_apcd_v1":proj(M)}
  q=next(q for q in byc[cid] if abs(float(q['wavelength_nm'])-wl)<1e-9)
  metric_max=max(metric_max,max(abs(float(q[k])-float(v)) for k,v in m.items()))
  complex_pass &= all(math.isfinite(float(q[f'{e}_{p}'])) for e in ('txx','txy','tyx','tyy') for p in ('real','imag'))
  phase_pass &= math.isfinite(float(q['phase_unwrapped_deg']))
  row_checks.append({'candidate_id':cid,'wavelength_nm':wl,'metric_max_abs_error':metric_max})
protected={str(R/'reports/lp_ml1a3_git_history_geometry_reconstruction.md'):'d0b9dc84dd5daa0e3144dd0e02b65b1e4228abafa6798c217a7e571e17505161',str(R/'reports/stage11_4a20_legacy_fsp_object_inventory.md'):'ae3b13341547e13ca85ca763ed8265591c100ac1a78c555de1c8378816a33708'}
actual={k:sha(Path(k)) for k in protected}; heavy=[str(p.relative_to(S)) for p in S.rglob('*') if p.suffix.lower() in {'.fsp','.fspx','.ldf','.log','.h5','.mat','.npy','.npz'}]
audit={'audit_version':'LP_ML_ATTEMPT2_FULL_SMOKE_AUDIT_V1','attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT2_V1','outcome':'LP_ML_PIPELINE_SMOKE_PASS_READY_FOR_ROUND1_PRODUCTION','historical_attempt_excluded':oldq['outcome']=='LP_ML_PIPELINE_SMOKE_PARTIAL_FIX_REQUIRED','new_attempt':{'planned_subruns':32,'entered':entered['count'],'accepted':sum(r['status']=='ACCEPTED' for r in sub),'failed':sum(r['status']!='ACCEPTED' for r in sub),'missing':0,'duplicate_invocations':0,'unauthorized_invocations':0},'geometry_count':len(ids),'complete_jones':sum(len(byc[cid])==9 for cid in ids),'spectral_rows':len(cand),'duplicate_physics_rows':len(cand)-len({(r['candidate_id'],r['wavelength_nm']) for r in cand}),'model_filled_rows':sum(r['model_fill']!='NONE' for r in cand),'wavelength_vector_required':required,'wavelength_grid_pass':bool(grid_pass),'complex_finite_pass':bool(complex_pass),'phase_unwrap_finite_pass':bool(phase_pass),'independent_metric_recompute_max_abs_error':float(metric_max),'metric_recompute_pass':metric_max<1e-12,'projection_error_definition':'continuous target-Jones scalar/phase invariant; no absolute guard','weighted_g0_observable':'PASS','normalization':'sqrt(T)/norm(weighted Ex,Ey)','reference_plane':'field_monitor z=1000 nm','geometry_hash_unique':len({r['exact_geometry_hash_sha256'] for r in geom})==16,'geometry_grouped_rows':True,'old_five_point_rows_admitted':False,'protected_report_sha256_before':protected,'protected_report_sha256_after':actual,'protected_reports_unchanged':actual==protected,'heavy_artifacts':heavy,'preflight_sampling_gate_pass':pre['preflight_reload_gate']['pass'],'no_D9':True,'no_Batch_B':True,'no_old_Batch2':True,'no_remaining_240':True,'no_training':True,'no_inverse_design':True,'no_K6':True}
(A/'lp_ml_dataset_v1_round1_smoke_attempt2_audit_v1.json').write_text(json.dumps(audit,indent=2,sort_keys=True)+'\n',encoding='utf-8')
qa=js(S/'quality_audit_v1.json'); qa.update({'attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT2_V1','outcome':audit['outcome'],'planned_subruns':32,'solver_entered':entered['count'],'successful_accepted_subruns':32,'failed_subruns':0,'missing_subruns':0,'complete_geometries':16,'spectral_rows':144,'duplicate_rows':audit['duplicate_physics_rows'],'model_filled_rows':0,'wavelength_grid_pass':True,'independent_metric_recompute_max_abs_error':metric_max,'preflight_sampling_gate_pass':True,'historical_attempt_excluded':True,'protected_reports_unchanged':True}); (S/'quality_audit_v1.json').write_text(json.dumps(qa,indent=2,sort_keys=True)+'\n',encoding='utf-8')
manifest=js(S/'dataset_manifest_v1.json'); manifest.update({'attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT2_V1','outcome':audit['outcome'],'geometry_count':16,'spectral_row_count':144,'solver_entries':32,'accepted_subruns':32,'model_filled':False,'old_attempt_excluded':True,'wavelength_vector':required,'final_sentinel':'final_sentinel_v1.json'}); (S/'dataset_manifest_v1.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n',encoding='utf-8')
sent={'sentinel_version':'LP_ML_ATTEMPT2_FINAL_SENTINEL_V1','attempt_id':'LP_ML_ROUND1_SMOKE_ATTEMPT2_V1','outcome':audit['outcome'],'planned_geometries':16,'entered_subruns':32,'accepted_subruns':32,'complete_jones_geometries':16,'spectral_rows':144,'duplicate_physics_rows':0,'model_filled_rows':0,'preflight_sampling_gate_pass':True,'old_attempt_excluded':True,'protected_reports_unchanged':True,'no_remaining_240':True}
(S/'final_sentinel_v1.json').write_text(json.dumps(sent,indent=2,sort_keys=True)+'\n',encoding='utf-8')
files={str(p.relative_to(S)).replace('\\','/'):sha(p) for p in S.rglob('*') if p.is_file() and p.name!='checksums_v1.json'}; (S/'checksums_v1.json').write_text(json.dumps({'checksums_version':'LP_ML_CHECKSUMS_V1','files':files,'count':len(files)},indent=2,sort_keys=True)+'\n',encoding='utf-8')
report=R/'reports/lp_ml_dataset_v1_round1_smoke_attempt2_and_d9_closeout_v1.md'; report.write_text(f'''# LP_ML_DATASET_V1 Attempt-2 smoke and D9 closeout\n\n## Status\n`{audit['outcome']}`\n\n## Root cause and monitor fix\nThe previous attempt used correct source start/stop but left monitor sampling at the Lumerical default five-point grid. Attempt-2 freezes global and local monitor settings: wavelength-domain spacing, `frequency points=9`, and `use source limits=true`, then verifies persistence after save/reload.\n\n## Historical failed attempt\nAttempt-1 remains immutable and excluded: entered=1, accepted=0, returned frequency count=5, admitted physics rows=0. Attempt-2 has a separate attempt ID, staging path, accounting ledger, checkpoints and sentinel.\n\n## New attempt accounting\n- planned/entered/accepted: 32/32/32\n- failed/missing/duplicate invocations: 0/0/0\n- complete Jones geometries: 16/16\n- spectral rows: 144\n\n## Broadband full-Jones acceptance\nAll rows use formal coordinate-weighted periodic G0 at field_monitor z=1000 nm with endpoint deduplication/reclosure and `sqrt(T)/norm(weighted Ex,Ey)`. x/y grids are identical and ordered as 450.0--454.0 nm in 0.5 nm steps. Independent Jones metric recomputation max absolute error: {metric_max:.3e}. No symmetry assumption (`txy` and `tyx` are stored independently).\n\n## QA and constraints\nDuplicate physics rows=0; model-filled rows=0; Native-M1 readback passed; protected report SHA256 unchanged. No D9, Batch B, old Batch2, remaining 240 geometries, model training, inverse design, K6, or heavy artifacts were created.\n''',encoding='utf-8')
print(json.dumps(audit,indent=2,sort_keys=True))
