import csv, json, hashlib
from pathlib import Path
R=Path(r'D:/project/worktrees/blue_apcd_np_k6_mdc_v1'); O=R/'outputs/np_k6_m8_20g_forward_retraining_v1'; D=R/'docs/np_k6_m8_20g_forward_retraining_and_promotion_review_v1.md'
def rows(n):
 with (O/n).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def js(n):return json.loads((O/n).read_text(encoding='utf-8-sig'))
def f(x):
 try:return f'{float(x):.6f}'
 except:return str(x)
raw=rows('model_metrics_raw.csv'); ps=rows('ps_contrast_summary.csv'); common=rows('common_HF16_full_learning_value.csv'); new4=rows('new4_heldout_full_difficulty.csv'); truth=rows('hf20_ps_truth_distribution_summary.csv'); pros=rows('m7a_prospective_like_selection_time_audit.csv'); req=js('m8_requirement_audit.json'); review=js('m8_promotion_review.json'); dec=js('m8_external_promotion_decision.json'); manifest=js('m8_training_run_manifest.json'); prereg=O/'NP_K6_M8_20G_FORWARD_RETRAINING_PREREG_V1.json'
lines=['# NP K6 M8 20G forward retraining and promotion review v1','',f"Final state: `{dec['final_state']}`",'','## Authority and frozen method','',f"- Preregistration `NP_K6_M8_20G_FORWARD_RETRAINING_PREREG_V1`; SHA256 `{hashlib.sha256(prereg.read_bytes()).hexdigest()}`.",'- M7A preregistration SHA256: `bd221dfe8d15475cb5c0f9d5959a6595fed2238ff58f7ca1befbdc421bf65951`.','- Formal HF20 authority: 440 rows = 20 geometries × 2 polarizations × 11 exact wavelengths (445–455 nm); 20 geometry hashes; 40 paired P/S cases; G01 quarantine absent; duplicate/conflicting provenance 0.','- M7A contribution: 88 rows / 4 geometries; pre-M7A HF16: 352 rows. LF20: 440/440 keys matched with no missing baseline.','- Ordered physical `[D1,D2,D3,D4,D5,D6]` is preserved; no diameter sorting, pooling, or permutation-invariant encoding. Scope is `NORMAL_INCIDENCE_ONLY` (`u_x=0`, `k_y=0`). P/S remains explicit.','- Primary output is `[R, eta_m-3 … eta_m+3]`; `T` is derived from the symbolic order sum. Directionality and leakage are derived quantities. Complex labels remain `COMPLEX_ORDER_CONTRACT_NOT_YET_READY`.','- M8 uses 20-fold LOGO, fold-local normalization, 3 deterministic seeds (17, 29, 43), and 9 fixed model families.','']
lines += ['## Model comparison','', '| Model | order MAE | eta(+1) MAE | R MAE | T MAE | rho | Top-3 | champion rank | worst order MAE | energy max |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for r in raw:lines.append(f"| {r['model']} | {f(r['order_profile_mae'])} | {f(r['eta_plus1_mae'])} | {r['R_mae'] or 'unsupported'} | {f(r['T_mae'])} | {f(r['ranking_spearman'])} | {f(r['top3_recall'])} | {r['true_champion_predicted_rank']} | {f(r['worst_geometry_order_profile_mae'])} | {f(r['energy_residual_max'])} |")
lines += ['', '- Best order-profile trainable result: `LF_ridge_residual` (0.042516). Lowest η(+1) MAE is `circular_cnn` (0.079635), but its T/energy/worst-case gates fail. No model passes every frozen development gate.','- Per-seed ranking and error dispersion are retained in `model_metrics_by_seed.csv` and `ranking_seed_stability.json`; no single seed is used as a hidden selection shortcut.','- Raw and constrained metric files are both retained; constrained projection is not used as a substitute for raw physics validity.','']
lines += ['## Ranking, physics, and P/S','', '- LF-ridge and paired correction reach ρ≈0.9534 and Top-3 recall 2/3, but both predict the true champion at rank 4. Thus high global rho does not close champion-neighborhood reliability.','- Best P/S contrast MAE is ResMLP 0.087505, but its other numerical/physics gates fail. P/S averaging is not used.','- Physics bookkeeping `T=sum(eta_m)` is exact in the OOF schema; raw energy and negative-power violations remain nonzero for multiple learned models.','', '| Model | P/S contrast MAE | negative-power violation | energy max |','|---|---:|---:|---:|']
pm={r['model']:r for r in ps}; phys=js('physics_consistency_metrics.json')
for r in raw:
 q=phys.get(r['model'],{});lines.append(f"| {r['model']} | {f(pm[r['model']]['contrast_mae'])} | {f(q.get('raw_negative_power_violation_rate'))} | {f(q.get('raw_energy_residual_max'))} |")
lines += ['','## HF20 P/S truth distribution','', '| Scope | metric | n | mean | median | P90 | max |','|---|---|---:|---:|---:|---:|---:|']
for r in truth:lines.append(f"| {r['scope']} | {r['metric']} | {r['n']} | {f(r['mean'])} | {f(r['median'])} | {f(r['p90'])} | {f(r['max'])} |")
lines += ['','The HF20 P/S contrast remains materially nonzero; polarization must remain an explicit condition.','']
lines += ['## Common-HF16 learning value','', '| Model | order improved/degraded | eta(+1) improved/degraded | M8 R mean | M8 T mean | M8 P/S mean |','|---|---:|---:|---:|---:|---:|']
for r in common:lines.append(f"| {r['model']} | {r['improved_order']}/{r['degraded_order']} | {r['improved_eta_plus1']}/{r['degraded_eta_plus1']} | {f(r['M8_R_mean'])} | {f(r['M8_T_mean'])} | {f(r['M8_PS_mean'])} |")
lines += ['','The geometry-level paired deltas are mixed. Direct MLP/ResMLP improve many common geometries but remain poor globally; LF-ridge has 9 improved / 7 degraded and a small negative median order delta. This is targeted learning value, not uniform generalization improvement.','']
lines += ['## M7A new4 held-out difficulty','', '| Model | worst order MAE | worst eta(+1) MAE | worst R MAE | worst T MAE | worst P/S MAE |','|---|---:|---:|---:|---:|---:|']
for model in sorted({r['model'] for r in new4}):
 z=[r for r in new4 if r['model']==model];lines.append(f"| {model} | {f(max(float(r['order_profile_mae']) for r in z))} | {f(max(float(r['eta_plus1_mae']) for r in z))} | {f(max(float(r['R_mae']) for r in z))} | {f(max(float(r['T_mae']) for r in z))} | {f(max(float(r['PS_contrast_mae']) for r in z))} |")
lines += ['','G01 `RESIDUAL-TAIL` remains the clearest difficult regime; G02/G03 show useful targeted information, but the new4 tail is not removed.','']
lines += ['## M7A prospective-like acquisition audit','', '- The audit compares frozen M7 selection-time fields against M7A truth only; it does not use M8 predictions and is not an external test.','', '| Role | geometry | selection-time evidence |','|---|---|---|']
for g in sorted({r['geometry_id'] for r in pros}):
 z=[r for r in pros if r['geometry_id']==g];lines.append(f"| {z[0]['role']} | {g} | " + '; '.join(f"{r['selection_model']} err={f(r['absolute_error'])}" for r in z))
lines += ['','Residual-tail and polarization/ranking stress roles were genuine informative acquisition choices; this supports targeted development but not external promotion.','']
lines += ['## Residual structure and disagreement','', '- `residual_structure_by_geometry.csv`, `residual_structure_oof_by_geometry.csv`, and `hf_minus_lf_residual_summary.csv` retain per-geometry, P/S, wavelength/order residual evidence for LF, global-bias, affine and ridge baselines.','- Model disagreement is informative but not calibrated probability: high-disagreement η(+1) bucket error 0.087264 vs low 0.041426; high order-profile bucket 0.046785 vs low 0.023997.','']
lines += ['## Promotion and governance','',f"- Final decision: `{dec['final_state']}` — {dec['decision_rationale']}.",'- External set `NP_K6_FORWARD_EXTERNAL_FROZEN_SET_V1` remains metadata-only: 12 geometries / 24 future P/S logical cases. No target was read and no external solver ran.','- Concurrency governance remains `CONCURRENCY3_FUNCTIONAL_STABILITY_EVIDENCE_PRESENT`; max active FDTD 3 with 4 MPI × 1 thread, but CPU/RAM telemetry was unavailable, so throughput optimality is not claimed.','- No new HF, FDTD, LumAPI run, inverse design, angular extension, or external test was started.','- The surrogate remains a development candidate; it is not labeled `FORWARD_SURROGATE_FROZEN`.','']
lines += ['## Validation and reproducibility','', '- Requirement audit: PASS; residual reconstruction max error 5.55e-17; symbolic order schema and T/order closure PASS; selection-time manifest fields preserved exactly; no inverse artifacts in M8 output.','- Regression suite: 25 passed across M5, M5B, M7, M7A and M8 focused tests. Standalone M8 validator: PASS. `git diff --check`: PASS.','- Training fit completed before a post-processing selection-schema mismatch was discovered; recovery was post-processing-only and did not rerun fit or solver.','', 'Evidence directory: `outputs\\np_k6_m8_20g_forward_retraining_v1\\`.']
text='\n'.join(lines).rstrip()+'\n'; text=text.replace('25 passed','26 passed'); D.write_text(text,encoding='utf-8');print(D)
