import csv,json,hashlib
from pathlib import Path
R=Path(r'D:/project/worktrees/blue_apcd_np_k6_mdc_v1');O=R/'outputs/np_k6_m8_20g_forward_retraining_v1';DOC=R/'docs/np_k6_m8_20g_forward_retraining_and_promotion_review_v1.md'
def rd(n):
 with (O/n).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def rj(n):return json.loads((O/n).read_text(encoding='utf-8-sig'))
manifest=rj('m8_training_run_manifest.json');prereg=O/'NP_K6_M8_20G_FORWARD_RETRAINING_PREREG_V1.json';raw=rd('model_metrics_raw.csv');lv=rd('common_HF16_learning_value.csv');decision=rj('m8_external_promotion_decision.json')
lines=['# NP K6 M8 20G forward retraining and promotion review v1','',f"Final state: `{decision['final_state']}`",'']
lines += ['## Authority and preregistration','',f"- M8 preregistration: `NP_K6_M8_20G_FORWARD_RETRAINING_PREREG_V1`; SHA256 `{hashlib.sha256(prereg.read_bytes()).hexdigest()}`.",'- Formal HF authority: 440 rows, 20 geometries, 40 paired P/S cases, exact 445–455 nm, u_x=0 and k_y=0. Ordered [D1…D6] was preserved; no sorting or permutation-invariant compression.','- LF20 authority: 440/440 HF keys matched deterministic LF rows; LF remains explicitly polarization-blind at current normal-incidence scope. G01 quarantine absent; duplicate/conflicting provenance 0.','- External registry `NP_K6_FORWARD_EXTERNAL_FROZEN_SET_V1` remains metadata-only (12 geometries / 24 future P/S cases).','']
lines += ['## Model comparison','', '| Model | order MAE | eta(+1) MAE | R MAE | T MAE | rank ρ | Top-3 | champion rank | worst geometry MAE |','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
for r in raw:lines.append(f"| {r['model']} | {float(r['order_profile_mae']):.6f} | {float(r['eta_plus1_mae']):.6f} | {r['R_mae'] or 'unsupported'} | {float(r['T_mae']):.6f} | {float(r['ranking_spearman']):.6f} | {float(r['top3_recall']):.3f} | {r['true_champion_predicted_rank']} | {float(r['worst_geometry_order_profile_mae']):.6f} |")
lines += ['', 'The strongest numerical trainable result is `LF_ridge_residual` (order MAE 0.042516; η(+1) MAE 0.082800; R MAE 0.068380; T MAE 0.072849). No trainable candidate passed every preregistered promotion gate: champion rank, worst-case, energy residual and/or other gates remain limiting.','']
lines += ['## Ranking, physics, and P/S','', '- Broadband ranking remains strong for LF/ridge families, but the true champion is predicted at rank 4 by the best numerical residual model; high global ρ alone is insufficient for promotion.','- Raw physics audits are retained beside constrained projections. Non-negative-power and energy residual violations remain nonzero before projection; projection is not counted as a physics proof.','- P/S contrast remains an explicit condition. Contrast MAE: LF-only 0.093667, LF-ridge 0.096101, corrected residual MLP 0.124541, circular CNN 0.101093.','']
lines += ['## Common-HF16 learning value','', '| Model | improved geometries | degraded geometries | median Δ(M8−M7) | M7 mean | M8 mean |','|---|---:|---:|---:|---:|---:|']
for r in lv:lines.append(f"| {r['model']} | {r['improved_geometry_count']} | {r['degraded_geometry_count']} | {float(r['median_delta_M8_minus_M7']):.6f} | {float(r['M7_mean_order_profile_mae']):.6f} | {float(r['M8_mean_order_profile_mae']):.6f} |")
lines += ['', 'The common-HF16 comparison shows mixed but generally modest geometry-level gains; it does not support a blanket claim that adding M7A always improves legacy unseen-geometry generalization.','']
lines += ['## M7A new4 and prospective-like audit','', 'The new4 held-out table is split by the frozen roles RESIDUAL-TAIL, RANKING-CHAMPION-STRESS, POLARIZATION-STRESS and COVERAGE-CONTROL. G01 residual-tail remains the clearest difficult point for learned residual models, while G02/G03 show useful targeted information.','', 'The prospective-like audit uses only frozen M7 selection-time fields (LF, calibrated LF, ridge, residual MLP, CNN) against M7A truth. It is not external validation and is not retroactively replaced by M8 predictions.','']
lines += ['## Decision and governance','',f"- Decision: `{decision['final_state']}`.",f"- Rationale: {decision['decision_rationale']}.",'- External HF was not run or authorized automatically. No new development HF, inverse design, angular extension, or M8 follow-on acquisition was started.','- M7A concurrency evidence remains `CONCURRENCY3_FUNCTIONAL_STABILITY_EVIDENCE_PRESENT`; max active FDTD observed was 3 with 4 MPI × 1 thread, but continuous CPU/RAM telemetry was unavailable, so throughput-optimality is not claimed.','']
lines += ['## Reproducibility and solver budget','',f"- 20-fold LOGO, 3 deterministic seeds (17, 29, 43), fold-local normalization, 9 fixed model families; fit completed after preregistration hash `{manifest['preregistration_sha256']}`.",'- Solver calls: FDTD=0, LumAPI run=0, external HF=0, sealed target reads=0, inverse design=0.','- OOF fit completed before a post-processing schema mismatch was found in the frozen selection manifest; post-processing was recovered using only actual frozen fields, without rerunning fit or solver.','']
lines += ['## Evidence','', '- `outputs\\np_k6_m8_20g_forward_retraining_v1\\` contains preregistration, OOF predictions, raw/constrained metrics, ranking, P/S, common-HF16, new4, residual, disagreement, promotion and zero-solver audits.','- External promotion remains pending further targeted development; this report stops before any external FDTD.']
DOC.parent.mkdir(parents=True,exist_ok=True);DOC.write_text('\n'.join(lines).rstrip()+'\n',encoding='utf-8');print(str(DOC))
