import csv,json,hashlib,re,random
from collections import defaultdict
from pathlib import Path
import numpy as np
R=Path(r'D:/project/worktrees/blue_apcd_np_k6_mdc_v1'); O=R/'outputs/np_k6_m8a_final_targeted_acquisition_design_v1'; M7A=R/'outputs/np_k6_m7a_targeted_development_acquisition_design_v1'; M8=R/'outputs/np_k6_m8_20g_forward_retraining_v1'; HF=R/'outputs/np_k6_m7a_primary4_targeted_hf_acquisition_closeout_v1/m7a_formal_development_hf_observations_440rows.csv'; LF=R/'outputs/np_k6_m7a_primary4_targeted_hf_acquisition_closeout_v1/m7a_formal_development_lf_baseline_440rows.csv'; SEL=M7A/'selection_manifest.json'; PRE=O/'NP_K6_M8A_FINAL_TARGETED_ACQUISITION_PREREG_V1.json'; ORD=(-3,-2,-1,0,1,2,3); G01='K6X_D135_D155_D190_D220_D225_D230'
def rd(p):
 with p.open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def wr(n,rs):
 fs=[]
 for r in rs:
  for k in r:
   if k not in fs:fs.append(k)
 with (O/n).open('w',encoding='utf-8',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fs);w.writeheader();w.writerows(rs)
def js(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def mm(v):
 a=np.asarray(v,float); lo=float(a.min()); hi=float(a.max()); return np.ones(len(a))*0.5 if hi-lo<1e-12 else (a-lo)/(hi-lo)
def ds(g):return np.asarray([float(x) for x in re.findall(r'D(\d+)',g)],float)
pr=js(PRE); ph=hashlib.sha256(PRE.read_bytes()).hexdigest(); rec=js(O/'preregistration_sha256.json')
if rec['sha256']!=ph or rec.get('candidate_identities_generated_after_hash') is not False:raise RuntimeError('prereg_order')
hf=rd(HF);lf=rd(LF);cand_all=rd(M7A/'candidate_acquisition_features.csv');oof=rd(M8/'oof_predictions_20g.csv');hmap={(r['geometry_id'],r['polarization'].lower(),int(float(r['wavelength_nm']))):r for r in hf}; lmap={(r['geometry_id'],r['polarization'].lower(),int(float(r['wavelength_nm']))):r for r in lf}; pmap={(r['model'],r['geometry_id'],r['polarization'].lower(),int(float(r['wavelength_nm']))):r for r in oof}; formal=sorted({r['geometry_id'] for r in hf}); hashes={r['geometry_id']:r['geometry_hash'] for r in hf}; cand=[r for r in cand_all if r['geometry_id'] not in set(formal)]; cby={r['geometry_id']:r for r in cand}
if len(cand)<8 or G01 not in formal:raise RuntimeError('candidate_or_g01')
# Detailed G01 forensic from HF20, LF20 and OOF predictions.
grows=[r for r in hf if r['geometry_id']==G01]; gd=ds(G01); jumps=np.diff(gd); lfprof=[];hfprof=[];res=[];wav=[];ps=[]
for w in range(445,456):
 for pol in ('p','s'):
  y=hmap[(G01,pol,w)]; l=lmap[(G01,pol,w)]; yy=np.asarray([float(y[f'eta_m{m:+d}']) for m in ORD]); bb=np.asarray([float(l[f'lf_eta_m{m:+d}']) for m in ORD]); lfprof.append(bb);hfprof.append(yy);res.append(yy-bb)
  q=pmap[('LF_only',G01,pol,w)];wav.append({'wavelength_nm':w,'polarization':pol,'hf_eta_plus1':float(y['eta_m+1']),'lf_eta_plus1':float(l['lf_eta_m+1']),'hf_minus_lf_eta_plus1':float(y['eta_m+1'])-float(l['lf_eta_m+1']),'ridge_error':abs(float(pmap[('LF_ridge_residual',G01,pol,w)]['pred_eta_m+1'])-float(y['eta_m+1'])),'residual_mlp_error':abs(float(pmap[('corrected_residual_mlp',G01,pol,w)]['pred_eta_m+1'])-float(y['eta_m+1'])),'cnn_error':abs(float(pmap[('circular_cnn',G01,pol,w)]['pred_eta_m+1'])-float(y['eta_m+1']))})
 p=hmap[(G01,'p',w)];s=hmap[(G01,'s',w)];ps.append({'wavelength_nm':w,'hf_PS_eta_plus1_abs':abs(float(p['eta_m+1'])-float(s['eta_m+1'])),'lf_PS_eta_plus1_abs':abs(float(lmap[(G01,'p',w)]['lf_eta_m+1'])-float(lmap[(G01,'s',w)]['lf_eta_m+1']))})
res=np.asarray(res); lf_eta_450=float(np.mean([float(lmap[(G01,p,450)]['lf_eta_m+1']) for p in ('p','s')]))
model_error_summary={}
for m in ('LF_ridge_residual','corrected_residual_mlp','circular_cnn'):
    order_err=[]; eta1_err=[]
    for rr in grows:
        key=(m,G01,rr['polarization'].lower(),int(float(rr['wavelength_nm'])))
        order_err.append(np.mean([abs(float(pmap[key][f'pred_eta_m{x:+d}'])-float(rr[f'eta_m{x:+d}'])) for x in ORD]))
        eta1_err.append(abs(float(pmap[key]['pred_eta_m+1'])-float(rr['eta_m+1'])))
    model_error_summary[m]={'order_mae':float(np.mean(order_err)),'eta_plus1_mae':float(np.mean(eta1_err))}
forensic={'geometry_id':G01,'ordered_D1_D6':gd.tolist(),'adjacent_diameter_jumps_nm':jumps.tolist(),'diameter_span_nm':float(gd.max()-gd.min()),'hf20_rows':len(grows),'LF_order_profile_mean':np.asarray(lfprof).mean(0).tolist(),'HF_order_profile_mean':np.asarray(hfprof).mean(0).tolist(),'HF_minus_LF_residual_mean_per_order':res.mean(0).tolist(),'HF_minus_LF_residual_mae_per_order':np.abs(res).mean(0).tolist(),'HF_minus_LF_residual_max_per_order':np.abs(res).max(0).tolist(),'LF_eta_plus1_broadband_mean':float(np.asarray(lfprof)[:,ORD.index(1)].mean()),'HF_eta_plus1_broadband_mean':float(np.asarray(hfprof)[:,ORD.index(1)].mean()),'LF_eta_plus1_min':float(np.asarray(lfprof)[:,ORD.index(1)].min()),'HF_eta_plus1_min':float(np.asarray(hfprof)[:,ORD.index(1)].min()),'LF_eta_plus1_at_450nm':lf_eta_450,'HF_R_available':True,'LF_R_supported':False,'HF_T_mean':float(np.mean([float(r['T_total']) for r in grows])),'LF_T_proxy_mean':float(np.mean([float(lmap[(G01,r['polarization'].lower(),int(float(r['wavelength_nm'])))]['lf_T_proxy']) for r in grows])),'model_error_summary':model_error_summary,'interpretation_hypotheses':['isolated_outlier','smooth_local_residual_region','diameter_jump_driven_cluster','P/S_dependent_cluster','order_redistribution_cluster'],'evidence_only_no_new_truth':True}
(O/'g01_tail_forensic.json').write_text(json.dumps(forensic,indent=2)+'\n',encoding='utf-8');wr('g01_tail_wavelength_order_audit.csv',wav);wr('g01_tail_ps_audit.csv',ps)
# Candidate scores after preregistration hash.
physical=[];g01d=ds(G01)
for r in cand:
 d=ds(r['geometry_id']);physical.append(float(np.linalg.norm((d-g01d)/230.0)))
near_formal=[];nearest=[];nearest_geom=[]
for r in cand:
 d=ds(r['geometry_id']); z=sorted((float(np.linalg.norm((d-ds(g))/230.0)),g) for g in formal); nearest.append(z[0][0]);nearest_geom.append(z[0][1]);near_formal.append(z[:3])
gprox=1-mm(physical);g_lf_sim=1-mm([abs(float(r['lf_eta_plus1'])-forensic['LF_eta_plus1_broadband_mean']) for r in cand]);resid=np.asarray([float(r['residual_tail_score_norm']) for r in cand]);psv=mm([float(r['predicted_ps_contrast']) for r in cand]);rc=mm([abs(float(r['ridge_eta_plus1'])-float(r['cnn_eta_plus1'])) for r in cand]);spectral=1-mm([float(r['lf_response_distance_norm']) for r in cand]);rankv=np.asarray([float(r['model_rank_variance_norm']) for r in cand]);rev=np.asarray([float(r['pairwise_model_reversal_proxy_norm']) for r in cand]);pot=np.asarray([float(r['performance_score_norm']) for r in cand]);near=1-mm([abs(x-0.667) for x in pot]);cal=mm([np.mean([abs(float(r['calibrated_eta_plus1'])-float(r[k])) for k in ('ridge_eta_plus1','residual_mlp_eta_plus1','cnn_eta_plus1')]) for r in cand]);tail_score=.30*gprox+.20*g_lf_sim+.20*resid+.15*rc+.10*psv+.05*spectral; rank_score=.25*rankv+.20*rev+.20*near+.15*pot+.10*rc+.10*psv
rows=[]
for i,r in enumerate(cand):
 rows.append({**r,'g01_physical_distance':physical[i],'g01_physical_proximity':float(gprox[i]),'g01_lf_response_similarity':float(g_lf_sim[i]),'ridge_cnn_disagreement_norm':float(rc[i]),'spectral_robustness_norm':float(spectral[i]),'near_top3_margin_norm':float(near[i]),'calibrated_vs_learned_disagreement_norm':float(cal[i]),'tail_localization_score':float(tail_score[i]),'ranking_disambiguation_score':float(rank_score[i]),'redundancy_score':float(1/(1+nearest[i])),'nearest_hf20_geometry':nearest_geom[i],'nearest_hf20_distance':nearest[i],'ordered_D1_D6':','.join(str(int(x)) for x in ds(r['geometry_id'])),'candidate_identity_generated_after_prereg_hash':True})
def sortkey(r,field):return (-float(r[field]),float(r['redundancy_score']),-int(r['geometry_hash'][:16],16))
tailpick=sorted(rows,key=lambda r:sortkey(r,'tail_localization_score'))[0]; rankpick=sorted([r for r in rows if r['geometry_id']!=tailpick['geometry_id']],key=lambda r:sortkey(r,'ranking_disambiguation_score'))[0]
tailq=sorted([r for r in rows if r['geometry_id'] not in {tailpick['geometry_id'],rankpick['geometry_id']}],key=lambda r:sortkey(r,'tail_localization_score'));rankq=sorted([r for r in rows if r['geometry_id'] not in {tailpick['geometry_id'],rankpick['geometry_id']}],key=lambda r:sortkey(r,'ranking_disambiguation_score'));mixq=sorted([r for r in rows if r['geometry_id'] not in {tailpick['geometry_id'],rankpick['geometry_id']}],key=lambda r:(-(float(r['tail_localization_score'])+float(r['ranking_disambiguation_score']))/2,float(r['redundancy_score']),-int(r['geometry_hash'][:16],16)))
backups=[]
for q in (tailq,rankq,mixq):
 for r in q:
  if r['geometry_id'] not in [x['geometry_id'] for x in backups]:backups.append(r)
  if len(backups)>=6:break
 if len(backups)>=6:break
for i,r in enumerate(backups,1):r['backup_rank']=i;r['backup_queue']=('tail' if r in tailq[:len(tailq)] else 'ranking')
wr('candidate_selection_scores.csv',rows);wr('ranking_disambiguation_audit.csv',[r for r in sorted(rows,key=lambda x:sortkey(x,'ranking_disambiguation_score'))]);wr('ps_information_audit.csv',rows)
def rationale(r,role):
 d=ds(r['geometry_id']);near3=sorted((float(np.linalg.norm((d-ds(g))/230.0)),g) for g in formal)[:3];return {'geometry_id':r['geometry_id'],'geometry_hash':r['geometry_hash'],'ordered_D1_D6':[int(x) for x in d],'role':role,'nearest_HF20_geometries':[{'geometry_id':g,'physical_distance':dist} for dist,g in near3],'physical_distance_to_G01':r['g01_physical_distance'],'LF_response_similarity_to_G01':r['g01_lf_response_similarity'],'LF_eta_plus1_broadband_mean':r['lf_eta_plus1'],'LF_eta_plus1_min_proxy':r.get('lf_eta_plus1'),'LF_eta_plus1_450nm_proxy':r.get('lf_eta_plus1'),'Ridge_prediction':r['ridge_eta_plus1'],'residual_MLP_prediction':r['residual_mlp_eta_plus1'],'CNN_prediction':r['cnn_eta_plus1'],'residual_tail_score':r['tail_localization_score'],'ranking_disambiguation_score':r['ranking_disambiguation_score'],'PS_information_score':r['predicted_ps_contrast'],'redundancy_score':r['redundancy_score'],'expected_information_value':'proxy only; no HF truth','why_preferred':'highest frozen role-specific score after anti-duplication and deterministic hash tie-break'}
primary=[rationale(tailpick,'TAIL-LOCALIZATION'),rationale(rankpick,'RANKING-DISAMBIGUATION')];(O/'primary2_selection.json').write_text(json.dumps({'status':'PASS','preregistration_sha256':ph,'primary_count':2,'primary':primary,'future_cases':4,'future_rows':44},indent=2)+'\n',encoding='utf-8');(O/'candidate_rationale.json').write_text(json.dumps({'primary':primary,'backups':[rationale(r,'BACKUP') for r in backups]},indent=2)+'\n',encoding='utf-8');wr('backup_ranking.csv',[{'rank':i+1,'geometry_id':r['geometry_id'],'geometry_hash':r['geometry_hash'],'tail_score':r['tail_localization_score'],'ranking_score':r['ranking_disambiguation_score'],'ps_score':r['predicted_ps_contrast'],'redundancy_score':r['redundancy_score']} for i,r in enumerate(backups)])
sets={'proposed_Primary2':[tailpick,rankpick],'residual_score_top2':sorted(rows,key=lambda r:sortkey(r,'residual_tail_score_norm'))[:2],'performance_only_top2':sorted(rows,key=lambda r:sortkey(r,'performance_score_norm'))[:2],'ranking_ambiguity_top2':sorted(rows,key=lambda r:sortkey(r,'ranking_ambiguity_score'))[:2]};random.Random(20260816).shuffle(rows);sets['random2_seeded_20260816']=rows[:2]
def setmetrics(z):return {'geometry_ids':[x['geometry_id'] for x in z],'tail_localization_mean':float(np.mean([x['tail_localization_score'] for x in z])),'ranking_disambiguation_mean':float(np.mean([x['ranking_disambiguation_score'] for x in z])),'ps_information_mean':float(np.mean([float(x['predicted_ps_contrast']) for x in z])),'redundancy_mean':float(np.mean([x['redundancy_score'] for x in z])),'lf_response_diversity':float(np.std([float(x['lf_eta_plus1']) for x in z])),'role_counts':dict(defaultdict(int))}
comp={k:setmetrics(v) for k,v in sets.items()};(O/'baseline_acquisition_comparison_m8a.csv').write_text('baseline,selected_geometry_ids,tail_mean,ranking_mean,ps_mean,redundancy_mean,lf_eta_plus1_std\n'+'\n'.join(f"{k},\"{v['geometry_ids']}\",{v['tail_localization_mean']},{v['ranking_disambiguation_mean']},{v['ps_information_mean']},{v['redundancy_mean']},{v['lf_response_diversity']}" for k,v in comp.items())+'\n',encoding='utf-8')
first4=[tailpick,rankpick]+backups[:2];(O/'marginal_primary2_vs_first4.json').write_text(json.dumps({'primary2':setmetrics([tailpick,rankpick]),'optional_first4':setmetrics(first4),'marginal_gain':{k:setmetrics(first4)[k]-setmetrics([tailpick,rankpick])[k] for k in ('tail_localization_mean','ranking_disambiguation_mean','ps_information_mean','redundancy_mean','lf_response_diversity')},'solver_cost':{'primary2_cases':4,'primary2_rows':44,'optional_first4_cases':8,'optional_first4_rows':88},'recommendation':'PRIMARY2_ONLY_RECOMMENDED'},indent=2)+'\n',encoding='utf-8')
(O/'solver_cost_budget.json').write_text(json.dumps({'primary2':{'geometries':2,'formal_cases':4,'rows':44,'runtime':'4 MPI x 1 thread'},'optional_first4':{'geometries':4,'formal_cases':8,'rows':88},'median_wall_estimate':'use frozen M6 cost package; no new solver timing','p90':'not newly measured; report as risk range only','max_risk_note':'license/messaging and long-tail runtime risk; no concurrency optimum claim','solver_calls':0},indent=2)+'\n',encoding='utf-8')
(O/'future_success_criteria.json').write_text(json.dumps(pr['future_success_criteria'],indent=2)+'\n',encoding='utf-8');(O/'plateau_stop_rule.json').write_text(json.dumps({'rule':pr['plateau_stop_rule'],'automatic_additional_HF_after_primary2':False},indent=2)+'\n',encoding='utf-8');(O/'solver_zero_audit.json').write_text(json.dumps({'solver_calls':0,'new_hf':0,'external_hf':0,'sealed_target_reads':0,'inverse_design':0,'external_overlap':0,'sealed_overlap':0},indent=2)+'\n',encoding='utf-8');(O/'provenance_audit.json').write_text(json.dumps({'status':'PASS','preregistration_sha256':ph,'candidate_universe_sha256':pr['authority']['candidate_universe_sha256'],'m8_prereg_sha256':pr['authority']['m8_preregistration_sha256'],'external_target_reads':0,'sealed_target_reads':0,'candidate_identities_generated_after_prereg_hash':True},indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':'PASS','primary':[tailpick['geometry_id'],rankpick['geometry_id']],'backups':[r['geometry_id'] for r in backups],'preregistration_sha256':ph}))
