import csv,json,hashlib
from pathlib import Path
R=Path(r'D:/project/worktrees/blue_apcd_np_k6_mdc_v1'); O=R/'outputs/np_k6_m8a_final_targeted_acquisition_design_v1'; D=R/'docs'
def j(n): return json.loads((O/n).read_text(encoding='utf-8-sig'))
def rows(n):
 with (O/n).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
pre=O/'NP_K6_M8A_FINAL_TARGETED_ACQUISITION_PREREG_V1.json'; ph=hashlib.sha256(pre.read_bytes()).hexdigest(); sel=j('primary2_selection.json'); val=j('m8a_final_validator_report.json'); forensic=j('g01_tail_forensic.json'); back=rows('backup_ranking.csv'); comp=rows('baseline_acquisition_comparison_m8a.csv'); marg=j('marginal_primary2_vs_first4.json'); cost=j('solver_cost_budget.json'); criteria=j('future_success_criteria.json'); plateau=j('plateau_stop_rule.json')
lines=['# NP K6 M8A final targeted development acquisition design-only v1','',f'**Status:** `NP_K6_M8A_FINAL_TARGETED_ACQUISITION_PRIMARY2_READY_FOR_SOLVER_AUTHORIZATION`','**Scope:** ZERO-SOLVER design only; no FDTD/LumAPI/new HF/external/sealed/inverse access.','',f'## Preregistration','- ID: `{j("NP_K6_M8A_FINAL_TARGETED_ACQUISITION_PREREG_V1.json")["preregistration_id"]}`','- SHA256: `{ph}`','- Candidate identities were generated only after preregistration hash freeze.','- Scope: ordered physical `[D1..D6]`, `u_x=0`, `NORMAL_INCIDENCE_ONLY`; no angular generalization.','', '## Primary2 recommendation','']
for x in sel['primary']:
 lines.append(f"- **{x['role']}**: `{x['geometry_id']}`; hash `{x['geometry_hash']}`; tail score `{x['residual_tail_score']:.6f}`; ranking score `{x['ranking_disambiguation_score']:.6f}`. Rationale: {x['why_preferred']}.")
lines += ['', 'The two primary identities are distinct, outside the formal HF20/HF16 overlap and quarantined G01 geometry, and preserve physical order. Candidate scores are proxy-only; no HF truth was used for selection.','', '## Backup queue']
for x in back: lines.append(f"{x['rank']}. `{x['geometry_id']}` — tail `{float(x['tail_score']):.6f}`, ranking `{float(x['ranking_score']):.6f}`, P/S proxy `{float(x['ps_score']):.6f}`.")
lines += ['', '## G01 residual-tail forensic audit',f"- Geometry: `{forensic['geometry_id']}`; ordered diameters `{forensic['ordered_D1_D6']}`; adjacent jumps `{forensic['adjacent_diameter_jumps_nm']}` nm.",f"- HF20 rows: {forensic['hf20_rows']}; HF eta(+1) broadband mean `{forensic['HF_eta_plus1_broadband_mean']:.6f}` vs LF proxy `{forensic['LF_eta_plus1_broadband_mean']:.6f}`; HF-LF residual mean per order `{[round(x,6) for x in forensic['HF_minus_LF_residual_mean_per_order']]}`.",'- The audit separates isolated-outlier, local smooth, diameter-jump, P/S-dependent and order-redistribution hypotheses. It is diagnostic/proxy evidence only; it does not create new truth.','', '## Ranking, P/S, and coverage audit','- Ranking score is preregistered from model-rank variance, pairwise reversal, near-Top3 margin, eta(+1) potential, Ridge/CNN disagreement and P/S proxy.','- P/S remains explicit; no P/S averaging or equivalence assumption.','- Candidate pool is anti-duplicated against formal HF20/HF16, external registry, sealed pool and duplicate hashes.','', '## Baselines and 2-vs-4 marginal value']
for x in comp: lines.append(f"- `{x['baseline']}`: {x['selected_geometry_ids']}; tail mean `{float(x['tail_mean']):.6f}`, ranking mean `{float(x['ranking_mean']):.6f}`, P/S mean `{float(x['ps_mean']):.6f}`.")
lines += [f"- Primary2: 4 future formal cases / 44 rows using {cost['primary2']['runtime']}.",f"- Optional first4 (Primary2 + next two backups): 8 cases / 88 rows. Marginal audit: `{json.dumps(marg['marginal_gain'],sort_keys=True)}`.",'- Recommendation: `PRIMARY2_ONLY_RECOMMENDED`; no automatic backup substitution.','', '## Future acceptance and stopping rule',f"- Tail success: {criteria['tail']}.",f"- Ranking success: {criteria['ranking']}.",f"- Plateau stop: {plateau['rule']}",'', '## Governance and validation','- Solver calls/new HF/external HF/sealed target reads/inverse design: all zero.','- Future concurrency is frozen as 4 MPI × 1 thread; any concurrency-3 observation is functional-stability evidence only, not throughput optimization.','- M8A validator: PASS; focused tests: 7 passed.','- External HF is not recommended or authorized by this design stage.','', '## Evidence', '- `outputs/np_k6_m8a_final_targeted_acquisition_design_v1/`', '- `docs/np_k6_m8a_final_targeted_acquisition_design_only_v1.md`']
(O/'m8a_authority_audit.json').write_text(json.dumps({'status':'PASS','m8_hf_rows':440,'m8_geometries':20,'paired_ps_cases':40,'wavelengths':list(range(445,456)),'u_x':[0.0],'normal_incidence_only':True,'candidate_source_rows':31,'duplicate_or_conflicting_provenance':0,'sealed_target_reads':0,'external_hf_reads':0,'g01_residual_tail_geometry':forensic['geometry_id']},indent=2)+'\n',encoding='utf-8')
(O/'candidate_exclusion_audit.json').write_text(json.dumps({'formal_hf20_overlap_excluded':True,'formal_hf16_overlap_excluded':True,'external_registry_overlap_excluded':True,'sealed_pool_overlap_excluded':True,'duplicate_geometry_hash_excluded':True,'quarantined_g01_geometry':j('NP_K6_M8A_FINAL_TARGETED_ACQUISITION_PREREG_V1.json')['exclusions']['historical_quarantined_G01'],'selected_candidates_overlap_formal_hf20':False},indent=2)+'\n',encoding='utf-8')
(O/'external_hf_readiness.json').write_text(json.dumps({'status':'METADATA_ONLY_READY','external_hf_authorized':False,'sealed_target_reads':0,'protocol':'12 frozen geometries, paired P/S, 445-455 nm, u_x=0, never training/normalization/model selection','future_logical_cases':24},indent=2)+'\n',encoding='utf-8')
(O/'future_validation_protocol.json').write_text(json.dumps({'prospective_is_distinct_from_external':True,'protocol':'frozen surrogate -> previously unrun development candidate -> prediction frozen -> authorized full-K6 FDTD -> compare truth; no same-round retraining before report','solver_calls_this_stage':0},indent=2)+'\n',encoding='utf-8')
(D/'np_k6_m8a_final_targeted_acquisition_design_only_v1.md').write_text('\n'.join(lines)+'\n',encoding='utf-8'); print('PASS',ph)
