from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1];run=ROOT/'outputs'/'mdc_fdtd_dipole_tmm_validation_v1'/'fdtd-matrix-20260729T092000Z-602d89c69258';data=json.loads((run/'forensic'/'forensic.json').read_text())
reports=ROOT/'reports';reports.mkdir(exist_ok=True)
def dump(n,v): (reports/n).write_text(json.dumps(v,indent=2,sort_keys=True),encoding='utf-8')
salvage={'classification':data['original_readback']['classification'],'original':data['original_after'],'short_copy':data['short_copy'],'fresh_readback':data['short_readback'],'monitor_results_available':data['original_readback']['results'],'original_unchanged':data['original_before']==data['original_after'],'solver_calls_this_task':0}
retention={'contract_id':'MDC_FDTD_ARTIFACT_RETENTION_V1','runtime_root':r'D:\apcd_runtime\mdc_fdtd_validation_v1','rules':['unique never-existing Lumerical runtime filename','close session before copy','fresh load before canonical byte copy','SHA equality required','no direct Lumerical save to deep canonical worktree'],'diagnosis':data['retention_diagnosis'],'zero_solver_tests':data['zero_solver_tests'],'solver_calls_this_task':0}
budget=data['budget']|{'remaining_solver_capacity':data['remaining_solver_capacity'],'remaining_unique_cases':data['remaining_unique_cases'],'decision':'VALID_COMPLETE salvage; remaining 17 cases fit current cap=19 without rerunning x'}
for n,v in [('mdc_fdtd_post_fsp_forensic_salvage_v1.json',salvage),('mdc_fdtd_artifact_retention_contract_v1.json',retention),('mdc_fdtd_solver_budget_reconciliation_v1.json',budget)]:dump(n,v)
for n,title,body in [('mdc_fdtd_post_fsp_forensic_salvage_v1.md','MDC post-FSP forensic salvage v1','The original post-FSP is VALID_COMPLETE: fresh load, geometry objects and upward monitor E/T results are available. Original SHA/mtime remained unchanged.'),('mdc_fdtd_artifact_retention_contract_v1.md','MDC artifact retention contract v1','Future Lumerical saves use unique short runtime paths; only readback-validated files are copied byte-for-byte to canonical outputs with SHA equality.'),('mdc_fdtd_solver_budget_reconciliation_v1.md','MDC solver budget reconciliation v1','Actual solver invocations=2; cap=19; the salvaged x case is complete, leaving capacity=17 and 17 unique cases.')]: (reports/n).write_text('# '+title+'\n\n'+body+'\n',encoding='utf-8')
