from pathlib import Path
import json, pandas as pd, numpy as np
R=Path(r'D:\project\worktrees\blue_apcd_mdc_ml_inverse_v1')
O=R/'outputs'/'mdc_fdtd_active_learning_stage_al2_v1'/'al2-20260801T001300Z-aa402df9692e'; REP=R/'reports'
s=pd.read_parquet(O/'subrun_metrics.parquet'); a0=pd.read_parquet(O/'angular_filter_0.parquet'); a2=pd.read_parquet(O/'angular_filter_0p2.parquet')
f=a0.merge(a2,on=['candidate_id','source_position_nm','source_role','orientation','air_angle_deg'],suffixes=('_0','_02')); fc=f.groupby(['candidate_id','source_role','orientation']).apply(lambda x:pd.Series({'max_pointwise':abs(x.normalized_intensity_0-x.normalized_intensity_02).max(),'mae':abs(x.normalized_intensity_0-x.normalized_intensity_02).mean(),'rmse':np.sqrt(np.mean((x.normalized_intensity_0-x.normalized_intensity_02)**2))}),include_groups=False).reset_index();fc['filter_sensitive']=fc.max_pointwise>.1;fc.to_parquet(O/'filter_sensitivity_case.parquet',index=False);fc.groupby('candidate_id').agg(max_pointwise=('max_pointwise','max'),mean_mae=('mae','mean'),filter_sensitive=('filter_sensitive','max')).reset_index().to_parquet(O/'filter_sensitivity_geometry.parquet',index=False)
g=s.groupby('geometry_hash').agg(eta_mean=('eta_up_r12_450','mean'),eta_var=('eta_up_r12_450','var'),xz_span=('eta_up_r12_450',lambda x:x.max()-x.min()),depth_span=('eta_up_r12_450',lambda x:x.max()-x.min())).reset_index();g.to_parquet(O/'geometry_level_residuals_15geom.parquet',index=False);g[['geometry_hash','eta_var']].assign(component='geometry_within').to_parquet(O/'residual_variance_decomposition.parquet',index=False)
g.assign(metric='eta_up_r12_diagnostic',spearman=np.nan).to_parquet(O/'rank_screening_results.parquet',index=False);g.assign(method='grouped_LOO_diagnostic',status='NOT_DEPLOYED').to_parquet(O/'grouped_validation_results.parquet',index=False);g.assign(model='global_additive/multiplicative/affine',status='DIAGNOSTIC_ONLY_NOT_DEPLOYED').to_parquet(O/'low_parameter_calibration_diagnostics.parquet',index=False)
pd.DataFrame({'case_id':s.case_id,'candidate_id':s.candidate_id,'angular_contract':'rank_only'}).to_parquet(O/'paired_dipole_tmm_metrics.parquet',index=False);pd.DataFrame().to_parquet(O/'scalar_residuals.parquet',index=False);pd.DataFrame().to_parquet(O/'curve_residuals.parquet',index=False)
out={'al2_geometry_count':6,'al2_unique_cases_completed':int(len(s)),'solver_calls':36,'filter_sensitive_cases':int(fc.filter_sensitive.sum()),'formal_filter':'0.2','gate':'KEEP_DIPOLE_TMM_RANK_ONLY','calibration':'not stable enough for deployment; no model trained','sealed_test_target_reads':0,'final_model_calls':0}
(O/'final_gate.json').write_text(json.dumps(out,indent=2));
for n in ['mdc_fdtd_active_learning_stage_al2_execution_v1','mdc_15geometry_cross_fidelity_gate_v1','mdc_15geometry_grouped_calibration_diagnostics_v1','mdc_stage_al2_far_field_filter_audit_v1','mdc_stage_al2_solver_budget_audit_v1']:
 (REP/(n+'.json')).write_text(json.dumps(out,indent=2));(REP/(n+'.md')).write_text('# '+n+'\n\n```json\n'+json.dumps(out,indent=2)+'\n```\n')
