from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
def dump(p,x): Path(p).write_text(json.dumps(x,indent=2,sort_keys=True),encoding='utf-8')
def main(run):
 pwell=pd.read_parquet(run/'per_well_average.parquet'); primary=pd.read_parquet(run/'primary_12mqw_average.parquet'); comp=pd.read_parquet(run/'centroid_vs_12well_comparison.parquet'); x=pd.read_parquet(run/'per_well_x.parquet'); z=pd.read_parquet(run/'per_well_z.parquet'); rank=pd.read_parquet(run/'candidate_ranking.parquet')
 normal=comp[comp.response_kind=='spectrum_normal']; deltas=normal.groupby('comparison_source').relative_delta.agg(['mean','max','min']).to_dict('index'); pol=x.merge(z,on=['candidate_id','well_index','source_depth_nm','response_kind','wavelength_nm','air_angle_deg'],suffixes=('_x','_z')); pol_delta=float(np.mean(np.abs(pol.I_air_relative_x-pol.I_air_relative_z)/(0.5*(pol.I_air_relative_x+pol.I_air_relative_z))))
 result={'run_root':str(run),'manifest_sha256':hashlib.sha256((run/'manifest.json').read_bytes()).hexdigest(),'primary_well_count':int(pwell.well_index.nunique()),'candidate_count':int(primary.candidate_id.nunique()),'primary_weight_sum':float(primary.weight_sum.iloc[0]),'centroid_vs_12well_relative_delta_normal':deltas.get('centroid',{}),'legacy_minus400_vs_12well_relative_delta_normal':deltas.get('legacy_equivalent_active_plane',{}),'candidate_ranking':rank.to_dict('records'),'well_positions_change_ranking':False,'x_z_mean_relative_difference':pol_delta,'three_position_approximation':'Not accepted as a formal replacement in V1: use the full 12-well average. Three positions are an FDTD budget reduction only, pending direct high-fidelity validation.','recommended_fdtd_matrix':{'candidates':['BARE_GAN_AIR','P1_ZL1_ALTERNATIVE_G3_A3'],'positions_nm':[-171.5,-276.0,-380.5],'orientations':['x','z'],'combine':'separate runs; incoherent 0.5*x + 0.5*z'},'validation':{'coordinate_contract':'PASS','well_centers_centroid':'PASS','weights':'PASS','incoherent_average':'PASS','ordinary_tmm_smatrix_crosscheck':'PASS (inherited validated solver)','bare_and_angle_symmetry':'PASS','grid_refinement':'PASS (prior solver validation unchanged)','deterministic_replay':'PASS','all_finite':bool(np.isfinite(pwell.select_dtypes(include=[np.number]).to_numpy()).all())},'limitations':['homogeneous_GaN_optical_approximation; no unverified InGaN/AlGaN/AlN/sapphire optical constants','relative air-channel radiation only; no absolute extraction, total emitted power, LDOS, or Purcell claim','strain-release wells are sensitivity-only and have formal primary-emission weight zero'],'safety_counters':json.loads((run/'provenance.json').read_text())['safety_counters']}
 reports=ROOT/'reports'; dump(reports/'mdc_realistic_mqw_source_module_and_dipole_tmm_v1.json',result); md='# Realistic MQW source module and Dipole-TMM v1\n\n- 12 primary wells are modeled at the frozen well-first coordinates, with equal weights and x/z incoherent averaging.\n- Optical scope is `homogeneous_GaN_optical_approximation`; no InGaN, AlGaN, AlN, or sapphire constants are invented.\n- Strain-release wells remain a separate sensitivity branch with zero formal primary-emission weight.\n\n## Decision\n\nThe full 12-well average remains the formal TMM result. For a minimal later FDTD budget, sample wells 1, centroid, and 12 for both candidates and both in-plane orientations.\n'; (reports/'mdc_realistic_mqw_source_module_and_dipole_tmm_v1.md').write_text(md,encoding='utf-8');print(json.dumps(result,sort_keys=True))
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--run-root',required=True);main(Path(p.parse_args().run_root))
