from __future__ import annotations
from typing import Any

def _metric(result: dict[str, Any], key: str) -> Any:
    return result.get(key) if result.get(key) is not None else {'value': None, 'reason': result.get('not_applicable', {}).get(key, 'NOT_AVAILABLE')}

def row_from_result(result: dict[str, Any], comparison_id: str) -> dict[str, Any]:
    return {'comparison_id':comparison_id,'control_group':result.get('control_group'),'mdc_candidate_id':result.get('mdc_candidate_id'),'np_candidate_id':result.get('np_candidate_id'),'interface_id':result.get('interface_id'),'wavelength_nm':result.get('wavelength_nm'),'polarization':result.get('polarization'),'kx_over_k0':result.get('kx_over_k0'),'R_total':result.get('R_total'),'T_total':result.get('T_total'),'loss_or_residual':result.get('loss_or_residual',result.get('power_closure',{}).get('residual_1_minus_R_minus_T')),'eta_t_orders':result.get('eta_t_orders'),'eta_r_orders':result.get('eta_r_orders'),'eta_plus1':_metric(result,'eta_plus1'),'eta_zero':_metric(result,'eta_zero'),'eta_minus1':_metric(result,'eta_minus1'),'theta_plus1':_metric(result,'theta_out_plus1_deg'),'directionality':_metric(result,'directionality'),'power_closure':result.get('power_closure'),'order_closure':result.get('order_closure'),'entry_pre_fsp_sha':result.get('pre_fsp_sha256'),'mutated_pre_fsp_sha':result.get('pre_fsp_current_sha256'),'post_fsp_sha':result.get('post_fsp_sha256'),'source_contract':result.get('source_contract_id'),'material_contract':result.get('material_contract_id'),'mesh_contract':result.get('mesh_contract_id'),'provenance_status':'PASS' if result.get('solver_entered') and result.get('solver_completed') else 'INCOMPLETE','result_path':result.get('result_path')}

def standalone_row(reference: dict[str, Any], source_path: str, source_commit: str, artifact_sha: str) -> dict[str, Any]:
    return {'comparison_id':'NP_R0_STANDALONE_REFERENCE','control_group':'NP_R0','mdc_candidate_id':None,'np_candidate_id':'NP_K6X_125_135_150_175_190_210','interface_id':'STANDALONE_SIO2_SUBSTRATE','wavelength_nm':450,'polarization':'x','kx_over_k0':0.0,'R_total':{'value':None,'reason':'R/T not present in authoritative standalone artifact'},'T_total':{'value':None,'reason':'R/T not present in authoritative standalone artifact'},'loss_or_residual':{'value':None,'reason':'R/T not present in authoritative standalone artifact'},'eta_t_orders':{'plus1':float(reference['plus1_absolute_efficiency']),'zero':float(reference['zero_absolute_efficiency']),'minus1':float(reference['minus1_absolute_efficiency']),'reason':'partial authoritative order metrics'},'eta_r_orders':{'reason':'reflected order spectrum not present in authoritative standalone artifact'},'eta_plus1':float(reference['plus1_absolute_efficiency']),'eta_zero':float(reference['zero_absolute_efficiency']),'eta_minus1':float(reference['minus1_absolute_efficiency']),'theta_plus1':float(reference.get('plus1_angle_450_deg')) if reference.get('plus1_angle_450_deg') is not None else {'value':None,'reason':'angle unavailable'},'directionality':float(reference['directionality']),'power_closure':{'status':'NOT_AVAILABLE','reason':'R/T not present in authoritative standalone artifact'},'order_closure':{'status':'NOT_AVAILABLE','reason':'full order spectrum not present in authoritative standalone artifact'},'entry_pre_fsp_sha':None,'mutated_pre_fsp_sha':None,'post_fsp_sha':None,'source_contract':{'value':None,'reason':'not recorded in standalone artifact'},'material_contract':{'value':None,'reason':'not recorded in standalone artifact'},'mesh_contract':{'value':None,'reason':'not recorded in standalone artifact'},'provenance_status':'AUTHORITATIVE_REFERENCE_READ_ONLY','result_path':source_path,'source_commit':source_commit,'artifact_sha256':artifact_sha}

def _v(row: dict[str, Any], key: str):
 value=row.get(key); return value if isinstance(value,(int,float)) else None

def delta(a: dict[str, Any], b: dict[str, Any], keys: tuple[str,...]) -> dict[str, Any]:
 out={}
 for key in keys:
  av=_v(a,key); bv=_v(b,key); out[key]=av-bv if av is not None and bv is not None else {'value':None,'reason':'N/A: one comparison row lacks this metric'}
 return out

def build_comparison(rows: dict[str, dict[str, Any]], standalone: dict[str, Any]) -> dict[str, Any]:
 b0,b1,b2,b3=(rows[k] for k in ('B0','B1','B2','B3'))
 return {'schema_version':'stage_a_control_comparison_v1','comparison_id':'APCD_MDC_NP_COUPLING_V1_STAGE_A_CONTROL_MATRIX','conditions':{'wavelength_nm':450,'polarization':'x','incidence':'normal','kx_over_k0':0.0,'ky_over_k0':0.0,'period_x_nm':1740,'period_y_nm':290},'rows':[standalone,*rows.values()],'attribution':{'mdc_only_B1_minus_B0':{'delta_R':delta(b1,b0,('R_total',))['R_total'],'delta_T':delta(b1,b0,('T_total',))['T_total'],'delta_loss_or_residual':delta(b1,b0,('loss_or_residual',))['loss_or_residual'],'m0_B0':next((x['power_fraction_of_source'] for x in b0['eta_t_orders'] if x['m']==0),None),'m0_B1':next((x['power_fraction_of_source'] for x in b1['eta_t_orders'] if x['m']==0),None),'interpretation':'Uniform MDC changes reflection/transmission and loss redistribution; nonzero orders are numerical leakage only.'},'finite_support_B2_minus_NP_R0':delta(b2,standalone,('eta_plus1','eta_zero','eta_minus1','directionality','R_total','T_total')),'full_mdc_B3_minus_B2':delta(b3,b2,('eta_plus1','eta_zero','eta_minus1','directionality','R_total','T_total','loss_or_residual')),'full_integrated_B3_minus_NP_R0':delta(b3,standalone,('eta_plus1','eta_zero','eta_minus1','directionality','R_total','T_total')),'order_redistribution':{'B0':{'transmitted_orders':b0['eta_t_orders'],'reflected_orders':b0['eta_r_orders']},'B1':{'transmitted_orders':b1['eta_t_orders'],'reflected_orders':b1['eta_r_orders']},'B2':{'transmitted_orders':b2['eta_t_orders'],'reflected_orders':b2['eta_r_orders']},'B3':{'transmitted_orders':b3['eta_t_orders'],'reflected_orders':b3['eta_r_orders']}},'interpretation':'B2 isolates finite 79 nm support plus GaN environment; B3 minus B2 isolates the added full MDC underlayer under the same source/cell contract. Residual changes are not assigned to GaN absorption alone without volumetric absorption evidence.'},'provenance_status':'PASS'}
