from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; sys.path.insert(0,str(ROOT/'scripts/coupling'))
from build_control_group_case import readback,validate

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--output-dir',type=Path,required=True); ap.add_argument('--material-helper-root',type=Path,required=True); a=ap.parse_args(); out=a.output_dir.resolve(); setup=json.loads((out/'setup_manifest.json').read_text(encoding='utf-8')); runtime=json.loads((out/'runtime/attempt_001/run_state.json').read_text(encoding='utf-8')); case=json.loads((out/'joint_case.json').read_text(encoding='utf-8')); ledger=json.loads((out/'runtime/attempt_001/entered_ledger.json').read_text(encoding='utf-8')); runtime.setdefault('pre_fsp_entry_sha256',ledger.get('pre_fsp_entry_sha256',ledger.get('pre_fsp_sha256'))); post=Path(runtime['post_fsp_path']); rb=readback(case,post,a.material_helper_root); gate=validate(case,rb); pre=setup['readback']; identity={'stack_identity_unchanged':rb['stack_objects']==pre['stack_objects'],'np_geometry_identity_unchanged':rb['np_pillars']==pre['np_pillars'],'source_identity_unchanged':rb['source']==pre['source'],'monitor_identity_unchanged':rb['monitors']==pre['monitors'],'material_identity_unchanged':rb['materials']==pre['materials'],'solver_identity_gate':gate['pass']}; audit={'schema_version':'stage_a_control_post_fsp_identity_audit_v1','case_id':case['case_id'],'control_group':case['control_group'],'post_fsp_path':str(post),'post_fsp_sha256':runtime['post_fsp_sha256'],'pre_fsp_entry_sha256':runtime['pre_fsp_entry_sha256'],'pre_fsp_current_sha256':runtime['pre_fsp_current_sha256'],'pre_fsp_post_entry_mutation':runtime['pre_fsp_post_entry_mutation'],'readback':rb,'setup_gate_replay':gate,'identity_checks':identity,'pass':all(identity.values())}; (out/'post_fsp_readback.json').write_text(json.dumps(rb,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); (out/'post_fsp_identity_audit.json').write_text(json.dumps(audit,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); print(json.dumps({'case_id':case['case_id'],'control_group':case['control_group'],'pass':audit['pass'],'identity_checks':identity},indent=2));
 if not audit['pass']: raise SystemExit('POST_FSP_IDENTITY_FAIL')
if __name__=='__main__': main()
