from __future__ import annotations
import argparse,hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; sys.path.insert(0,str(ROOT/'src'))
from apcd_coupling.comparison_engine import row_from_result,standalone_row,build_comparison

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--output-dir',type=Path,required=True); ap.add_argument('--fixture-registry',type=Path,required=True); args=ap.parse_args(); cfg=json.loads(args.fixture_registry.read_text(encoding='utf-8')); dirs={'B0':ROOT/'outputs/coupling/stage_a_b0_450nm_xpol_normal_v1','B1':ROOT/'outputs/coupling/stage_a_b1_450nm_xpol_normal_v1','B2':ROOT/'outputs/coupling/stage_a_b2_450nm_xpol_normal_v1','B3':ROOT/'outputs/coupling/stage_a_450nm_xpol_normal_textra0_golden_fixture_v1'}; results={k:json.loads((p/'results/result.json').read_text(encoding='utf-8')) for k,p in dirs.items()}; rows={k:row_from_result(v,k) for k,v in results.items()}; ref_cfg=cfg['standalone_reference']; refpath=Path(ref_cfg['path']); ref_full=json.loads(refpath.read_text(encoding='utf-8')); ref=ref_full['at_450_nm']; ref['plus1_angle_450_deg']=ref_full.get('plus1_angle_450_deg'); standalone=standalone_row(ref,str(refpath),ref_cfg['source_commit'],sha(refpath)); artifact=build_comparison(rows,standalone); artifact['result_paths']={k:str(dirs[k]/'results/result.json') for k in dirs}; artifact['output_schema_fields']=['comparison_id','mdc_candidate_id','np_candidate_id','interface_id','wavelength_nm','polarization','kx_over_k0','R_total','T_total','loss_or_residual','eta_t_orders','eta_r_orders','eta_plus1','eta_zero','eta_minus1','theta_plus1','directionality','power_closure','order_closure','entry_pre_fsp_sha','mutated_pre_fsp_sha','post_fsp_sha','source_contract','material_contract','mesh_contract','provenance_status']; args.output_dir.mkdir(parents=True,exist_ok=True); (args.output_dir/'comparison_matrix.json').write_text(json.dumps(artifact,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); print(json.dumps({'path':str(args.output_dir/'comparison_matrix.json'),'status':artifact['provenance_status'],'rows':[x['comparison_id'] for x in artifact['rows']]},indent=2))
if __name__=='__main__': main()
